84 report default values are not coherent after read
KhiopsML/khiops-python pull request #111
Opened 2023-11-08 12:57 UTC by folmos-at-orange

2023-11-08 17:55 UTC, popescu-v requested changes

2023-11-10 10:44 UTC, folmos-at-orange commented on khiops/core/internals/io.py
> +    First it tries a vanille read, then if that fails it warns and then loads the files
Ok

2023-11-10 10:45 UTC, folmos-at-orange commented on tests/resources/analysis_results/ref_json_reports/Iris2D.khj
> +      "mainTargetValue": "Iris-setosa"
Ok. They are tabs most likely

2023-11-10 13:48 UTC, folmos-at-orange commented on tests/resources/analysis_results/ref_json_reports/Iris2D.khj
> +      "mainTargetValue": "Iris-setosa"
Ok

2023-11-10 13:49 UTC, folmos-at-orange commented on tests/test_core.py
> +                        domain = kh.read_dictiojary_file(ref_kdicj)
Good one, I wonder how it managed to pass the tests.

2023-11-10 13:50 UTC, folmos-at-orange commented on khiops/core/analysis_results.py
> +        # Call the parent's initialization
Every paragraph has a comment. We accept some overhead.

2023-11-10 13:50 UTC, folmos-at-orange commented on khiops/core/coclustering_results.py
>          # Initialize base class
See above.

2023-11-10 13:55 UTC, folmos-at-orange commented on khiops/core/analysis_results.py
> +            json_data = {}
Maybe the check could be refactored, but there are some methods where `json_data` is not a `dict`, so the refactored function would have a parameter. So we would have a wrapper for `type_error_message` which beats the purpose.

I would not refactor the second part because is slightly tricky: I reassign the input parameter `json_data`, normally I would be against this, but this time I let it go because of readability and low-risk (we reassign only when `None`).

So I would leave it as it is right now, even if it is repetitive.

2023-11-10 13:55 UTC, folmos-at-orange commented on khiops/core/analysis_results.py
> +            json_data = {}
See above.

2023-11-10 13:55 UTC, folmos-at-orange commented on khiops/core/analysis_results.py
> +        # Initialize attributes for a supervised data grid with several input vars.
Ok

2023-11-10 13:56 UTC, folmos-at-orange commented on khiops/core/analysis_results.py
> +            json_data = {}
See above.

2023-11-10 13:59 UTC, folmos-at-orange commented on khiops/core/coclustering_results.py
> +                dimension = CoclusteringDimension().init_summary(json_dimension_summary)
The no-parameter constructor pattern is everywhere in the JSON related classes. I would not make an exception just for one. 

I haven't gave a thought of what could be initialized immediately, but a priori if the data is not in the "current" object it could have been removed for storage reasons. I will discuss this with MB.

For now let's leave the pattern as it is.

2023-11-10 13:59 UTC, folmos-at-orange commented on khiops/core/coclustering_results.py
>              Dictionary representing the data of an element of the list found at the
Ok

2023-11-10 14:00 UTC, folmos-at-orange commented on khiops/core/coclustering_results.py
>          """See class docstring"""
Ok

2023-11-10 14:17 UTC, folmos-at-orange commented on khiops/core/coclustering_results.py
> +        self.cluster_name = json_data.get("cluster", "")
The `json_data = {}` is missing.

2023-11-10 14:18 UTC, folmos-at-orange commented on khiops/core/coclustering_results.py
>              Python dictionary representing the data of an element of the list found at
Ok, and I will make it optional.

2023-11-10 14:19 UTC, folmos-at-orange commented on khiops/core/coclustering_results.py
>              Python dictionary representing the data of an element of the list found at
I will remake it optional.

2023-11-10 14:19 UTC, folmos-at-orange commented on khiops/core/coclustering_results.py
>              Python dictionary representing the data of an element of the list found at
Ok

2023-11-10 14:20 UTC, folmos-at-orange commented on khiops/core/coclustering_results.py
> +        # Otherwise Raise an error if no values are found
Ok

2023-11-10 14:20 UTC, folmos-at-orange commented on khiops/core/dictionary.py
> +        # Initialize base attributes
See above.

2023-11-10 14:22 UTC, folmos-at-orange commented on khiops/core/dictionary.py
> +                raise KhiopsJSONError("variable/block name not found")
Nothing.

Ok, maybe we could dump the json object in the exception.

2023-11-10 14:53 UTC, folmos-at-orange commented on tests/test_core.py
> +                        domain = kh.read_dictiojary_file(ref_kdicj)
Done

2023-11-10 14:54 UTC, folmos-at-orange commented on tests/test_core.py
> +            break
Done

2023-11-10 14:55 UTC, folmos-at-orange commented on khiops/core/internals/io.py
> +    First it tries a vanille read, then if that fails it warns and then loads the files
Done

2023-11-10 14:57 UTC, folmos-at-orange commented on tests/resources/analysis_results/ref_json_reports/Iris2D.khj
> +      "mainTargetValue": "Iris-setosa"
Done

2023-11-10 14:59 UTC, folmos-at-orange commented on tests/resources/analysis_results/ref_json_reports/Iris2D.khj
> +      "mainTargetValue": "Iris-setosa"
Done

2023-11-10 15:00 UTC, folmos-at-orange commented on khiops/core/analysis_results.py
> +        # Initialize attributes for a supervised data grid with several input vars.
It was an abbreviation but now `variables` fit the line.

2023-11-10 15:24 UTC, folmos-at-orange commented on khiops/core/coclustering_results.py
>              Python dictionary representing the data of an element of the list found at
Done

2023-11-10 15:24 UTC, folmos-at-orange commented on khiops/core/coclustering_results.py
>              Python dictionary representing the data of an element of the list found at
Done

2023-11-10 15:24 UTC, folmos-at-orange commented on khiops/core/coclustering_results.py
>              Python dictionary representing the data of an element of the list found at
Done

2023-11-10 15:25 UTC, folmos-at-orange commented on khiops/core/coclustering_results.py
>              Python dictionary representing the data of an element of the list found at
Done

2023-11-10 15:26 UTC, folmos-at-orange commented on khiops/core/coclustering_results.py
>          """See class docstring"""
Done.

2023-11-10 15:27 UTC, folmos-at-orange commented on khiops/core/coclustering_results.py
> +        self.cluster_name = json_data.get("cluster", "")
Done

2023-11-10 15:27 UTC, folmos-at-orange commented on khiops/core/coclustering_results.py
> +        # Initialibze base class
I corrected the typo though.

2023-11-10 15:28 UTC, folmos-at-orange commented on khiops/core/coclustering_results.py
> +        # Otherwise Raise an error if no values are found
Done

2023-11-10 15:29 UTC, folmos-at-orange commented on khiops/core/dictionary.py
> +                raise KhiopsJSONError("variable/block name not found")
Done.

2023-11-10 15:30 UTC, folmos-at-orange commented on khiops/core/coclustering_results.py
>              Dictionary representing the data of an element of the list found at the
Done

2023-11-14 10:03 UTC, popescu-v requested changes

2023-11-14 10:03 UTC, popescu-v commented on tests/test_core.py
> +        # kh.EvaluationReport(json_data={"summary": None})
Why are these commented out? Either uncomment and add check on `cm`, or remove?

2023-11-14 10:05 UTC, folmos-at-orange commented on khiops/core/analysis_results.py
> +        # Check that the tool is the proper one (it was set by the parent)
The pattern is to put the comment before the `if/else` clauses. I will reword it so it is more readable.

2023-11-14 10:11 UTC, folmos-at-orange commented on khiops/core/analysis_results.py
>              self._predictors_performance_by_name[performance.name] = performance
I don't think it is necessary. These patterns differ by little and the factored function will have too many parameters.

2023-11-14 10:11 UTC, folmos-at-orange commented on khiops/core/analysis_results.py
> +            if not len(json_data) == 2 and not len(json_data) == 0:
Ok

2023-11-14 10:13 UTC, folmos-at-orange commented on khiops/core/coclustering_results.py
> +        # Initialize empty report attributes
It was a generic comment concerning the line just below. I will comment also the `if/else` block afterwards.

2023-11-14 10:13 UTC, folmos-at-orange commented on khiops/core/coclustering_results.py
> +            if "summary" not in json_data:
Ok

2023-11-14 10:14 UTC, folmos-at-orange commented on khiops/core/coclustering_results.py
> +            first_interval = self.parts[0]
Ok I'll additional checks for the `intervals` field.

2023-11-14 10:15 UTC, folmos-at-orange commented on khiops/core/coclustering_results.py
> +                if cluster.parent_cluster.child_cluster1 is None:
I agree but that would imply an API change.

2023-11-14 10:16 UTC, folmos-at-orange commented on khiops/core/coclustering_results.py
> +            self.upper_bound = json_bounds[1]
I'll add an additional check.

2023-11-14 10:17 UTC, folmos-at-orange commented on khiops/core/coclustering_results.py
> +        self.child_cluster2 = None
See above.

2023-11-14 10:17 UTC, folmos-at-orange commented on tests/test_core.py
> +        # kh.EvaluationReport(json_data={"summary": None})
I'll look into it.

2023-11-14 10:23 UTC, folmos-at-orange commented on khiops/core/analysis_results.py
> +        self._variables_statistics_by_name = {}
Ok.

2023-11-16 10:32 UTC, folmos-at-orange commented on khiops/core/coclustering_results.py
> +            if "summary" not in json_data:
Done

2023-11-16 10:35 UTC, folmos-at-orange commented on khiops/core/analysis_results.py
> +        self._variables_statistics_by_name = {}
Done

2023-11-16 14:59 UTC, folmos-at-orange commented on khiops/core/analysis_results.py
> +        # Check that the tool is the proper one (it was set by the parent)
Done

2023-11-16 15:00 UTC, folmos-at-orange commented on khiops/core/analysis_results.py
> +            if not len(json_data) == 2 and not len(json_data) == 0:
Done

2023-11-16 15:02 UTC, folmos-at-orange commented on khiops/core/coclustering_results.py
> +        # Initialize empty report attributes
Done

2023-11-16 15:05 UTC, folmos-at-orange commented on khiops/core/coclustering_results.py
> +            first_interval = self.parts[0]
Done

2023-11-16 15:07 UTC, folmos-at-orange commented on khiops/core/coclustering_results.py
> +            self.upper_bound = json_bounds[1]
Done

2023-11-16 15:15 UTC, folmos-at-orange commented on khiops/core/coclustering_results.py
> +            value.typicality = json_value_typicalities[i]
Done

2023-11-18 14:44 UTC, folmos-at-orange commented on tests/test_core.py
> +        # kh.EvaluationReport(json_data={"summary": None})
There were missing tests. I added them.

2023-11-20 12:06 UTC, popescu-v requested changes

2023-11-20 14:36 UTC, folmos-at-orange commented on khiops/core/analysis_results.py
> +            if not len(json_data) == 2 and not len(json_data) == 0:
This is done no?

2023-11-20 14:37 UTC, folmos-at-orange commented on khiops/core/coclustering_results.py
> +            if "summary" not in json_data:
This is done no ?

2023-11-20 14:38 UTC, folmos-at-orange commented on khiops/core/coclustering_results.py
> +            first_interval = self.parts[0]
It is checked in the constructor call below that line.

2023-11-20 14:45 UTC, folmos-at-orange commented on khiops/core/coclustering_results.py
> +                raise KhiopsJSONError("'bounds' key must be a list of length 2")
I think this is fine. It is a block for 1 "subject": checking "bounds". This pattern is everywhere. I shortcut it to `elif` only when there is a single if clause in the block.

2023-11-20 14:46 UTC, folmos-at-orange commented on khiops/core/coclustering_results.py
> +        json_value_typicalities = json_data.get("valueTypicalities")
ok

2023-11-20 14:46 UTC, folmos-at-orange commented on khiops/core/coclustering_results.py
> +        json_value_typicalities = json_data.get("valueTypicalities")
Done

2023-11-20 14:47 UTC, folmos-at-orange commented on khiops/sklearn/estimators.py
> +        isinstance(dataset.target_column_type, pd.CategoricalDtype)
Because we have a sea of deprecation warnings in the latests scikit learn. This type was introduced long ago, so it shouldn't pose any problem. I will put it in a separate commit though.

2023-11-20 14:48 UTC, folmos-at-orange commented on khiops/sklearn/estimators.py
> +            isinstance(self._original_target_type, pd.CategoricalDtype)
See above.

2023-11-20 15:01 UTC, popescu-v commented on khiops/core/coclustering_results.py
> +            first_interval = self.parts[0]
There, in the init of `CoclusteringDimensionPartInterval`, if I understand correctly, we check the length of `json_data["bounds"]`, but not of `json_data["intervals"]`; or, `self.parts` is initialized by iterating on `json_data["intervals"]`... Am I missing something?

2023-11-20 15:10 UTC, popescu-v commented on khiops/sklearn/estimators.py
> +        isinstance(dataset.target_column_type, pd.CategoricalDtype)
Ok

2023-11-22 11:10 UTC, folmos-at-orange commented on khiops/core/coclustering_results.py
> +            first_interval = self.parts[0]
Ahh, ok, I added a check.

2023-11-22 11:14 UTC, folmos-at-orange commented on khiops/core/coclustering_results.py
> +            first_interval = self.parts[0]
Done

2023-11-22 11:49 UTC, folmos-at-orange commented on khiops/core/analysis_results.py
> +            assert len(self.partition) >= 2
Ok. I added a check.
Done

2023-11-22 13:18 UTC, popescu-v commented on khiops/core/coclustering_results.py
> +            first_interval = self.parts[0]
Where is this check?

2023-11-22 13:20 UTC, popescu-v commented on khiops/sklearn/estimators.py
> +        isinstance(dataset.target_column_type, pd.CategoricalDtype)
Where is the separate commit?

2023-11-22 13:21 UTC, popescu-v commented on khiops/sklearn/estimators.py
> +            isinstance(self._original_target_type, pd.CategoricalDtype)
Could be resolved once the separate commit is pushed.

2023-11-22 15:26 UTC, folmos-at-orange commented on khiops/sklearn/estimators.py
> +            isinstance(self._original_target_type, pd.CategoricalDtype)
Done

2023-11-22 16:06 UTC, popescu-v approved these changes
LGTM.

2023-11-22 16:24 UTC, merged