Relax conda enviroment detection
KhiopsML/khiops-python pull request #113
Opened 2023-11-13 10:10 UTC by folmos-at-orange

- We do not check CONDA_DEFAULT_ENV anymore
- We warn if we dectect the user is running in a virtualenv inside a conda env

2023-11-14 10:34 UTC, popescu-v requested changes

2023-11-14 10:34 UTC, popescu-v commented on .github/workflows/pre-commit-checks.yml
> +          python-version: '3.11'
This is because of GitHub bumping the default Python version to 3.12 and the `setup-python` action not supporting it?

2023-11-14 10:34 UTC, popescu-v commented on khiops/core/internals/runner.py
> +            )
I am not sure about this fallback strategy: system-wide might not be what the user expects or want at all IMHO. I would be inclined to just stop the execution and keep issuing this warning as long as the environment is not as targeted. On the other hand, we could *propose* to the user, in the warning, to step out of the Conda environment altogether, have a vanilla Python virtualenv installed and a system-wide installation done (with URL to the relevant documentation on how to do this).

2023-11-14 10:34 UTC, popescu-v commented on khiops/core/internals/runner.py
> +    # - if the `CONDA_PREFIX` environment variable exist
s/exist/exists/

2023-11-14 10:34 UTC, popescu-v commented on khiops/core/internals/runner.py
> +    # - if MODL and MODL_Coclustering executables are in CONDA_PREFIX/bin
s/CONDA_PREFIX/bin/\`$CONDA_PREFIX/bin\`/

2023-11-14 10:34 UTC, popescu-v commented on khiops/core/internals/runner.py
> +    # We are in a conda installation
s/installation/environment/

2023-11-14 10:34 UTC, popescu-v commented on khiops/core/internals/runner.py
> +        # Check that the Khiops binaries exists within CONDA_PREFIX
s/exists/exist/
s/within CONDA_PREFIX/within \`$CONDA_PREFIX/bin\`/

2023-11-14 10:34 UTC, popescu-v commented on khiops/core/internals/runner.py
> +        # We are in a "pure" conda enviroment if not in a virtual env
s/virtual env/virtualenv/
OR
s/virtual env/virtual environment/
(and change throughout, for consistency)

2023-11-14 10:35 UTC, folmos-at-orange commented on .github/workflows/pre-commit-checks.yml
> +          python-version: '3.11'
I don't know exactly. But the `pre-commit` job failed. Let's stick to 3.11 until 3.12 solidifies.

2023-11-14 10:36 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +    # - if the `CONDA_PREFIX` environment variable exist
Ok

2023-11-14 10:36 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +    # - if MODL and MODL_Coclustering executables are in CONDA_PREFIX/bin
Ok

2023-11-14 10:36 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +    # We are in a conda installation
Ok

2023-11-14 10:37 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +        # Check that the Khiops binaries exists within CONDA_PREFIX
Ok

2023-11-14 10:37 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +        # We are in a "pure" conda enviroment if not in a virtual env
Ok

2023-11-16 09:45 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +            )
In the end I think no warning is necessary:
- If the Khiops binaries are in `$CONDA_ENV/bin` then the module will work -> no warning necessary
- If not then it will try a system-wide config which if there is anything wrong will fail -> no warning necessary

2023-11-16 10:03 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +    # - if the `CONDA_PREFIX` environment variable exist
Done

2023-11-16 10:04 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +    # - if MODL and MODL_Coclustering executables are in CONDA_PREFIX/bin
Done.

2023-11-16 10:05 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +        # Check that the Khiops binaries exists within CONDA_PREFIX
Done

2023-11-16 10:05 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +        # We are in a "pure" conda enviroment if not in a virtual env
Not relevant anymore.

2023-11-20 12:34 UTC, popescu-v requested changes
Just a minor change to one commit message (see comment).

2023-11-20 12:34 UTC, popescu-v commented on khiops/core/internals/runner.py
Remove the "We warn ... virtualenv" from the commit message.

2023-11-20 14:33 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
Ok

2023-11-20 14:35 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
Done

2023-11-20 15:04 UTC, popescu-v approved these changes
LGTM.

2023-11-20 15:06 UTC, merged