Add support for bytes fields in dictionary domains
KhiopsML/khiops-python pull request #115
Opened 2023-11-15 18:36 UTC by popescu-v

closes #79

2023-11-16 09:02 UTC, folmos-at-orange commented on khiops/core/dictionary.py
> +            )
Change to `str, bytes` to `"string-like"` to be coherent with the rest of the codebase.

2023-11-16 09:02 UTC, folmos-at-orange commented on khiops/core/dictionary.py
> +            )
And all instances below.

2023-11-17 10:29 UTC, popescu-v commented on khiops/core/dictionary.py
> +    return b"`" + name.replace(b"`", b"``") + b"`"
Ok

2023-11-17 10:29 UTC, popescu-v commented on khiops/core/dictionary.py
> +    return b'"' + value.replace(b'"', b'""') + b'"'
Yes, ok.

2023-11-17 10:29 UTC, popescu-v commented on khiops/core/dictionary.py
> +    version : str or bytes
Well, ok.

2023-11-17 10:29 UTC, popescu-v commented on khiops/core/dictionary.py
> +            )
Ok, right.

2023-11-17 10:33 UTC, popescu-v commented on tests/test_core.py
> +
Comment for me:
- add metadata to the test dictionary created programmatically

2023-11-17 16:52 UTC, popescu-v commented on khiops/core/dictionary.py
> +    return b"`" + name.replace(b"`", b"``") + b"`"
Done.

2023-11-17 16:52 UTC, popescu-v commented on khiops/core/dictionary.py
> +    return b'"' + value.replace(b'"', b'""') + b'"'
Done.

2023-11-17 16:52 UTC, popescu-v commented on khiops/core/dictionary.py
> +    version : str or bytes
Done.

2023-11-17 16:52 UTC, popescu-v commented on khiops/core/dictionary.py
> +            )
Done.

2023-11-17 16:52 UTC, popescu-v commented on tests/test_core.py
> +
Done.

2023-11-21 15:06 UTC, folmos-at-orange requested changes

2023-11-21 15:06 UTC, folmos-at-orange commented on khiops/core/dictionary.py
> +                writer.write(_quote_value(value))
Ok. The example didn't work for another reason.

2023-11-21 15:06 UTC, folmos-at-orange commented on khiops/core/dictionary.py
> +        # `name` is of type bytes
change for an assert

2023-11-21 15:06 UTC, folmos-at-orange commented on khiops/core/dictionary.py
> +        # `value` is of type bytes
change for an assert

2023-11-21 15:06 UTC, folmos-at-orange commented on khiops/core/dictionary.py
Not necessary to add a note. I would put the phrase about validity in the parameter explanation paragraph.

2023-11-21 15:06 UTC, folmos-at-orange commented on khiops/core/dictionary.py
Could you also add that we accept  `str` ?

2023-11-21 15:06 UTC, folmos-at-orange commented on khiops/core/dictionary.py
>              - If the value is not a valid string or if is not bool, int, float.
Leave out bytes.

2023-11-22 10:35 UTC, popescu-v commented on khiops/core/dictionary.py
> +        # `name` is of type bytes
Ok

2023-11-22 10:35 UTC, popescu-v commented on khiops/core/dictionary.py
> +        # `value` is of type bytes
Ok

2023-11-22 10:36 UTC, popescu-v commented on khiops/core/dictionary.py
> Not necessary to add a note. I would put the phrase about validity in the parameter explanation paragraph.

Ok, I would remove the note markdown.

2023-11-22 10:37 UTC, popescu-v commented on khiops/core/dictionary.py
> Could you also add that we accept `str` ?

I'm not sure I see where to add this. It seems to me that this information is already indicated in the doc of `key : str`. What/where else to add?

2023-11-22 10:37 UTC, popescu-v commented on khiops/core/dictionary.py
>              - If the value is not a valid string or if is not bool, int, float.
Ok

2023-11-22 11:08 UTC, popescu-v commented on khiops/core/dictionary.py
> +        # `name` is of type bytes
Done

2023-11-22 11:08 UTC, popescu-v commented on khiops/core/dictionary.py
> +        # `value` is of type bytes
Done

2023-11-22 11:08 UTC, popescu-v commented on khiops/core/dictionary.py
>              - If the value is not a valid string or if is not bool, int, float.
Done

2023-11-22 11:11 UTC, popescu-v commented on khiops/core/dictionary.py
> > Not necessary to add a note. I would put the phrase about validity in the parameter explanation paragraph.
> 
> Ok, I would remove the note markdown, but keep the text.

Done.

2023-11-22 11:12 UTC, popescu-v commented on khiops/core/dictionary.py
> Sorry, I forgot to say "for the `value` parameter"

Ok, done.

2023-11-22 12:50 UTC, folmos-at-orange approved these changes
LGTM

2023-11-22 17:51 UTC, folmos-at-orange requested changes

2023-11-22 17:51 UTC, folmos-at-orange commented on tests/test_core.py
> +        # version when defining domains programmatically
You may specify the version as `bytes` .

2023-11-22 17:51 UTC, folmos-at-orange commented on tests/test_core.py
> +        # version when defining domains programmatically
And the comment may be simplified no ?

2023-11-22 17:53 UTC, popescu-v commented on tests/test_core.py
> +        # version when defining domains programmatically
I can just remove it altogether, now that by default `version` is set to `""`. Is this ok?

2023-11-22 17:58 UTC, popescu-v commented on tests/test_core.py
> +        # version when defining domains programmatically
Done.

2023-11-22 18:00 UTC, folmos-at-orange approved these changes

2023-11-22 18:14 UTC, merged