Integrate the remote access service into the khiopspydev Docker image
KhiopsML/khiops-python pull request #116
Opened 2023-11-23 14:25 UTC by popescu-v

closes #114

2023-11-24 17:11 UTC, folmos-at-orange requested changes

2023-11-24 17:11 UTC, folmos-at-orange commented on tests/test_remote_access.py
> +                kh.get_runner().khiops_temp_dir
This was a bug ?

2023-11-24 17:11 UTC, folmos-at-orange commented on .github/workflows/build-dev-container.yml
>  env:
**General Comment**: 

So the docker tests run locally ?

2023-11-24 17:11 UTC, folmos-at-orange commented on .github/workflows/run-unit-tests.yml
>            # version is  # retrieved
Could you please remove the extra `#`?

2023-11-27 10:15 UTC, popescu-v commented on tests/test_remote_access.py
> +                kh.get_runner().khiops_temp_dir
It's `khiops_temp_dir` that is part of the runner API. `KHIOPS_TMP_DIR` is the name of the relevant environment variable though.

I think the remote runner test code used to work anyway because of duck typing, as the `khiops_tmp_dir` was set in the `setUpClass` methods and used throughout the tests afterwards (by setting the `results_dir` to a path containing `khiops_tmp_dir`).

2023-11-27 10:22 UTC, popescu-v commented on .github/workflows/run-unit-tests.yml
>            # version is  # retrieved
Ok.

2023-11-27 12:25 UTC, folmos-at-orange commented on tests/test_remote_access.py
> +                kh.get_runner().khiops_temp_dir
So it was a bug.

2023-11-27 12:26 UTC, folmos-at-orange commented on .github/workflows/build-dev-container.yml
>  env:
Ok!

2023-11-27 12:40 UTC, folmos-at-orange requested changes

2023-11-27 14:03 UTC, popescu-v commented on tests/test_remote_access.py
> +                kh.get_runner().khiops_temp_dir
Yes, I would say so. Thus, can this thread be closed?

2023-11-27 14:04 UTC, popescu-v commented on .github/workflows/build-dev-container.yml
>  env:
Yes, ok. And the same goes for `setup-buildx-action` and `login-action`; I would bump them all to `@v3`.

2023-11-27 14:09 UTC, popescu-v commented on .github/workflows/build-dev-container.yml
>  env:
Done.

2023-11-27 16:11 UTC, merged