66 save stdout contents to a file in trace mode
KhiopsML/khiops-python pull request #119
Opened 2023-11-24 16:06 UTC by folmos-at-orange

2023-11-27 10:48 UTC, popescu-v requested changes

2023-11-27 10:48 UTC, popescu-v commented on khiops/core/api.py
> +    # Save the runner.run arguments other than the task parameters and options
Is this this the relevant issue associated to this PR https://github.com/KhiopsML/khiops-python/issues/66? If so, why was it unlinked from the PR? Could it be re-linked to the PR?

2023-11-27 10:48 UTC, popescu-v commented on khiops/core/api.py
> +    # Save the runner.run arguments other than the task parameters and options
I would enclose `runner.run` in back-ticks to make it clear that this is an API fragment.

2023-11-27 10:48 UTC, popescu-v commented on khiops/core/internals/runner.py
> +                with open(stdout_file_path, "w") as stdout_file:
Shouldn't we allow to write these files to any location, including a remote one (like an S3 bucket etc)? In that case, shouldn't we be able to handle URIs as well? If so, perhaps the `filesystems` interface might be more appropriate?

2023-11-27 10:48 UTC, popescu-v commented on khiops/core/internals/runner.py
> +            *Advanced* The path of a file to which write the stdout stream of the Khiops
I would slightly rephrase ''The path of a file to which write the stdout stream of the Khiops process." into
"If specified, write the stdout stream of the Khiops process to a file at this path."

2023-11-27 10:48 UTC, popescu-v commented on khiops/core/internals/runner.py
> +            *Advanced* The path of a file to which write the stderr stream of the Khiops
I would also rephrase the first sentence as shown above.

2023-11-27 10:48 UTC, popescu-v commented on khiops/core/internals/runner.py
>              stdout, stderr = khiops_process.communicate()
Shouldn't we add or update some core tests according to this change (perhaps add a test to `KhiopsCoreIOTests`)?

2023-11-27 12:16 UTC, folmos-at-orange commented on khiops/core/api.py
> +    # Save the runner.run arguments other than the task parameters and options
No but there won't be an issue to improve a comment.

2023-11-27 12:18 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +            if stdout_file_path is not None:
No. We do not do this kind of check anywhere in the library. If there aren't permissions then the good "permission denied" exception will be raised by Python.

2023-11-27 12:19 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +                with open(stdout_file_path, "w") as stdout_file:
Yes. I will refactor to use `fs`

2023-11-27 12:23 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +            *Advanced* The path of a file to which write the stdout stream of the Khiops
It is already implied that it is optional. I will change the signature and comment. to match that of `log_file_path`

2023-11-27 12:23 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +            *Advanced* The path of a file to which write the stderr stream of the Khiops
See above.

2023-11-27 12:25 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
>              stdout, stderr = khiops_process.communicate()
I thought about it but it requires heavy mocking, because we need to simulate the `stdout` and `stderr` of the Khiops process.

2023-11-27 14:11 UTC, popescu-v commented on khiops/core/internals/runner.py
> +            *Advanced* The path of a file to which write the stdout stream of the Khiops
Ok.

2023-11-27 14:11 UTC, popescu-v commented on khiops/core/internals/runner.py
> +            *Advanced* The path of a file to which write the stderr stream of the Khiops
Ok.

2023-11-27 14:13 UTC, popescu-v commented on khiops/core/internals/runner.py
>              stdout, stderr = khiops_process.communicate()
Or we could have it as an integration test (w/o mocking) for the time being, with a TODO in the commit message that this should be mocked to make it into a unit test?

2023-11-27 14:27 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
>              stdout, stderr = khiops_process.communicate()
And I'll make an issue for the mocking test.

2023-11-27 15:16 UTC, folmos-at-orange commented on khiops/core/api.py
> +    # Save the runner.run arguments other than the task parameters and options
Done

2023-11-28 10:53 UTC, popescu-v requested changes
Some minor comments.

2023-11-28 10:53 UTC, popescu-v commented on khiops/core/internals/runner.py
> +            that path. Normally Khiops should not write to this stream but MPI,
s/"that path"/"to that path"/

2023-11-28 10:53 UTC, popescu-v commented on khiops/core/internals/runner.py
> +            *Advanced* If specified it writes the stderr stream of the Khiops process
s/"that path"/"to that path"/

2023-11-28 12:27 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +            that path. Normally Khiops should not write to this stream but MPI,
Ok

2023-11-28 12:27 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +            *Advanced* If specified it writes the stderr stream of the Khiops process
Ok

2023-11-28 18:21 UTC, popescu-v requested changes

2023-11-28 18:21 UTC, popescu-v commented on doc/notes.rst
> +    *Advanced* Path of a file to which write the Khiops process stdout stream.  Normally Khiops
I would rephrase the first sentence to "Path of a file the Khiops process writes the stdout stream to".

2023-11-28 18:21 UTC, popescu-v commented on doc/notes.rst
> +    *Advanced* Path of a file to which write the Khiops process stderr stream.  Normally Khiops
I would rephrase the first sentence (cf. the `stdout`-specific sentence above).

2023-11-28 18:21 UTC, popescu-v commented on khiops/core/dictionary.py
> +            Prefer either the the `.read_dictionary_file` function from the core API to
Delete "either the".

2023-11-28 18:21 UTC, popescu-v commented on khiops/core/internals/runner.py
> +            *Advanced* Path of a file to which write the Khiops process stdout stream.
I would rephrase the first sentence (see relevant comment on the associated .rst documentation file).

2023-11-28 18:21 UTC, popescu-v commented on khiops/core/internals/runner.py
> +            *Advanced* Path of a file to which write the Khiops process stderr stream.
I would rephrase the first sentence (see relevant comments above). Namely, "to which write" needs to be rephrased IMHO.

2023-11-28 18:21 UTC, popescu-v commented on tests/test_core.py
> +            kh.set_runner(mock_runner)
Perhaps this snippet can be factored into a helper function, as it seems repetitive?

2023-11-29 08:59 UTC, folmos-at-orange commented on doc/notes.rst
> +    *Advanced* Path of a file to which write the Khiops process stdout stream.  Normally Khiops
What about `Path to a file where the Khiops process writes its stdout stream`

2023-11-29 08:59 UTC, folmos-at-orange commented on khiops/core/dictionary.py
> +            Prefer either the the `.read_dictionary_file` function from the core API to
Ok

2023-11-29 09:00 UTC, folmos-at-orange commented on tests/test_core.py
> +            kh.set_runner(mock_runner)
I don't know. It changes a global state (`set_runner`)

2023-11-29 09:02 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +            *Advanced* Path of a file to which write the Khiops process stderr stream.
See above.

2023-11-29 09:02 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +            *Advanced* Path of a file to which write the Khiops process stdout stream.
See above.

2023-11-29 09:06 UTC, folmos-at-orange commented on doc/notes.rst
> +    *Advanced* Path of a file to which write the Khiops process stderr stream.  Normally Khiops
See above

2023-11-29 09:33 UTC, popescu-v commented on doc/notes.rst
> +    *Advanced* Path of a file to which write the Khiops process stderr stream.  Normally Khiops
Ok.

2023-11-29 09:34 UTC, popescu-v commented on khiops/core/internals/runner.py
> +            *Advanced* Path of a file to which write the Khiops process stdout stream.
Ok.

2023-11-29 09:34 UTC, popescu-v commented on khiops/core/internals/runner.py
> +            *Advanced* Path of a file to which write the Khiops process stderr stream.
Ok.

2023-11-29 09:35 UTC, popescu-v commented on tests/test_core.py
> +            kh.set_runner(mock_runner)
Indeed, it would be a side-effectful function. I don't see any particular issue with this in a testing context, as long as its side effects are documented (docstring + comment).

2023-11-29 16:59 UTC, folmos-at-orange commented on doc/notes.rst
> +    *Advanced* Path of a file to which write the Khiops process stdout stream.  Normally Khiops
Done

2023-11-29 16:59 UTC, folmos-at-orange commented on doc/notes.rst
> +    *Advanced* Path of a file to which write the Khiops process stderr stream.  Normally Khiops
Done

2023-11-29 17:00 UTC, folmos-at-orange commented on khiops/core/dictionary.py
> +            Prefer either the the `.read_dictionary_file` function from the core API to
Done

2023-11-29 17:00 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +            *Advanced* Path of a file to which write the Khiops process stdout stream.
Done

2023-11-29 17:00 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +            *Advanced* Path of a file to which write the Khiops process stderr stream.
Done

2023-12-01 18:18 UTC, folmos-at-orange commented on tests/test_core.py
> +            kh.set_runner(mock_runner)
Done

2023-12-01 18:32 UTC, popescu-v approved these changes

2023-12-04 07:46 UTC, merged