Unify environment initialization between conda and system wide installations
KhiopsML/khiops-python pull request #124
Opened 2023-12-01 18:08 UTC by popescu-v

closes #123

2023-12-04 12:40 UTC, popescu-v commented on khiops/core/internals/runner.py
> +    def _initialize_execution_environment(self):
Ok

2023-12-04 12:42 UTC, popescu-v commented on tests/test_core.py
> +
Ok

2023-12-04 18:59 UTC, popescu-v commented on khiops/core/internals/runner.py
> +    def _initialize_execution_environment(self):
Done. [The refactoring of `.is_initialized` will be handled in another commit.]

2023-12-04 19:00 UTC, popescu-v commented on khiops/core/internals/runner.py
> +
Done.

2023-12-04 19:00 UTC, popescu-v commented on khiops/core/internals/runner.py
> +            custom_mpi_lib_path = os.environ["KHIOPS_MPI_LIB"]
Done.

2023-12-04 19:00 UTC, popescu-v commented on tests/test_core.py
> +        # Test that, if set, KHIOPS_* environment variables are taken into account
Done.

2023-12-04 19:00 UTC, popescu-v commented on tests/test_core.py
> +
Done.

2023-12-06 15:23 UTC, folmos-at-orange requested changes

2023-12-08 14:21 UTC, popescu-v commented on khiops/core/internals/runner.py
> +            os.environ["KHIOPS_PROC_NUMBER"] = str(self.max_cores + 1)
Done.

2023-12-08 14:26 UTC, popescu-v commented on tests/test_core.py
> +        )
Done.

2023-12-08 14:26 UTC, popescu-v commented on tests/test_core.py
> +        """
Done.

2023-12-08 14:27 UTC, popescu-v commented on tests/test_core.py
> +
Done. Removed the comment and refactored the docstring.

2023-12-08 14:28 UTC, popescu-v commented on tests/test_core.py
> +
Yes, IMHO it has been taken into account.

2023-12-08 14:29 UTC, popescu-v commented on tests/test_khiops_integrations.py
> +
Rather than long, it is an integration test where the real Khiops is launched, whence the "integration" in test class name. Indeed, we want to see that Khiops binaries can be launched from the runner.

2023-12-08 14:30 UTC, popescu-v commented on tests/test_khiops_integrations.py
> +
Done.

2023-12-08 15:16 UTC, popescu-v commented on tests/test_khiops_integrations.py
> +                )
Done.

2023-12-08 15:16 UTC, popescu-v commented on tests/test_khiops_integrations.py
> +            # directory
Done.

2023-12-08 15:16 UTC, popescu-v commented on tests/test_remote_access.py
Hmm, ok.

2023-12-08 15:24 UTC, popescu-v commented on khiops/core/internals/runner.py
> +        # Initialize Khiops binary directory
Ok, I will rename it, as discussed.

2023-12-08 17:44 UTC, popescu-v commented on tests/test_helper.py
Done.

2023-12-08 17:44 UTC, popescu-v commented on khiops/core/internals/runner.py
> +        # Initialize Khiops binary directory
Done.

2023-12-11 09:51 UTC, folmos-at-orange requested changes
Small stuff, but I think there is bug in the tests.

2023-12-11 09:51 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +
`initialize_khiops_environment` should go immediatly after `__init__`

2023-12-11 09:51 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
This is a method of the khiops runner, just call it `_initialize`. Also, move below `__init__`.

2023-12-11 09:51 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +            # Non-Conda environment
This comment goes above the `else`

2023-12-11 09:51 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +        # Set the Khiops process number according to the relevant env var
relevant env var -> `KHIOPS_PROC_NUMBER` env var

2023-12-11 09:51 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +        mpiexec_path = os.environ.get("KHIOPS_MPIEXEC_PATH") or shutil.which("mpiexec")
The Conda part of this comment is not relevant anymore (before it was a method called only `if CONDA`). Just rephrase to keep the explanation of the mechanics.

2023-12-11 09:51 UTC, folmos-at-orange commented on tests/test_core.py
> +            os.environ[variable] = f"my{variable.lower()}"
Add paragraph comment : "Save the current environment" (or similar)

2023-12-11 09:51 UTC, folmos-at-orange commented on tests/test_core.py
> +
~~This is unnecessary.~~

I think this is in fact an error, shouldn't the custom runner be used in the test ?

2023-12-11 09:51 UTC, folmos-at-orange commented on tests/test_core.py
> +
Make it one line.

2023-12-11 09:51 UTC, folmos-at-orange commented on tests/test_core.py
> +        # set `KHIOPS_MPIEXEC_PATH`
Say also that you save the current environment.

2023-12-11 09:51 UTC, folmos-at-orange commented on tests/test_core.py
> +        """
Make it one line.

2023-12-11 09:51 UTC, folmos-at-orange commented on tests/test_core.py
> +        # command arguments of `mpiexec`
This is redundant. The additional information should go in the docstring body.

2023-12-11 09:51 UTC, folmos-at-orange commented on tests/test_core.py
> +        # set `KHIOPS_MPI_COMMAND_ARGS`
Say that you also save the current environment

2023-12-11 09:51 UTC, folmos-at-orange commented on tests/test_remote_access.py
Calling it as a composition with `self` the method is perfectly fine.

2023-12-11 11:04 UTC, popescu-v commented on tests/test_remote_access.py
Ok, I will go for this implementation.

2023-12-11 11:06 UTC, popescu-v commented on khiops/core/internals/runner.py
> +
Ok, I will put it after the parent's `__init__` call.

2023-12-11 11:08 UTC, popescu-v commented on khiops/core/internals/runner.py
> +            # Non-Conda environment
Ok.

2023-12-11 11:10 UTC, popescu-v commented on khiops/core/internals/runner.py
> +        # Set the Khiops process number according to the relevant env var
Ok.

2023-12-11 11:50 UTC, popescu-v commented on khiops/core/internals/runner.py
> +        mpiexec_path = os.environ.get("KHIOPS_MPIEXEC_PATH") or shutil.which("mpiexec")
Right. I have simplified it.

2023-12-11 11:51 UTC, popescu-v commented on tests/test_core.py
> +            os.environ[variable] = f"my{variable.lower()}"
Ok.

2023-12-11 11:54 UTC, popescu-v commented on tests/test_core.py
> +
I am not sure to see why this is an error, as we do not test features provided by the `MockedRunnerContext` here, right?

2023-12-11 12:42 UTC, popescu-v commented on tests/test_remote_access.py
Done.

2023-12-11 12:42 UTC, popescu-v commented on khiops/core/internals/runner.py
> +
Done.

2023-12-11 12:42 UTC, popescu-v commented on khiops/core/internals/runner.py
> +            # Non-Conda environment
Done.

2023-12-11 12:43 UTC, popescu-v commented on khiops/core/internals/runner.py
> +        # Set the Khiops process number according to the relevant env var
Done.

2023-12-11 12:43 UTC, popescu-v commented on tests/test_core.py
> +            os.environ[variable] = f"my{variable.lower()}"
Done.

2023-12-11 13:31 UTC, popescu-v commented on tests/test_core.py
> +
I have used the `MockedRunnerContext` throughout the Core tests though.

2023-12-11 13:45 UTC, popescu-v commented on tests/test_core.py
> +
Right, ok.

2023-12-11 13:47 UTC, popescu-v commented on tests/test_core.py
> +        """
Done

2023-12-11 13:47 UTC, popescu-v commented on tests/test_core.py
> +        # command arguments of `mpiexec`
Ok, done.

2023-12-11 13:47 UTC, popescu-v commented on tests/test_core.py
> +        # set `KHIOPS_MPI_COMMAND_ARGS`
Yes, done.

2023-12-11 17:44 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +
Just to be a bit more coherent `KHIOPS_MPI_COMMAND_ARGS` -> `KHIOPS_MPIEXEC_ARGS`

2023-12-11 17:46 UTC, folmos-at-orange commented on tests/test_core.py
> +        # contract)
Ok, but the title must fix the line. Otherwise put any extra information in the body.

To be clear
```
def fun():
"""Title (must to pass the line
<emtpy line>
Body
"""

2023-12-11 19:22 UTC, popescu-v commented on tests/test_core.py
> +        # contract)
Yep, ok.

2023-12-11 19:25 UTC, folmos-at-orange commented on tests/test_khiops_integrations.py
> +
It is not long, so it should be not skipped.

2023-12-11 19:27 UTC, folmos-at-orange commented on tests/test_khiops_integrations.py
> +
What I mean by merge is that there is only one comment for both instructions.

```python
# Create and initialize its bin dir
runner = KhiopsLocalRunner()
runner._initialize_default_khiops_bin_dir()
```

2023-12-11 19:29 UTC, folmos-at-orange commented on tests/test_khiops_integrations.py
> +                )
Just one question why `copy2` ? why not `copy` ?

2023-12-11 19:32 UTC, folmos-at-orange commented on tests/test_remote_access.py
Could you also generalize to other long tests ? (In another commit)

2023-12-11 19:39 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +
Sorry I meant the definition, to have a more local code.

2023-12-11 19:43 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
Sorry, I didn't understand the code. Now i see that this code finalizes the initialization. I'm tempted to call it `_finalize_initialization` but I do not know how to rename `initialize_khiops_environment` ... maybe `_start_environment_initialization` and `_finish_environment_initialization` ?

2023-12-11 19:43 UTC, popescu-v commented on tests/test_khiops_integrations.py
> +                )
Because I wanted to preserve all file metadata. But this does indeed not seem necessary in this case and `copy` is fine, because it preserves the permissions, which is sufficient for this test. Hence, I will replace with `copy`.

2023-12-11 19:46 UTC, popescu-v commented on tests/test_remote_access.py
Normally, this helper is already used for all long tests. Where should this be further generalized?

2023-12-11 19:47 UTC, popescu-v commented on khiops/core/internals/runner.py
> +
Ok, so this has been done, whence this thread could be closed IMHO.

2023-12-11 19:48 UTC, popescu-v commented on khiops/core/internals/runner.py
Yeah, `_start_environment_initialization` / `_finish_environment_initialization`, why not? They seem to be clearly conveying the intent. Hence, +1 for renaming them thusly.

2023-12-11 20:49 UTC, folmos-at-orange commented on tests/test_core.py
> +
Ok

2023-12-11 21:02 UTC, folmos-at-orange requested changes
Almost LGTM

2023-12-11 21:02 UTC, folmos-at-orange commented on tests/test_remote_access.py
I still see some "UNITTEST_ONLY_SHORT_TESTS" in the code
```bash
> rg UNITTEST
tests/test_samples.py
19:        if "UNITTEST_ONLY_SHORT_TESTS" in os.environ:
20:            if os.environ["UNITTEST_ONLY_SHORT_TESTS"].lower() == "true":

tests/test_helper.py
266:        if "UNITTEST_ONLY_SHORT_TESTS" in os.environ:
267:            if os.environ["UNITTEST_ONLY_SHORT_TESTS"].lower() == "true":

tests/test_sklearn_output_types.py
51:        if "UNITTEST_ONLY_SHORT_TESTS" in os.environ:
52:            if os.environ["UNITTEST_ONLY_SHORT_TESTS"].lower() == "true":
```

2023-12-11 21:03 UTC, folmos-at-orange commented on tests/test_khiops_integrations.py
> +                )
Ok!

2023-12-11 21:17 UTC, folmos-at-orange commented on doc/notes.rst
> +
Also a  link to the list at the beginning of `khiops/core/api.py`

2023-12-12 09:31 UTC, popescu-v commented on tests/test_khiops_integrations.py
> +
Ok, I will not skip it anymore.

2023-12-12 09:31 UTC, popescu-v commented on tests/test_khiops_integrations.py
> +
Ok, done.

2023-12-12 10:16 UTC, popescu-v commented on khiops/core/internals/runner.py
I finally opted for `_start_khiops_environment_initialization` / `_finish_khiops_environment_initialization`.

2023-12-12 13:08 UTC, popescu-v commented on tests/test_khiops_integrations.py
> +
Done.

2023-12-12 13:08 UTC, popescu-v commented on tests/test_khiops_integrations.py
> +                )
Done.

2023-12-12 13:09 UTC, popescu-v commented on tests/test_remote_access.py
Ok, I had missed those. Generalization done now, throughout the tests.

2023-12-12 13:10 UTC, popescu-v commented on doc/notes.rst
> +- `KHIOPS_HOME`: path to the Khiops installation directory, on Windows systems
Done.

2023-12-12 13:10 UTC, popescu-v commented on doc/notes.rst
> +- `KHIOPS_MEMORY_LIMIT`: memory limit of the Khiops executables; ignored if set above the system
Done.

2023-12-12 13:10 UTC, popescu-v commented on doc/notes.rst
> +- `KHIOPS_MPI_LIB`: path to the MPI library
Done and done.

2023-12-12 13:10 UTC, popescu-v commented on doc/notes.rst
> +
Done.

2023-12-12 13:11 UTC, popescu-v commented on doc/notes.rst
> +only by used in particular envionments. For the majority of usages, default behavior is implemented
Yes, indeed. I have rephrased the text accordingly.

2023-12-12 13:11 UTC, popescu-v commented on khiops/core/internals/runner.py
> +    - `KHIOPS_TMP_DIR`: path to Khiops' temporary directory
Done.

2023-12-12 16:27 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
Ok !

2023-12-12 16:33 UTC, folmos-at-orange commented on doc/notes.rst
> +only by used in particular envionments. For the majority of usages, default behavior is implemented
Only the first 3 ones are part of the API

2023-12-12 16:35 UTC, folmos-at-orange approved these changes
LGTM but before merging fix the last two of the doc bugs.

2023-12-12 16:36 UTC, popescu-v commented on doc/notes.rst
> +only by used in particular envionments. For the majority of usages, default behavior is implemented
Ok. I have rephrased this; it is pushed now.

2023-12-15 13:59 UTC, popescu-v commented on doc/notes.rst
> +only by used in particular envionments. For the majority of usages, default behavior is implemented
OK, I have fixed this.

2023-12-15 14:08 UTC, popescu-v commented
> LGTM but before merging fix the last two of the doc bugs.
> 
> **And squashing some commits if possible**

The doc bugs have been fixed. Some commits have been squashed.

2023-12-15 14:52 UTC, merged