Full conda pkg tests
KhiopsML/khiops-python pull request #126
Opened 2023-12-12 15:41 UTC by folmos-at-orange

Solve the mpich version problem in Linux

2024-01-12 18:56 UTC, popescu-v requested changes
Technically, almost LGTM (see the three comments).
However, I think it would be best to run the full Khiops test suite, including the tests for the MPI-related bug https://github.com/KhiopsML/khiops/issues/104, on all supported platforms (Mac x86, Mac ARM, Linux x86), before approving this PR.

2024-01-12 18:56 UTC, popescu-v commented on .github/workflows/build-conda-package.yml
> +        os: [ubuntu-20.04, windows-latest, macos-11]
Are we sure that a Khiops compiled on the latest Windows is suppoed to work on an older Windows (like, Windows 2019)?

2024-01-12 18:56 UTC, popescu-v commented on .github/workflows/build-conda-package.yml
> +      # In Linux/macOS we need the conda-forge channel to install mpi 3.4.3
This comment is not fully accurate, as pinned MPI versions are different between macOS and Linux. I would just say:
"...to install specific pinned mpi versions".

2024-01-12 18:56 UTC, popescu-v commented on packaging/conda/meta.yaml
> +    - KHIOPS_REVISION
Ok, I would add a comment somewhere that now we need to make sure `KHIOPS_REVISION` is set prior to attempting a `conda build`. This is of some importance for contributors IMHO.

2024-01-15 10:38 UTC, folmos-at-orange commented on packaging/conda/meta.yaml
> +    - KHIOPS_REVISION
I think we should have a conda build README. I'll do that later. For the moment conda-build warns you if you have not set this variable.

2024-01-25 14:52 UTC, folmos-at-orange commented on .github/workflows/build-conda-package.yml
> +        os: [ubuntu-20.04, windows-latest, macos-11]
We'll see when executing the tests. I suspect it doesn't matter since a conda environment is supposed to be isolated.

2024-01-25 14:53 UTC, folmos-at-orange commented on .github/workflows/build-conda-package.yml
> +      # In Linux/macOS we need the conda-forge channel to install mpi 3.4.3
Ok

2024-01-25 15:12 UTC, popescu-v commented on packaging/conda/meta.yaml
> +    - KHIOPS_REVISION
Yes, right. The readme should perhaps be in a `doc/CONTRIBUTE.md` or alike?

2024-01-25 15:14 UTC, popescu-v commented on .github/workflows/build-conda-package.yml
> +        os: [ubuntu-20.04, windows-latest, macos-11]
Yes, IMHO the only thing we would need to make sure of is that the runtime dependencies can be satisfied correctly (i.e., in informal terms, that a recent-enough Conda can be installed on the older Windows).

2024-01-25 15:18 UTC, popescu-v commented on packaging/conda/meta.yaml
> +    - KHIOPS_REVISION
Meanwhile, a small comment there could be useful IMHO.

2024-02-02 13:43 UTC, folmos-at-orange commented on .github/workflows/build-conda-package.yml
> +      # In Linux/macOS we need the conda-forge channel to install mpi 3.4.3
Done

2024-02-02 14:06 UTC, folmos-at-orange commented on packaging/conda/meta.yaml
> +    - KHIOPS_REVISION
I added a README to the conda packaging.

2024-02-02 14:14 UTC, folmos-at-orange commented
> Technically, almost LGTM (see the three comments). However, I think it would be best to run the full Khiops test suite, including the tests for the MPI-related bug [KhiopsML/khiops#104](https://github.com/KhiopsML/khiops/issues/104), on all supported platforms (Mac x86, Mac ARM, Linux x86), before approving this PR.

The tests are Ok for the pinned versions. We can merge this.

2024-02-07 15:00 UTC, popescu-v commented on .github/workflows/build-conda-package.yml
> +        run: conda install conda-build=3.27.0 conda-verify
This is the last version that works correctly?

2024-02-07 15:03 UTC, popescu-v commented on .github/workflows/build-conda-package.yml
> +    needs: [build-packages, test-packages]
`test-packages` already needs `build-packages`; hence, insn't the needs `build-packages` here redundant?

2024-02-07 15:05 UTC, popescu-v commented on packaging/conda/build.sh
> +git clone https://github.com/khiopsml/khiops.git khiops-core
This change is so that we can build on any Khiops version / tag, right?

2024-02-07 15:06 UTC, folmos-at-orange commented on .github/workflows/build-conda-package.yml
> +        run: conda install conda-build=3.27.0 conda-verify
No. But it is a version that works.

2024-02-07 15:07 UTC, popescu-v commented on packaging/conda/meta.yaml
> +    - mpich 3.4.3        # [osx]
Do we need this same pinning for both OSXes: Intel and ARM? Or rather, the Intel MacOS could use the same pinning as Linux?

2024-02-07 15:07 UTC, folmos-at-orange commented on .github/workflows/build-conda-package.yml
> +    needs: [build-packages, test-packages]
It `needs` `build-packages` because it uses its outputs.

2024-02-07 15:07 UTC, folmos-at-orange commented on packaging/conda/README.md
> +You'll need `conda-build` installed in your system. The environment variable `KHIOPS_REVISION` is
Ok

2024-02-07 15:08 UTC, popescu-v commented on .github/workflows/build-conda-package.yml
> +        run: conda install conda-build=3.27.0 conda-verify
Ok.

2024-02-07 15:08 UTC, folmos-at-orange commented on packaging/conda/README.md
> +You'll need `conda-build` installed in your system. The environment variable `KHIOPS_REVISION` is
Rewritten differently but with the same spirit. Done.

2024-02-07 15:08 UTC, folmos-at-orange commented on packaging/conda/build.sh
> +git clone https://github.com/khiopsml/khiops.git khiops-core
Yes, just so versioneer works properly.

2024-02-07 15:08 UTC, popescu-v commented on .github/workflows/build-conda-package.yml
> +    needs: [build-packages, test-packages]
I see, this is because the `needs` relation is not transitive in GitHub workflows?

2024-02-07 15:10 UTC, popescu-v commented on packaging/conda/build.sh
> +git clone https://github.com/khiopsml/khiops.git khiops-core
Yes, ok.

2024-02-07 15:14 UTC, folmos-at-orange commented on packaging/conda/meta.yaml
> +    - mpich 3.4.3        # [osx]
I don't know, but it works and better to have less combinatorics at the moment. Ideally in the future we won't need selectors.

2024-02-07 15:15 UTC, popescu-v commented on .github/workflows/build-conda-package.yml
> +    needs: [build-packages, test-packages]
Ok, I see. Then, I would add a small comment in this respect.

2024-02-07 15:15 UTC, popescu-v commented on packaging/conda/meta.yaml
> +    - mpich 3.4.3        # [osx]
Ok, I see your point.

2024-02-07 15:17 UTC, folmos-at-orange commented on .github/workflows/build-conda-package.yml
> +    needs: [build-packages, test-packages]
Ok

2024-02-07 15:18 UTC, folmos-at-orange commented on .github/workflows/build-conda-package.yml
> +    needs: [build-packages, test-packages]
Done

2024-02-07 15:51 UTC, popescu-v commented on packaging/conda/\
Remove this file?

2024-02-07 16:52 UTC, popescu-v approved these changes
LGTM

2024-02-07 17:38 UTC, merged