Check existence of docker shared_dir only for local ones
KhiopsML/khiops-python pull request #130
Opened 2024-01-08 15:36 UTC by folmos-at-orange

2024-01-10 13:39 UTC, popescu-v requested changes
Almost LGTM, with two caveats (see comments).

2024-01-10 13:39 UTC, popescu-v commented on khiops/extras/docker.py
> +        ):
I would separate the two `if` condition parts and:
- would raise `ValueError` if `self.shared_dir is None`
- would raise `RuntimeError` if `self.shared_dir` is a non-existing local directory

2024-01-10 13:39 UTC, popescu-v commented on khiops/extras/docker.py
> +        ):
I would also add a test that a `RuntimeError` (see previous comment) is only raised for a non-existing local `shared_dir`.

2024-01-10 17:17 UTC, folmos-at-orange commented on khiops/extras/docker.py
> +        ):
Ok

2024-01-11 16:56 UTC, folmos-at-orange commented on khiops/extras/docker.py
> +        ):
Done

2024-01-11 16:56 UTC, folmos-at-orange commented on khiops/extras/docker.py
> +        ):
Done

2024-01-12 10:14 UTC, popescu-v commented on khiops/extras/docker.py
> +        ):
Ok for these checks.

2024-01-12 10:16 UTC, popescu-v commented on khiops/extras/docker.py
> +        ):
Actually, what I had in mind was an automatic test (in test_remote_access) that a ~`RuntimeError`~ `KhiopsEnvironmentError` is only raised for a non-existing local `shared_dir` (but not for a remote URI).

2024-01-12 10:17 UTC, popescu-v requested changes
There is only one comment left to address IMHO.

2024-01-12 12:22 UTC, folmos-at-orange commented on khiops/extras/docker.py
> +        ):
That is what i did.

2024-01-22 10:42 UTC, folmos-at-orange commented on khiops/extras/docker.py
> +        ):
Done

2024-01-22 17:51 UTC, popescu-v requested changes
Almost LGTM, barring 4 remaining comments.

2024-01-22 17:51 UTC, popescu-v commented on tests/test_khiops_integrations.py
> +        """Test that shared dir exists when it is a local path"""
I would rephrase to something like: "Test that KhiopsEnvironmentError is raised when shared_dir is a local path and does not exist".

2024-01-22 17:51 UTC, popescu-v commented on khiops/extras/docker.py
>          response = None
This is not needed anymore IMHO.

2024-01-22 17:51 UTC, popescu-v commented on khiops/extras/docker.py
> +        Path for the shared directory dire. May be an URL.
I would 's/May be an URL/Can be either a local path or an URL/'.

2024-01-22 17:51 UTC, popescu-v commented on khiops/extras/docker.py
> +        Path for the shared directory dire. May be an URL.
s/shared directory dire./shared directory./

2024-01-23 12:55 UTC, folmos-at-orange commented on tests/test_khiops_integrations.py
> +        """Test that shared dir exists when it is a local path"""
Done

2024-01-23 12:56 UTC, folmos-at-orange commented on khiops/extras/docker.py
>          response = None
Ok and done

2024-01-23 12:58 UTC, folmos-at-orange commented on khiops/extras/docker.py
> +        Path for the shared directory dire. May be an URL.
I put "May be an URL/URI" to keep it consistent with the codebase.

2024-01-23 13:32 UTC, popescu-v approved these changes
LGTM

2024-01-23 14:06 UTC, merged