Support 1-1 relations and update unit tests
KhiopsML/khiops-python pull request #131
Opened 2024-01-11 16:01 UTC by nairbenrekia

2024-01-11 17:21 UTC, folmos-at-orange requested changes
Almost finished.

2024-01-11 18:02 UTC, nairbenrekia commented on doc/samples/samples_sklearn.rst
> +            n_trees=0, output_dir=path.join(kh.get_samples_dir(), "Accidents_dico.txt")
It is not. I forgot to drop it.

2024-01-11 18:03 UTC, nairbenrekia commented on khiops/sklearn/tables.py
> +                if len(relation) < 2 or len(relation) > 3:
Ok.

2024-01-11 18:04 UTC, nairbenrekia commented on khiops/sklearn/tables.py
> +                                "1-1 relation flag", is_one_to_one_relation, bool
Good idea. Ok.

2024-01-11 18:06 UTC, nairbenrekia commented on khiops/sklearn/tables.py
>                          f"Tables in relation '{relation}' are the same. "
Ok.

2024-01-22 16:05 UTC, popescu-v requested changes
Technically, the code LGTM. However, there are some three comments left to tackle IMHO.

2024-02-06 13:57 UTC, nairbenrekia commented on khiops/sklearn/tables.py
> +                parent_table, child_table = relation[:2]
Ok.

2024-02-07 17:46 UTC, popescu-v commented on tests/test_dataset_class.py
> +            "VAR_4": np.round(np.random.rand(10).tolist(), 2),
Ok, then I would add a comment accordingly, just before the definitions of these tables.

2024-02-07 17:47 UTC, popescu-v commented on tests/test_dataset_errors.py
> +            "VAR_4": np.round(np.random.rand(10).tolist(), 2),
Add relevant comment before the definition.

2024-02-07 18:01 UTC, folmos-at-orange commented on doc/samples/samples_sklearn.rst
> +            n_trees=0, output_dir=path.join(kh.get_samples_dir(), "Accidents_dico.txt")
It is done

2024-02-12 15:53 UTC, popescu-v commented on doc/multi_table_primer.rst
> +  either ``1:n`` or ``1:1`` (entity). For example, If the tuple ``(table1, table2, True)`` is contained in this
I would add "by default": "either ``1:n`` (by default), or ``1:1`` (entity)".

2024-02-12 15:54 UTC, popescu-v commented on doc/multi_table_primer.rst
> +    support External data tables are not currently supported.
Cut "are not currently supported", as this is stated just before ("[They] currently do not support ...).

2024-02-12 15:54 UTC, popescu-v commented on doc/multi_table_primer.rst
> +    This feature will be available in upcoming releases. If you need to use it, you can use `khiops.core`
"..., you can use *the* `khiops.core` module" (add "the").

2024-02-12 15:56 UTC, popescu-v commented on khiops/sklearn/tables.py
> +            self.relations = X["relations"]
How are we sure that `"relations" in X` is `True` here?

2024-02-12 15:58 UTC, popescu-v commented on khiops/sklearn/tables.py
> +            if relations.count(relation) != 1:
I would have just written "> 1" to make it clear right away what the problem is.

2024-02-12 16:01 UTC, popescu-v commented on tests/test_dataset_errors.py
>                          ("D", "E"),
We could insert some `False` third argument, to check everything runs OK in this case (as the API now supports it).

2024-02-12 16:02 UTC, popescu-v commented on tests/test_dataset_errors.py
>                          ("D", "E"),
Insert some `False` third argument (see above)?

2024-02-12 16:05 UTC, popescu-v requested changes
Almost LGTM. Just a few - relatively - minor points remain (see comments).

2024-02-12 17:15 UTC, nairbenrekia commented on doc/multi_table_primer.rst
> +    support External data tables are not currently supported.
Yes. I forgot to cut it.

2024-02-12 17:30 UTC, nairbenrekia commented on khiops/sklearn/tables.py
> +            self.relations = X["relations"]
in _check_input_mapping() that is called before this instruction, we create "relations" on the fly if the MT schema is "star"; otherwise (if it is a "snwoflake schema) we complete the tuples in the user-provided "relations" with the entiy flag.

2024-02-12 17:30 UTC, nairbenrekia commented on khiops/sklearn/tables.py
> +            if relations.count(relation) != 1:
Ok.

2024-02-12 17:31 UTC, nairbenrekia commented on tests/test_dataset_errors.py
>                          ("D", "E"),
Yes Ok.

2024-02-12 18:03 UTC, popescu-v commented on khiops/sklearn/tables.py
> +            self.relations = X["relations"]
I see.
In a `_check_...` method there should only be checks IMHO, that is, raise `TypeError` or `ValueError`. Side-effectful instructions should be factored in a different place. Concretely, `relations` should be created elsewhere IMHO, if `_check_input_mapping` doesn't raise any exception. For instance, directly in `_init_tables_from_mapping`, after `self._check_input_mapping`.

2024-03-05 12:24 UTC, popescu-v commented on khiops/sklearn/tables.py
> +            parent_table, child_table, is_one_to_one_relation = relation
I think we should check the Boolean in two times:
1. check that `len(relations) == 3`;
2. if so, then do type checking on the Boolean (`relation[-1]`)

2024-03-05 12:28 UTC, popescu-v requested changes
Almost LGTM. I would only separate more the checks on user input `X` (in `_check_relations`) from the programmatic modifications (which I would not check at the same place).

2024-03-05 12:34 UTC, popescu-v commented on khiops/sklearn/tables.py
> +            X["relations"] = relations
Why do we need to change `X`? Isn't `self.relations` enough? Something like:
```python
# At the beginning
self._check_relations(X)
# ...
# Then, at the end:
self.relations = relations
```?

2024-03-13 15:13 UTC, popescu-v commented on khiops/sklearn/tables.py
> +            self.relations = X["relations"]
Closing as this has been done.

2024-03-13 15:14 UTC, popescu-v commented on khiops/sklearn/tables.py
> +                parent_table, child_table, _ = relation
Closing as this has been superseded by the latest refactoring.

2024-03-13 15:18 UTC, popescu-v approved these changes
LGTM.

2024-03-13 16:04 UTC, folmos-at-orange approved these changes
LGTM

Squash to one commit before merging.

2024-03-13 16:36 UTC, merged