127 mpiexec is not found on rocky linux
KhiopsML/khiops-python pull request #132
Opened 2024-01-16 17:24 UTC by popescu-v

Add support for environment modules-based mpich installations (as on Rocky Linux).

closes #127.

2024-01-18 16:30 UTC, folmos-at-orange requested changes

2024-01-19 18:41 UTC, popescu-v commented on khiops/core/internals/runner.py
> +            # https://modules.readthedocs.io/en/latest/module.html,
No, not that I am aware of.

2024-01-19 18:42 UTC, popescu-v commented on tests/test_core.py
> +        self.mock_context.__exit__(a_type, value, traceback)
Ok.

2024-01-19 19:09 UTC, popescu-v commented on tests/test_core.py
> +        self.mock_context.__exit__(a_type, value, traceback)
Done.

2024-01-22 08:39 UTC, folmos-at-orange requested changes

2024-01-22 08:39 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +            # https://modules.readthedocs.io/en/latest/module.html,
What about https://modules.readthedocs.io/en/latest/module.html#examples-of-initialization

2024-01-22 08:39 UTC, folmos-at-orange commented on tests/test_khiops_integrations.py
> +            # yum list installed
I'd change the comment to say what are you doing (instead of the commands)

2024-01-22 08:39 UTC, folmos-at-orange commented on tests/test_khiops_integrations.py
> +            # dpkg -l
I'd change the comment to say what are you doing (instead of the commands)

2024-01-22 08:39 UTC, folmos-at-orange commented on tests/test_khiops_integrations.py
> +            )
I'd put one assert for each statement. It is easier to see what failed afterwards.

2024-01-22 08:39 UTC, folmos-at-orange commented on tests/test_khiops_integrations.py
> +            # yum list installed
And  move the comments before the `elif`

2024-01-22 08:39 UTC, folmos-at-orange commented on tests/test_khiops_integrations.py
> +            # dpkg -l
And move the comment before the `if`

2024-01-22 08:39 UTC, folmos-at-orange commented on doc/samples/samples_sklearn.rst
The old code provokes a failure ?

2024-01-22 08:39 UTC, folmos-at-orange commented on .github/workflows/run-unit-tests.yml
> +        run: python -m unittest -v tests.test_khiops_integrations.KhiopsRunnerEnvironmentTests.test_runner_has_mpiexec_on_linux
And also unload the module before testing.

2024-01-22 09:47 UTC, popescu-v commented on khiops/core/internals/runner.py
> +            # https://modules.readthedocs.io/en/latest/module.html,
Well, OK, but it's just a bookmark on the same page that I had given in the comment. And it incurs the risk of yielding too long a line for the linters.

2024-01-22 09:48 UTC, popescu-v commented on .github/workflows/build-pip-package.yml
> +        shell: bash
Actually, without this, the module intialization does not work, because, contrary to the runners, for containers the shell is `sh` by default; see https://github.com/actions/runner/issues/1533.

2024-01-22 09:48 UTC, popescu-v commented on .github/workflows/build-pip-package.yml
> +          kh-status | grep "MPI command" | grep -wq mpiexec
Ok, fair enough.

2024-01-22 09:49 UTC, popescu-v commented on .github/workflows/build-pip-package.yml
> +          kh-status | grep "MPI command" | grep -wq mpiexec
Ok, right.

2024-01-22 09:49 UTC, popescu-v commented on .github/workflows/run-unit-tests.yml
> +          python3 setup.py egg_info
I could try to.

2024-01-22 09:49 UTC, popescu-v commented on .github/workflows/run-unit-tests.yml
> +        run: python -m unittest -v tests.test_khiops_integrations.KhiopsRunnerEnvironmentTests.test_runner_has_mpiexec_on_linux
Ok and ok.

2024-01-22 09:49 UTC, popescu-v commented on tests/test_khiops_integrations.py
> +            # yum list installed
Ok and ok.

2024-01-22 09:50 UTC, popescu-v commented on tests/test_khiops_integrations.py
> +            # dpkg -l
Ok and ok.

2024-01-22 09:50 UTC, popescu-v commented on tests/test_khiops_integrations.py
> +            )
Ok.

2024-01-22 09:51 UTC, popescu-v commented on doc/samples/samples_sklearn.rst
Yes, indeed, as a more recent sklearn is installed and the deprecated code is not supported anymore. See https://github.com/KhiopsML/khiops-python/actions/runs/7587846352/job/20669075709#step:10:1183.

2024-01-22 09:52 UTC, popescu-v commented on tests/test_core.py
> +        self.mock_context.__exit__(a_type, value, traceback)
Could this be closed?

2024-01-22 10:44 UTC, folmos-at-orange commented on doc/samples/samples_sklearn.rst
Does the fix work in old sklearn ?

2024-01-22 10:45 UTC, folmos-at-orange commented on .github/workflows/build-pip-package.yml
> +        shell: bash
Ok then.

2024-01-22 10:47 UTC, folmos-at-orange commented on .github/workflows/build-pip-package.yml
> +          kh-status | grep "MPI command" | grep -wq mpiexec
Would an `if [[ MODULES` or whatever solve this in the same step?

2024-01-22 10:53 UTC, popescu-v commented on doc/samples/samples_sklearn.rst
`sparse` was deprecated since sklearn 1.2 (https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html), which replaced it with `sparse_output` and was released in december 2022. Should we keep support for older versions (0.22 was introduced in the beginning of 2020)?

2024-01-22 10:54 UTC, popescu-v commented on .github/workflows/build-pip-package.yml
> +          kh-status | grep "MPI command" | grep -wq mpiexec
> Would an `if [[ MODULES` or whatever solve this in the same step?

Rather, a test for `/etc/os-release` to check if on Rocky?

2024-01-22 11:07 UTC, folmos-at-orange commented on doc/samples/samples_sklearn.rst
Yes, according to our support policy:
Ubuntu-20.04 -> Python 3.8 -> sklearn 0.22.

Does the keyword exists in 0.22 `sparse_output` ?

2024-01-22 12:47 UTC, popescu-v commented on doc/samples/samples_sklearn.rst
Hence, I will try to switch according to the sklearn version (< 1.2 vs. >= 1.2) for this parameter.

2024-01-22 13:28 UTC, folmos-at-orange commented on doc/samples/samples_sklearn.rst
No, i'd leave it with the new version. Maybe add a comment with a the comment with the line for old sklearn.

2024-01-22 14:15 UTC, popescu-v commented on khiops/core/internals/runner.py
> +            # https://modules.readthedocs.io/en/latest/module.html,
Done.

2024-01-22 14:16 UTC, popescu-v commented on .github/workflows/build-pip-package.yml
> +          kh-status | grep "MPI command" | grep -wq mpiexec
Done.

2024-01-22 14:16 UTC, popescu-v commented on .github/workflows/build-pip-package.yml
> +          kh-status | grep "MPI command" | grep -wq mpiexec
Done. Also, changed runner so that environment setup in the calling shell is not assumed anymore (thus, it is just like khiops-env now).

2024-01-22 14:17 UTC, popescu-v commented on .github/workflows/run-unit-tests.yml
> +          python3 setup.py egg_info
Done.

2024-01-22 14:17 UTC, popescu-v commented on .github/workflows/run-unit-tests.yml
> +        run: python -m unittest -v tests.test_khiops_integrations.KhiopsRunnerEnvironmentTests.test_runner_has_mpiexec_on_linux
Done and done.

2024-01-22 14:17 UTC, popescu-v commented on tests/test_khiops_integrations.py
> +            # yum list installed
Done and done.

2024-01-22 14:17 UTC, popescu-v commented on tests/test_khiops_integrations.py
> +            )
Done.

2024-01-22 14:28 UTC, popescu-v commented on doc/samples/samples_sklearn.rst
Tests with a Python 3.8 on a Conda environment and on an old Rocky8  Python 3.8 environment allow to install sklearn 1.3.0 and 1.3.2, respectively. Hence, do we still need to support skearn < 1.2 even for Python 3.8?

2024-01-22 14:29 UTC, popescu-v commented on doc/samples/samples_sklearn.rst
I left it as it was for now (in light of the previous comment too).

2024-01-23 09:29 UTC, folmos-at-orange requested changes

2024-01-23 10:12 UTC, popescu-v commented on khiops/core/internals/runner.py
> +                        break
`stdout` is `bytes`, as it is taken directly out of `Popen.communicate()`.

2024-01-23 10:13 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +                        break
Ok after discussion.

2024-01-23 10:13 UTC, popescu-v commented on packaging/docker/khiopspydev/Dockerfile.rocky8
> +ARG SERVER_REVISION
Ok for factoring this out.

2024-01-23 12:44 UTC, popescu-v commented on doc/samples/samples_sklearn.rst
Added comment for sklearn < 1.2.

2024-01-23 13:18 UTC, popescu-v commented on khiops/core/internals/runner.py
> +                        # module load
I have moved the comment before the `if`, and rephrased it.

2024-01-23 13:49 UTC, popescu-v commented on khiops/core/internals/runner.py
> +
Done.

2024-01-23 13:49 UTC, popescu-v commented on packaging/docker/khiopspydev/Dockerfile.rocky8
> +ARG SERVER_REVISION
Done. Added CI step for KHIOPSDEV_OS -> os codename lookup.

2024-01-23 13:50 UTC, popescu-v commented on khiops/samples/samples_sklearn.py
> +        ),
Done; line added.

2024-01-23 13:50 UTC, popescu-v commented on khiops/core/internals/runner.py
> +                        # module load
Done.

2024-01-23 16:47 UTC, merged