141 implement a conda fallback strategy
KhiopsML/khiops-python pull request #142
Opened 2024-02-08 16:32 UTC by popescu-v

- implement Conda fallback strategy
- compute mpiexec path for Conda-based environments

2024-02-08 17:13 UTC, folmos-at-orange requested changes

2024-02-08 17:13 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +            mpiexec_path = os.environ.get("KHIOPS_MPIEXEC_PATH") or os.path.join(
I'd do this with `installation_method in ["conda", "conda-based"]` so we cover the other issue #140.

2024-02-08 17:13 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +    and pip + system-wide"""
One line titles.

Specifics (if any for a private method) the body.

2024-02-09 08:56 UTC, popescu-v commented on khiops/core/internals/runner.py
> +    """Check MODL* executables exist relative to the specified binary dir"""
OK for `_modl_executables_exist`.

2024-02-09 08:58 UTC, popescu-v commented on khiops/core/internals/runner.py
> +    return ("pip + system-wide", None)
Yes, but we would be obliged to compute the root directory twice; even if this computation can be factored in a (helper) function, it would be done twice: once for determining the installation method, and the second time for setting `_khiops_bin_dir`...

2024-02-09 09:14 UTC, popescu-v commented on khiops/core/internals/runner.py
> +    reference_dir = Path(khiops.__file__.partition(python_version)[0]).parent.as_posix()
Good catch! OK, but I would prefer a more generic solution rather than hard-coding the indexes, `3` vs. `4`.
Someting like:

```python
pattern = re.compile(f"[Ll]ib{os.path.sep}(?:python\d+.\d+)?{os.path.sep}?site-packages{os.path.sep}")

conda_env_dir = pattern.split(khiops.__file__)[0]
```

2024-02-09 09:30 UTC, popescu-v commented on khiops/core/internals/runner.py
> +    reference_dir = Path(khiops.__file__.partition(python_version)[0]).parent.as_posix()
Or even more generic:
```python
pattern = re.compile(f"[Ll]ib{os.path.sep}.*{os.path.sep}khiops")

conda_env_dir = pattern.split(khiops.__file__)[0]
```
The only case this would not work would be the `pip install -e`, in which case `khiops.__file__` is `None`. But in this case the other solutions based on `__file__` wouldn't work either.

2024-02-09 09:31 UTC, popescu-v commented on khiops/core/internals/runner.py
> +            mpiexec_path = os.environ.get("KHIOPS_MPIEXEC_PATH") or os.path.join(
Well, for `installation_method == "conda"`, `which` works, so there is no need for this IMHO.

2024-02-09 09:31 UTC, popescu-v commented on khiops/core/internals/runner.py
> +    and pip + system-wide"""
Ok.

2024-02-09 09:41 UTC, popescu-v commented on khiops/core/internals/runner.py
> +    """Check MODL* executables exist relative to the specified binary dir"""
Done.

2024-02-09 09:50 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +    return ("pip + system-wide", None)
I think is better to have to clearly defined functions. Recomputing the directory is trivial so it isn't critical to have it defactored.

2024-02-09 09:52 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +    reference_dir = Path(khiops.__file__.partition(python_version)[0]).parent.as_posix()
> Good catch! OK, but I would prefer a more generic solution rather than hard-coding the indexes, `3` vs. `4`. Someting like:
> 
> ```python
> pattern = re.compile(f"[Ll]ib{os.path.sep}(?:python\d+.\d+)?{os.path.sep}?site-packages{os.path.sep}")
> 
> conda_env_dir = pattern.split(khiops.__file__)[0]
> ```

Here we are guessing a more specific thing, thus it can break easier. Better to guess just the number of directories above the current one. It is simpler.

I'd not trying to be future proof for a workaround like this, we really don't know the future, better to have a non-crytpic code that we can change in the future if necessary.

2024-02-09 09:58 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +    reference_dir = Path(khiops.__file__.partition(python_version)[0]).parent.as_posix()
> Or even more generic:
> 
> ```python
> pattern = re.compile(f"[Ll]ib{os.path.sep}.*{os.path.sep}khiops")
> 
> conda_env_dir = pattern.split(khiops.__file__)[0]
> ```
> 
> The only case this would not work would be the `pip install -e`, in which case `khiops.__file__` is `None`. But in this case the other solutions based on `__file__` wouldn't work either.

In my machine with the editable install of `khiops-python` I have 
```bash
(10:56:56)> python -c'import khiops; print(khiops.__file__)'
/Users/folmos/work/khiops/khiops-python/khiops/__init__.py
```

2024-02-09 10:12 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +            mpiexec_path = os.environ.get("KHIOPS_MPIEXEC_PATH") or os.path.join(
But what about the issue #140 then.

2024-02-09 11:46 UTC, popescu-v commented on khiops/core/internals/runner.py
> +    return ("pip + system-wide", None)
Ok, I agree. I have re-implemented this accordingly.

2024-02-09 11:47 UTC, popescu-v commented on khiops/core/internals/runner.py
> +    reference_dir = Path(khiops.__file__.partition(python_version)[0]).parent.as_posix()
Do you run this from inside the `khiops` directory?

2024-02-09 11:48 UTC, popescu-v commented on khiops/core/internals/runner.py
> +            mpiexec_path = os.environ.get("KHIOPS_MPIEXEC_PATH") or os.path.join(
I think this issue needs to be rephrased. The issue is not about CONDA_PREFIX, but about what to do if it is missing, IMHO.

2024-02-09 11:51 UTC, popescu-v commented on khiops/core/internals/runner.py
> +    reference_dir = Path(khiops.__file__.partition(python_version)[0]).parent.as_posix()
> > Good catch! OK, but I would prefer a more generic solution rather than hard-coding the indexes, `3` vs. `4`. Someting like:
> > ```python
> > pattern = re.compile(f"[Ll]ib{os.path.sep}(?:python\d+.\d+)?{os.path.sep}?site-packages{os.path.sep}")
> > 
> > conda_env_dir = pattern.split(khiops.__file__)[0]
> > ```
> 
> Here we are guessing a more specific thing, thus it can break easier. Better to guess just the number of directories above the current one. It is simpler.
> 
> I'd not try to be future-proof for a workaround like this, we really don't know the future, better to have a non-crytpic code that we can change in the future if necessary.

To me, having hard-coded indexes is more cryptic and brittle. Having a regex like the latter proposed, seems less brittle to me, because:
- `khiops` should always be in the name; we can use `khiops.__name__` for even more robustness;
- `[Ll]ib` seems less restrictive to me than counting the nesting levels (I would keep the second proposal, not the first one that hard-coded the presence of "`pythonX.Y`".

2024-02-09 12:26 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +    reference_dir = Path(khiops.__file__.partition(python_version)[0]).parent.as_posix()
> Do you run this from inside the `khiops` directory?

Yes, now I reproduce. So if it is `None` the `khiops.__file__` then we assume `binary+pip`.

2024-02-09 12:27 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +            mpiexec_path = os.environ.get("KHIOPS_MPIEXEC_PATH") or os.path.join(
Ok. Please update it or close it as obsolete.

2024-02-09 13:11 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +    reference_dir = Path(khiops.__file__.partition(python_version)[0]).parent.as_posix()
> To me, having hard-coded indexes is more cryptic and brittle. Having a regex like the latter proposed, seems less brittle to me, because:
> 
> * `khiops` should always be in the name; we can use `khiops.__name__` for even more robustness;
> * `[Ll]ib` seems less restrictive to me than counting the nesting levels (I would keep the second proposal, not the first one that hard-coded the presence of "`pythonX.Y`").

Why it is more cryptic? the comment is just above the line. The regex is more cryptic because you have to parse it in your mind. Having a simple index of a list is a lot less complex.

2024-02-09 14:31 UTC, popescu-v commented on khiops/core/internals/runner.py
> +    reference_dir = Path(khiops.__file__.partition(python_version)[0]).parent.as_posix()
> > Do you run this from inside the `khiops` directory?
> 
> Yes, now I reproduce. So if it is `None` the `khiops.__file__` then we assume `binary+pip`.

Yes.

2024-02-09 16:24 UTC, popescu-v commented on khiops/core/internals/runner.py
> +    reference_dir = Path(khiops.__file__.partition(python_version)[0]).parent.as_posix()
> > To me, having hard-coded indexes is more cryptic and brittle. Having a regex like the latter proposed, seems less brittle to me, because:
> > 
> > * `khiops` should always be in the name; we can use `khiops.__name__` for even more robustness;
> > * `[Ll]ib` seems less restrictive to me than counting the nesting levels (I would keep the second proposal, not the first one that hard-coded the presence of "`pythonX.Y`").
> 
> Why it is more cryptic? the comment is just above the line. The regex is more cryptic because you have to parse it in your mind. Having a simple index of a list is a lot less complex.

I went for the hard-coded indexes, as this is a hack anyway.

2024-02-09 16:26 UTC, popescu-v commented on khiops/core/internals/runner.py
> +            mpiexec_path = os.environ.get("KHIOPS_MPIEXEC_PATH") or os.path.join(
Closing this as the mentioned issue has already been obsoleted and closed.

2024-02-12 08:02 UTC, folmos-at-orange requested changes

2024-02-12 08:02 UTC, folmos-at-orange commented on tests/test_khiops_integrations.py
> +        """Test that local runner works in non-Conda, Conda-based environments"""
For later: We should make this test to be run in all circumstances.

2024-02-12 08:03 UTC, folmos-at-orange commented
Before merging this i'll test it in Colab. @popescu-v could you do it in a JupyterHub environment ?

2024-02-12 09:14 UTC, popescu-v commented on khiops/core/internals/runner.py
> +    and pip + system-wide"""
This was done, right?

2024-02-12 09:15 UTC, popescu-v commented on tests/test_khiops_integrations.py
> +        """Test that local runner works in non-Conda, Conda-based environments"""
But I think it is already. Only the preceding test is skipped unless on Linux.

2024-02-12 09:17 UTC, popescu-v commented on khiops/core/internals/runner.py
> +    return False
Yes, right.

2024-02-12 10:02 UTC, folmos-at-orange commented on tests/test_khiops_integrations.py
> +        """Test that local runner works in non-Conda, Conda-based environments"""
I think it is not tested in a real conda installation in the CI.

2024-02-12 10:42 UTC, popescu-v commented on tests/test_khiops_integrations.py
> +        """Test that local runner works in non-Conda, Conda-based environments"""
Yes, right. Perhaps we should launch at least all integration tests in the Conda package CI testing job?

2024-02-12 13:18 UTC, folmos-at-orange commented
The fallback works in Colab 
<img width="483" alt="Screenshot 2024-02-08 at 15 10 12" src="https://github.com/KhiopsML/khiops-python/assets/92923444/4a07d523-28b3-4fd0-851b-1ef1e3c9d1e2">

2024-02-12 16:56 UTC, folmos-at-orange approved these changes
LGTM

Merging pending tests in JupyterHub and rebase

2024-02-12 16:59 UTC, popescu-v commented on khiops/core/internals/runner.py
> +                    )
It's just that I add `mpiexec[.extension]` (with extension either provided by the `KHIOPS_MPIEXEC_PATH` env var - e.g. `path/to/mpiexec.EXE`, or added programmatically if missing - `.exe`). In order not to repeat the calculation, I look it up with `.parts[-1]`.

2024-02-12 17:41 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +                    )
I'd explain with a comment.

2024-02-13 09:38 UTC, popescu-v commented
> LGTM
> 
> Merging pending tests in JupyterHub and rebase

The rebase has been done.
According to report, the fallback works in JupyterHub.

2024-02-13 09:39 UTC, merged