Implement new Khiops versioning scheme
KhiopsML/khiops-python pull request #144
Opened 2024-02-09 17:41 UTC by folmos-at-orange

2024-02-09 17:54 UTC, folmos-at-orange commented
In the end we were already compatible with a fourth digit. The thing that needed to be addressed were the new Khiops versioning scheme.

2024-02-09 18:29 UTC, popescu-v commented on khiops/core/internals/version.py
> +        if len(raw_parts) != 3:
This implies that all tags on the Khiops GitHub repo will observe this convention, right?

2024-02-09 18:31 UTC, popescu-v commented on khiops/core/internals/version.py
> +            self._patch, self._pre_release = patch_and_pre_release.split("-")
IMHO, we need to check that `patch_and_pre_release` contains a single `-`

2024-02-09 18:34 UTC, popescu-v commented on khiops/core/internals/version.py
>      def __str__(self):
`__str__` could just call `__repr__`, couldn't it?

2024-02-09 18:37 UTC, popescu-v commented on khiops/core/internals/version.py
> +        """Lexicographic order for each of the version parts
The way I read it is rather "Numeric order for major, minor and patch parts. Lexicographic order for the pre-release part", right?

2024-02-09 18:39 UTC, popescu-v commented on khiops/core/internals/version.py
> +        return self._version_str.__hash__()
Or `self.__repr__().__hash__()`?

2024-02-09 18:51 UTC, popescu-v requested changes
See comments

2024-02-12 08:46 UTC, folmos-at-orange commented on khiops/core/internals/version.py
> +    """Tests if a stringos contains only characters [0-9]
Ok & Done

2024-02-12 08:47 UTC, folmos-at-orange commented on khiops/core/internals/version.py
> +        if len(raw_parts) != 3:
Yes

2024-02-12 08:48 UTC, folmos-at-orange commented on khiops/core/internals/version.py
> +            self._patch, self._pre_release = patch_and_pre_release.split("-")
Ok

2024-02-12 08:51 UTC, folmos-at-orange commented on khiops/core/internals/version.py
> +            self._patch, self._pre_release = patch_and_pre_release.split("-")
Changed the test just above that line to cover that case. Done.

2024-02-12 08:53 UTC, folmos-at-orange commented on khiops/core/internals/version.py
>      def __str__(self):
Removed the method.

2024-02-12 08:57 UTC, folmos-at-orange commented on khiops/core/internals/version.py
> +        """Lexicographic order for each of the version parts
major, minor and patch follow numerical order and the pre-release follows an alphabetical order. The whole version is lexicographical, taking each part as a "character" (cf. https://en.wikipedia.org/wiki/Lexicographic_order#Definition)

2024-02-12 08:58 UTC, folmos-at-orange commented on khiops/core/internals/version.py
> +        return self._version_str.__hash__()
Ok.

2024-02-12 09:06 UTC, popescu-v commented
> In the end we were already compatible with a fourth digit. The thing that needed to be addressed were the new Khiops versioning scheme.

Yes, ok, I got it. So, no need for extra provisions for the fourth digit

2024-02-12 09:13 UTC, popescu-v commented on khiops/core/internals/version.py
> +        """Lexicographic order for each of the version parts
Ok, so the "symbols" are the parts, right? Hence "a.b.c > a'.b'.c'" iff "a > a' or a == a' and b > b' or a == a' and b == b' and c > c'", knowing that "a > a' and "b > b'" are determined numerically, while "c > c'" is determined lexicographically, taking "c" and "c'" characters as "symbols", right?

If all this is true, then I think the comment should be updated: otherwise, IMHO we understand that for "each of the version parts" the ordering relation is lexicographic. Whereas what we have here is lexicographic order in terms of the versions parts, right? Then, I would at least propose something like: "Lexicographic order in terms of the version parts."

2024-02-12 09:44 UTC, popescu-v commented on khiops/core/internals/version.py
>      def __str__(self):
Ok, thus we remain with the default `__str__`, which just calls `__repr__`

2024-02-12 10:04 UTC, folmos-at-orange commented on khiops/core/internals/version.py
> +        """Lexicographic order for each of the version parts
Maybe that's too much. Let's forget lexicographical and just put "Normal versioning order" .

2024-02-12 14:33 UTC, folmos-at-orange commented on khiops/core/internals/version.py
> +        """Lexicographic order for each of the version parts
Ok as per offline conversation.

2024-02-12 14:35 UTC, folmos-at-orange commented on khiops/core/internals/version.py
> +        """Lexicographic order for each of the version parts
Done

2024-02-12 15:40 UTC, popescu-v commented on khiops/core/internals/version.py
> +        """str : The pre-release tag of this version. Either 'a', 'b' or 'rc' or None"""
Update to mention the increment number.

2024-02-12 15:42 UTC, popescu-v commented on khiops/core/internals/version.py
> +            and self.pre_release == version.pre_release
If pre-release increment has several digits, how is the comparison being done? Two choices:
- lexicographically (as of now): "-a2" > "-a12"
- numerically: "-a2" < "-a12"

Only the latter  seems correct to me. Hence, IMHO, this part needs to be updated: the pre-release part needs to be compared lexicographically as before, while the pre-release increment needs to be compared numerically.

2024-02-12 15:44 UTC, popescu-v commented on khiops/core/internals/version.py
> +            is_greater = self.pre_release > version.pre_release
Update to separate lexicographic comparison of pre-release tags and numeric comparisons of pre-release increments.

2024-02-12 15:45 UTC, popescu-v commented on tests/test_core.py
> +            "10.0.8-b2",
Add e.g. "10.0.8-b12" and check proper comparison, i.e. that "10.0.8-b2" < "10.0.8-b12".

2024-02-12 15:45 UTC, popescu-v requested changes
A few comments need to be addresssed.

2024-02-12 15:56 UTC, folmos-at-orange commented on khiops/core/internals/version.py
> +            and self.pre_release == version.pre_release
I'll make the comparison by the internal parts.

2024-02-12 15:56 UTC, folmos-at-orange commented on tests/test_core.py
> +            "10.0.8-b2",
Ok

2024-02-12 15:59 UTC, folmos-at-orange commented on tests/test_core.py
> +            "10.0.8-b2",
And I won't accept pre-releases without increment.

2024-02-12 16:04 UTC, folmos-at-orange commented on tests/test_core.py
> +            "10.0.8-b2",
And also left zeros are forbidden.

2024-02-12 16:08 UTC, popescu-v commented on tests/test_core.py
> +            "10.0.8-b2",
Ok and ok.

2024-02-12 16:40 UTC, folmos-at-orange commented on khiops/core/internals/version.py
> +        """str : The pre-release tag of this version. Either 'a', 'b' or 'rc' or None"""
Done

2024-02-12 16:40 UTC, folmos-at-orange commented on khiops/core/internals/version.py
> +            is_greater = self.pre_release > version.pre_release
Done, now it is numerically.

2024-02-12 16:41 UTC, folmos-at-orange commented on khiops/core/internals/version.py
> +            and self.pre_release == version.pre_release
Done

2024-02-12 16:47 UTC, popescu-v approved these changes
LGTM.

2024-02-12 16:57 UTC, merged