Anaconda.org upload
KhiopsML/khiops-python pull request #159
Opened 2024-03-12 21:22 UTC by folmos-at-orange

2024-03-13 13:10 UTC, popescu-v commented on .github/workflows/conda.yml
> +    if: false
What is the purpose of this line? Wouldn't this make the `test` job never execute?

2024-03-13 13:20 UTC, folmos-at-orange commented on .github/workflows/conda.yml
> +    if: false
I remove it (it was as just to test fast).

2024-03-13 13:25 UTC, popescu-v requested changes
Almost LGTM (one small caveat - see the comment).

2024-03-13 13:25 UTC, popescu-v commented on .github/workflows/conda.yml
> +      - name: Extract Khiops Package Version
I would put this stage just before the "Create the release zip archive", which needs the output of this stage; Anaconda upload does not need this stage AFAIU.

2024-03-13 13:25 UTC, folmos-at-orange commented on .github/workflows/conda.yml
> +      - name: Extract Khiops Package Version
Ok

2024-03-13 16:13 UTC, folmos-at-orange commented on .github/workflows/conda.yml
> +      - name: Extract Khiops Package Version
Done

2024-03-14 16:34 UTC, popescu-v approved these changes
LGTM. I would only add a small section to CONTRIBUTING.md instructing not to reuse the same (a, b, rc, ...) tag for different commits, as this would automatically overwrite the Conda packages on the `khiops-dev`.

2024-03-15 11:04 UTC, popescu-v commented on CONTRIBUTING.md
> +Prefer to augment the pre-release revision number to re-create a tag because the CI overwrite
s/"because the CI overwrite"/"because otherwise the CI would overwrite"/

2024-03-15 11:11 UTC, popescu-v approved these changes
LGTM; can be merged IMHO

2024-03-15 13:57 UTC, merged