Support single-column Pandas dataframes as targets in estimators
KhiopsML/khiops-python pull request #160
Opened 2024-03-14 09:29 UTC by tramora

the target variable "y" can currently be an array-like of shape (n_samples,), a pandas.Dataframe of shame (n_samples, 1) - purpose of this commit - or a string key of a dataset dict (will be removed in version 11)

2024-03-14 15:36 UTC, popescu-v commented on khiops/sklearn/estimators.py
> +        # if a DataFrame is given, extract the first column to get an array-like object
The place for this kind of processing is in `tables.py`, namely in the `DatasetTable` class and its specializations, viz. `PandasTable` (for the cases where `X` is a dataframe). The case where `X` is a NumPy array is already being taken care of in the `NumpyTable` class.

But, before converting the dataframe to a series, we need to check that, as per the issue's content, the input dataframe `y` is a has precisely one column. In this case, even if the dataframe is empty (has 0 rows), `iloc` does not fail.

However, `column_or_1d` is not fully equivalent to `iloc`, as `iloc` preserves the Series type and the name, whereas `column_or_1d` itself does not. To be fully equivalent to `foo.iloc[:, 0]`, we need to do: `pd.Series(column_or_1d(foo), name=foo.columns[0])` (under the hypothesis that the dataframe `foo` has one column).

Hence, your proposed modification could be moved to `tables.py`, in the `PandasTable.__init__(...)` method, where the `target_column` argument is being type-checked and value-checked. More precisely, after the `if isinstance(target_column, pd.Series): ...` block, I would add the following block:

```python
            ...
            elif isinstance(target_column, pd.DataFrame):
                number_of_target_columns = len(target_column.columns)
                if number_of_target_columns != 1:
                    raise ValueError(
                        "Target dataframe should contain only one column. "
                        f"It contains {number_of_target_columns}."
                    )
                target_column = target_column.iloc[:, 0]
                # Or:
                # target_column = pd.Series(
                #     column_or_1d(target_column), name=target_column.columns[0]
                # )
            ...
```

2024-03-14 16:12 UTC, popescu-v commented on tests/test_sklearn.py
> +            # FIXME : find a clever way to avoid executing the estimator method twice
Here, we need to create a brand new test. We should not change `_test_template` in `test_sklearn.py`, but add a new test. To this end, we need to add a new input to the sklearn tests fixture.

2024-03-14 16:13 UTC, popescu-v requested changes
There are two pending comments to address.

2024-03-15 10:50 UTC, tramora commented on khiops/sklearn/estimators.py
> +        # if a DataFrame is given, extract the first column to get an array-like object
Indeed `tables.py` was the right place for the modification.

2024-03-19 09:21 UTC, folmos-at-orange approved these changes
LGTM

One minor detail and you may merge.

2024-03-19 09:21 UTC, folmos-at-orange commented on tests/test_sklearn.py
> +        self._test_template(
Document well the `source_type` in the docstring of `_test_template`.

2024-03-19 09:56 UTC, popescu-v commented on tests/test_sklearn.py
> +        self._test_template(
Ok, done; updated the documentation.

2024-03-19 12:57 UTC, popescu-v approved these changes
LGTM.

2024-03-19 15:25 UTC, merged