Separate conda package into khiops-core and khiops
KhiopsML/khiops-python pull request #170
Opened 2024-03-26 13:50 UTC by folmos-at-orange

2024-04-04 11:56 UTC, popescu-v requested changes

2024-04-04 11:56 UTC, popescu-v commented on .github/workflows/conda.yml
> +          conda build --channel conda-forge --channel khiops-dev \
IMHO, the channel for the upstream `khiops-core` dependency should be customizable, between `khiops-dev` and `khiops`, so that one can build against an officially released `khiops-core` Conda package when building the "final" `khiops` Python Conda package.

2024-04-04 11:56 UTC, popescu-v commented on .github/workflows/conda.yml
> +          conda install --channel conda-forge --channel khiops-dev --channel ./khiops-conda/ khiops
I would make the channel for the upstream `khiops-core` Conda package customizable, between `khiops-dev` and `khiops` (see my previous comment in this respect for the rationale).

2024-04-04 11:56 UTC, popescu-v commented on .github/workflows/conda.yml
> +      - name: Upload the Package to anaconda.org
s/Package/package/ (no need for capital "P" here)

2024-04-04 11:56 UTC, popescu-v commented on .github/workflows/conda.yml
> +      - name: Extract the Package Version
No need to capitalize "Package" here IMHO

2024-04-04 11:56 UTC, popescu-v commented on packaging/conda/meta.yaml
> -  {% if "KHIOPS_APPLE_CERTIFICATE_COMMON_NAME" in os.environ %}
How would this be handled now, when `KHIOPS_APPLE_CERTIFICATE_COMMON_NAME` is set at the `khiops-core` packaging level? Don't we need to make these Khiops Python entry points relocatable anymore on Mac OS?

2024-04-04 12:52 UTC, folmos-at-orange commented on .github/workflows/conda.yml
> +          conda build --channel conda-forge --channel khiops-dev \
I don't think so. However the version may be customizable.

2024-04-04 12:53 UTC, folmos-at-orange commented on .github/workflows/conda.yml
> +      - name: Upload the Package to anaconda.org
nitpick

2024-04-04 12:53 UTC, folmos-at-orange commented on .github/workflows/conda.yml
> +      - name: Extract the Package Version
se above.

2024-04-04 12:54 UTC, folmos-at-orange commented on packaging/conda/meta.yaml
> -  {% if "KHIOPS_APPLE_CERTIFICATE_COMMON_NAME" in os.environ %}
They are relocated by default.

2024-04-04 12:55 UTC, folmos-at-orange commented on .github/workflows/conda.yml
> +          conda install --channel conda-forge --channel khiops-dev --channel ./khiops-conda/ khiops
See above.

2024-04-04 17:23 UTC, popescu-v commented on .github/workflows/conda.yml
> +          conda build --channel conda-forge --channel khiops-dev \
Oh, wait: actually, for _building_ the `khiops` Python Conda package we don't need the `khiops-core` Conda package, do we? (it is needed for _testing_ the `khiops` Python Conda package though). Hence, why do we need to keep `--channel khiops-dev` here?

2024-04-04 17:25 UTC, popescu-v commented on .github/workflows/conda.yml
> +          conda install --channel conda-forge --channel khiops-dev --channel ./khiops-conda/ khiops
Here, for _installing_ / _testing_ the (just) build `khiops` Python Conda package, IMHO it is suitable to be able to choose to install an officially-released `khiops-core` Conda dependency (suppose the `khiops-core` with the right tag has been already released "yesterday" and "today" we run the workflows for building / testing / releasing the `khiops` package).

Hence, in the _testing_ context, I would like to be able to choose whether to install the upstream `khiops-core` dependency from the dev channel, vs. the official release (to reproduce the actual usage context as much as possible).

2024-04-04 17:35 UTC, folmos-at-orange commented on .github/workflows/conda.yml
> +          conda build --channel conda-forge --channel khiops-dev \
Indeed, it is only to make the basics tests. And I think testing should be done only with assets of the test channel (for simplicity). The official channel contains only assets that have been tested.

2024-04-04 17:36 UTC, folmos-at-orange commented on .github/workflows/conda.yml
> +          conda install --channel conda-forge --channel khiops-dev --channel ./khiops-conda/ khiops
Any official package must have been passed by test. The `khiops-dev` channel will contain all versions `khiops-core` released. So we only need the version.

2024-04-04 17:58 UTC, popescu-v commented on .github/workflows/conda.yml
> +          conda install --channel conda-forge --channel khiops-dev --channel ./khiops-conda/ khiops
OK, if we are sure that the same-version `khiops-core` package on `khiops-dev` is identical "at-the-bit-level" to the same package on `khiops`.

2024-04-04 18:00 UTC, popescu-v commented on .github/workflows/conda.yml
> +          conda build --channel conda-forge --channel khiops-dev \
So, for this _build_ stage, could we remove it?

2024-04-05 09:51 UTC, folmos-at-orange commented on .github/workflows/conda.yml
> +          conda build --channel conda-forge --channel khiops-dev \
I think it is still necessary for the `test` part of the `meta.yaml`

2024-04-05 12:08 UTC, popescu-v commented on .github/workflows/conda.yml
> +          conda build --channel conda-forge --channel khiops-dev \
I am not sure, as we only test module imports, not execution. Could you try without it?

2024-04-05 12:13 UTC, popescu-v commented on packaging/conda/meta.yaml
> +  number: 0
This will always be `0` for us, or should we set-up a protocol for updating it?

2024-04-05 12:16 UTC, popescu-v commented on .github/workflows/conda.yml
> +        default: 10.2.1
Should we have a hard-coded default here? Because IMHO one risks not bumping it as needed.

Perhaps setting this default as computed from the current Git tag? (like `git describe --tags | awk 'BEGIN {FS = "."; OFS = FS} {print $1, $2, $3}'`?

2024-04-05 12:39 UTC, folmos-at-orange commented on .github/workflows/conda.yml
> +          conda build --channel conda-forge --channel khiops-dev \
kh-status would fail if it doesn't find the binaries.

2024-04-05 12:41 UTC, folmos-at-orange commented on .github/workflows/conda.yml
> +        default: 10.2.1
Too much complexity. I think is better to maintain this by hand as it doesn't change that often. I'll add it to the release checklist.

2024-04-05 13:05 UTC, popescu-v commented on .github/workflows/conda.yml
> +        default: 10.2.1
OK, fair enough.

2024-04-05 13:29 UTC, popescu-v commented on .github/workflows/conda.yml
> +          conda build --channel conda-forge --channel khiops-dev \
OK, I see. I wonder if we need to test the _Python_ package _build_ with `kh-status`. Perhaps we could just keep the imports as tests, as this would stay within the scope of the pure Python package features. And we would keep the `kh-status` for the testing workflow job?

2024-04-05 15:19 UTC, folmos-at-orange commented on .github/workflows/conda.yml
> +          conda build --channel conda-forge --channel khiops-dev \
I prefer to leave that minimal check for building out of the workflow.

2024-04-05 15:20 UTC, folmos-at-orange commented on .github/workflows/conda.yml
> +          conda install --channel conda-forge --channel khiops-dev --channel ./khiops-conda/ khiops
Its a bit too much to 'bit-by-bit'. At least it would be constructed from the same tag. Or even transferred directly from `khiops-dev`

2024-04-05 16:01 UTC, popescu-v commented on .github/workflows/conda.yml
> +          conda build --channel conda-forge --channel khiops-dev \
We already launch `kh-status` in the package `test` workflow job. Why do we need to redundantly keep it the after-build tests as well? Removing it would allow us to focus on the pure Python aspects: just test that the namespacing is set-up right.

2024-04-05 16:20 UTC, popescu-v commented on .github/workflows/conda.yml
> +          conda install --channel conda-forge --channel khiops-dev --channel ./khiops-conda/ khiops
Yes, perhaps this is the way to go: add workflow stage for: 1/ fetching the package from `khiops-dev`; 2/ uploading it to |`khiops`?

2024-04-05 16:36 UTC, folmos-at-orange commented on .github/workflows/conda.yml
> +          conda install --channel conda-forge --channel khiops-dev --channel ./khiops-conda/ khiops
Too complicated. Just build from the same tag.

2024-04-05 16:37 UTC, folmos-at-orange commented on .github/workflows/conda.yml
> +          conda build --channel conda-forge --channel khiops-dev \
You want at least a minimal test when you build in local. A bit of redundancy is not harmful.

2024-04-05 16:44 UTC, popescu-v commented on .github/workflows/conda.yml
> +          conda install --channel conda-forge --channel khiops-dev --channel ./khiops-conda/ khiops
Building from the same tag does not guarantee that the packages are identical for the same tag IMHO (tags can be moved, development containers might change). Copying the package from `khiops-dev` to `khiops` does provide this guarantee.

2024-04-05 17:24 UTC, folmos-at-orange commented on .github/workflows/conda.yml
> +          conda install --channel conda-forge --channel khiops-dev --channel ./khiops-conda/ khiops
That is true. I don't think making things more complex for this minor risk is worth it.

2024-04-05 17:38 UTC, folmos-at-orange commented on .github/workflows/conda.yml
> +          conda build --channel conda-forge --channel khiops-dev \
Ok

2024-04-08 08:26 UTC, popescu-v commented on .github/workflows/conda.yml
> +          conda install --channel conda-forge --channel khiops-dev --channel ./khiops-conda/ khiops
Well, if through convention we could enforce that:

- no non-alpha tag should be overwritten, _ever_, in the  `khiops-core` repo;
- no alpha tag should _ever_ be used for getting a `khiops-core` package as a dependency of the `khiops` package.

then the current behavior seems acceptable to me, as a trade-off. But this seems acceptable only if the aforementioned two points are clearly stated (as cautionary notes) in the contributing guides of the respective repositories:

- the first point should be mentioned somewhere in the `khiops` repo, perhaps in https://github.com/KhiopsML/khiops/wiki/Release-Process?
- the second point should be mentioned in the `CONTRIBUTING.md` file of the current repo.

2024-04-08 14:09 UTC, folmos-at-orange commented on .github/workflows/conda.yml
> +          conda install --channel conda-forge --channel khiops-dev --channel ./khiops-conda/ khiops
I wrote a comment in the wiki for the first point.
The second point I put a note in the workflow.

2024-04-08 14:10 UTC, folmos-at-orange commented on .github/workflows/conda.yml
> +          conda build --channel conda-forge --channel khiops-dev \
I think this is obsolete with the pinned version of `khiops-core`

2024-04-08 16:29 UTC, popescu-v commented on CONTRIBUTING.md
> +    - `git pull`
Don't we need a `git rebase main` here, while on `dev`?

2024-04-08 16:30 UTC, popescu-v commented on CONTRIBUTING.md
> +    - `git pull`
`git pull --tags` to also get the tag locally?

2024-04-08 16:32 UTC, popescu-v commented on CONTRIBUTING.md
> +    - `git push dev` (you need to remove the protections of `dev` for this step)
If `dev`'s `HEAD` changed following the rebase, don't we need to `git push -f` here?

2024-04-08 16:33 UTC, popescu-v commented on CONTRIBUTING.md
> +    - The release tag
What about `khiops-core-version`? Couldn't this be specified as well, to make sure it matches the release tag?

2024-04-08 16:34 UTC, popescu-v commented on CONTRIBUTING.md
> +  - Execute the `API Docs` worflow specifying "Deploy GH Pages".
s/worflow/workflow/

2024-04-09 08:25 UTC, folmos-at-orange commented on CONTRIBUTING.md
> +    - `git pull`
Ok

2024-04-09 08:27 UTC, folmos-at-orange commented on CONTRIBUTING.md
> +    - The release tag
It is specified above.

2024-04-09 08:27 UTC, folmos-at-orange commented on CONTRIBUTING.md
> +  - Execute the `API Docs` worflow specifying "Deploy GH Pages".
Ok

2024-04-09 08:28 UTC, folmos-at-orange commented on CONTRIBUTING.md
> +    - `git pull`
I put a `git reset --hard`

2024-04-09 08:33 UTC, folmos-at-orange commented on CONTRIBUTING.md
> +    - `git pull`
Done

2024-04-09 08:33 UTC, folmos-at-orange commented on CONTRIBUTING.md
> +    - The release tag
Done

2024-04-09 08:33 UTC, folmos-at-orange commented on CONTRIBUTING.md
> +  - Execute the `API Docs` worflow specifying "Deploy GH Pages".
Done

2024-04-09 17:37 UTC, popescu-v commented on CONTRIBUTING.md
> +      - `git reset --hard main`
We avoid rebasing onto `main` so that we do not need to `git push -f dev`?

2024-04-09 17:39 UTC, popescu-v commented on tests/test_core.py
> +                        "additional_data_tables": (
These Python code reformattings were all caused by the `black` version updating, right?

2024-04-11 11:53 UTC, folmos-at-orange commented on tests/test_core.py
> +                        "additional_data_tables": (
Yes

2024-04-11 11:54 UTC, folmos-at-orange commented on CONTRIBUTING.md
> +      - `git reset --hard main`
No, this command will just make `dev` point to `main`. The push is still necessary.

2024-04-11 14:01 UTC, folmos-at-orange commented on CONTRIBUTING.md
> +      - `git reset --hard main`
And `--force` isn't necessary as we are adding a commit to the tip of the branch.

2024-04-11 14:06 UTC, popescu-v approved these changes
LGTM.

2024-04-11 14:09 UTC, merged