42 support sparse arrays in sklearn estimators
KhiopsML/khiops-python pull request #172
Opened 2024-04-03 17:58 UTC by popescu-v

2024-04-09 09:19 UTC, folmos-at-orange requested changes
A bit of refactoring is needed.

Merge paragraphs without comments or add a comment.

2024-04-09 09:19 UTC, folmos-at-orange commented on khiops/sklearn/tables.py
> +                    "sparse_matrix", sparse_matrix, "SciPy sparse matrix"
I'd put the `sp.spmatrix` instead of the string.

2024-04-09 09:19 UTC, folmos-at-orange commented on khiops/sklearn/tables.py
> +
I'd add a check that the matrix `dtype` is numeric.

2024-04-09 09:19 UTC, folmos-at-orange commented on khiops/sklearn/tables.py
> +        Adds metadata to each sparse variable
I'd add an empty line. I'm not sure is properly parsed if not.

2024-04-09 09:19 UTC, folmos-at-orange commented on khiops/sklearn/tables.py
> +        # For each variable, add metadata
Specify that the metadata is the `VarKey`

2024-04-09 09:19 UTC, folmos-at-orange commented on khiops/sklearn/tables.py
> +                            line += f"{variable_index + 1}: "
Add a header comment for the `else` branch.

2024-04-09 09:19 UTC, folmos-at-orange commented on khiops/sklearn/tables.py
> +                    output_sparse_matrix_stream.write(f"{line}\n")
I'd refactor this bit as `_write_sparse_block(row, stream)` and use it in both cases (with and without `y`)

2024-04-09 09:19 UTC, folmos-at-orange commented on tests/test_dataset_class.py
> +        iris = datasets.load_iris()
I'd put some missing values in this test.

2024-04-09 09:19 UTC, folmos-at-orange commented on tests/test_sklearn.py
>                  #   - To be implemented manually
No need of bullet points anymore.

2024-04-09 09:19 UTC, folmos-at-orange commented on khiops/sklearn/tables.py
> +    or (pandas.DataFrame, pandas.DataFrame)
Explain the types in the body of the docstring and make the header fit one line (eg. Table encapsulating the feature matrix `X` and target vector `y`)

2024-04-09 13:31 UTC, popescu-v commented on khiops/sklearn/tables.py
> +                )
I am expecting the labels to be array-like, if the features are array-like, or sparse.

2024-04-09 13:31 UTC, popescu-v commented on tests/test_dataset_errors.py
> +            "array-like or Pandas dataframe or Scipy sparse matrix",
Ok.

2024-04-09 13:32 UTC, popescu-v commented on khiops/sklearn/tables.py
> +class SparseTable(DatasetTable):
Ok.

2024-04-09 13:32 UTC, popescu-v commented on khiops/sklearn/tables.py
> +    sparse_matrix : `scipy.sparse.spmatrix`
`sparse_matrix` seems more explicit to me. `matrix` seems vague to me (do we mean NumPy matrix?).

2024-04-09 13:33 UTC, popescu-v commented on khiops/sklearn/tables.py
> +                    "sparse_matrix", sparse_matrix, "SciPy sparse matrix"
Ok.

2024-04-09 13:33 UTC, popescu-v commented on khiops/sklearn/tables.py
> +
Yes, good point! I'll add that.

2024-04-09 13:33 UTC, popescu-v commented on khiops/sklearn/tables.py
> +        Adds metadata to each sparse variable
Ok.

2024-04-09 13:34 UTC, popescu-v commented on khiops/sklearn/tables.py
> +                            line += f"{variable_index + 1}: "
Ok, right.

2024-04-09 13:34 UTC, popescu-v commented on khiops/sklearn/tables.py
> +                    output_sparse_matrix_stream.write(f"{line}\n")
Yes, +1.

2024-04-09 13:35 UTC, popescu-v commented on tests/test_dataset_class.py
> +        iris = datasets.load_iris()
> I'd put some missing values in this test.
Yes, ideally one should use a dataset which would fit a sparse representation from the outset.

2024-04-09 13:36 UTC, popescu-v commented on tests/test_dataset_class.py
> +        iris = datasets.load_iris()
> I'd also add a sklearn sample with a pipeline that generates a sparse feature matrix which can then be feeded to a `KhiopsClassifier`

Yes; this would be a bigger test, but why not? Like a vectorization before Khiops

2024-04-09 13:36 UTC, popescu-v commented on tests/test_sklearn.py
>                  #   - To be implemented manually
Ok.

2024-04-09 13:36 UTC, popescu-v commented on khiops/sklearn/tables.py
> +    or (pandas.DataFrame, pandas.DataFrame)
Ok for refactoring this.

2024-04-09 13:57 UTC, folmos-at-orange commented on tests/test_dataset_class.py
> +        iris = datasets.load_iris()
Using this maybe: https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html

2024-04-09 15:08 UTC, folmos-at-orange commented on khiops/sklearn/tables.py
> +                )
I think we should accept any `array-like` as `y`, independently of the feature matrix type.

2024-04-09 15:08 UTC, folmos-at-orange commented on khiops/sklearn/tables.py
> +    sparse_matrix : `scipy.sparse.spmatrix`
It is not vague, as it is _in_ the `SparseTable` class.

2024-04-09 15:08 UTC, folmos-at-orange commented on khiops/sklearn/tables.py
> +    sparse_matrix : `scipy.sparse.spmatrix`
Furthermore, we check the types.

2024-04-09 15:17 UTC, popescu-v commented on tests/test_dataset_errors.py
> +            "array-like or Pandas dataframe or Scipy sparse matrix",
Actually, instead of `sp.spmatrix` which uses `sp` which is our alias, one should write `scipy.sparse.spmatrix` throughout the docstrings or user-facing messages IMHO.

2024-04-09 15:18 UTC, popescu-v commented on khiops/sklearn/tables.py
> +                    "sparse_matrix", sparse_matrix, "SciPy sparse matrix"
... with the caveat that `sp` is our alias; hence, I would use `scipy.sparse.spmatrix` instead (see the comment above in this respect).

2024-04-09 15:19 UTC, popescu-v commented on tests/test_dataset_class.py
> +        iris = datasets.load_iris()
Yes, something along these lines.

2024-04-09 15:24 UTC, popescu-v commented on tests/test_dataset_errors.py
> +            "array-like or Pandas dataframe or Scipy sparse matrix",
Done. Also added link to scipy doc to `intersphinx_mapping` in `doc/conf.py`.

2024-04-09 15:25 UTC, popescu-v commented on khiops/sklearn/tables.py
> +class SparseTable(DatasetTable):
Done.

2024-04-09 15:26 UTC, popescu-v commented on khiops/sklearn/tables.py
> +    sparse_matrix : `scipy.sparse.spmatrix`
Done.

2024-04-09 15:29 UTC, popescu-v commented on khiops/sklearn/tables.py
> +                    "sparse_matrix", sparse_matrix, "SciPy sparse matrix"
Done.

2024-04-09 15:32 UTC, popescu-v commented on khiops/sklearn/tables.py
> +
Done.

2024-04-09 15:33 UTC, popescu-v commented on khiops/sklearn/tables.py
> +        Adds metadata to each sparse variable
Done.

2024-04-09 15:33 UTC, popescu-v commented on khiops/sklearn/tables.py
> +        # For each variable, add metadata
Done.

2024-04-09 15:46 UTC, popescu-v commented on khiops/sklearn/tables.py
> +                            line += f"{variable_index + 1}: "
Done.

2024-04-09 15:48 UTC, popescu-v commented on khiops/sklearn/tables.py
> +    or (pandas.DataFrame, pandas.DataFrame)
Done.

2024-04-09 16:05 UTC, popescu-v commented on khiops/sklearn/tables.py
> +                    output_sparse_matrix_stream.write(f"{line}\n")
Done.

2024-04-09 16:25 UTC, popescu-v commented on tests/test_sklearn.py
>                  #   - To be implemented manually
Done.

2024-04-09 17:31 UTC, popescu-v commented on khiops/sklearn/tables.py
> +                )
On second thought, this looks like a distinct feature to me: accepting `X` as a dataframe, and `y` as a numpy array. For this, we need to explicitly add relevant support to the `PandasTable` class. So, I would make this change in a different PR.

2024-04-10 08:36 UTC, folmos-at-orange commented on khiops/sklearn/tables.py
> +                )
Ok, could you please write it?

2024-04-10 15:11 UTC, popescu-v commented on tests/test_dataset_class.py
> +        iris = datasets.load_iris()
Done, with manually-created sparse data which also contains all-missing data rows.

2024-04-10 16:14 UTC, popescu-v commented on tests/test_dataset_class.py
> +        iris = datasets.load_iris()
Also added sparse 20newsgroups-based sample. Hence, this thread can be closed IMHO.

2024-04-11 07:39 UTC, folmos-at-orange commented on tests/test_dataset_class.py
> +        iris = datasets.load_iris()
The sample doesn't appear in the build documentation.

2024-04-11 07:48 UTC, popescu-v commented on tests/test_dataset_class.py
> +        iris = datasets.load_iris()
Ok. Done. This should be fixed now.

2024-04-11 09:12 UTC, folmos-at-orange approved these changes
Minor details. You may merge after resolving them.

2024-04-11 09:12 UTC, folmos-at-orange commented on khiops/samples/samples_sklearn.py
> +
This should be added to the `samples_generation` script. In the header creation code.

2024-04-11 09:12 UTC, folmos-at-orange commented on khiops/samples/samples_sklearn.py
> +
Eliminate all blank lines in this block (ie. make a paragraph)

2024-04-11 09:12 UTC, folmos-at-orange commented on khiops/samples/samples_sklearn.py
> +    # HashingVectorizer has relatively low memory footprint
I think this is irrelevant for the example. I'd eliminate it.

2024-04-11 09:12 UTC, folmos-at-orange commented on khiops/sklearn/tables.py
> +        variables = dictionary.variables[:]
I think this variable isn't very useful. I'd just directly `dictionary.variables`.

2024-04-11 09:12 UTC, folmos-at-orange commented on khiops/sklearn/tables.py
> +        variable_block.name = "SparseVariables"
Paragraph without comment.

2024-04-11 09:12 UTC, folmos-at-orange commented on tests/test_dataset_class.py
> +            # handle missing values
This comment is irrelevant now ?

2024-04-11 09:31 UTC, popescu-v commented on tests/test_dataset_class.py
> +            # handle missing values
No, it is relevant; this is the reason why we needed to implement `self._load_khiops_sparse_file`.

2024-04-11 09:31 UTC, popescu-v commented on khiops/sklearn/tables.py
> +        variable_block.name = "SparseVariables"
OK, I'll add one.

2024-04-11 09:33 UTC, popescu-v commented on khiops/sklearn/tables.py
> +        variables = dictionary.variables[:]
I think it is, because in the loop that iterates over the variables we do `dictionary.remove_variable(variable.name)`, in order to add each relevant variable to the sparse variable block. And we do not want the iterator to be a "moving target".

2024-04-11 09:33 UTC, popescu-v commented on khiops/samples/samples_sklearn.py
> +    # HashingVectorizer has relatively low memory footprint
OK. I will remove the second comment line (about the `HashingVectorizer`).

2024-04-11 09:33 UTC, popescu-v commented on khiops/samples/samples_sklearn.py
> +
Ok.

2024-04-11 09:34 UTC, popescu-v commented on khiops/samples/samples_sklearn.py
> +
Ok.

2024-04-11 10:08 UTC, popescu-v commented on khiops/samples/samples_sklearn.py
> +
Done.

2024-04-11 10:09 UTC, popescu-v commented on khiops/samples/samples_sklearn.py
> +
Done.

2024-04-11 10:09 UTC, popescu-v commented on khiops/sklearn/tables.py
> +        variable_block.name = "SparseVariables"
Done.

2024-04-11 11:40 UTC, folmos-at-orange commented on tests/test_dataset_class.py
> +            # handle missing values
But you are not loading a svm light file anymore.

2024-04-11 11:51 UTC, folmos-at-orange requested changes
Small optimization.

2024-04-11 11:51 UTC, folmos-at-orange commented on khiops/sklearn/tables.py
> +        variables = dictionary.variables[:]
ok, then i'd iterate over `variable_names`. And the line creating the list i'd put it at the top of the loop (more locality)

2024-04-11 11:51 UTC, folmos-at-orange commented on khiops/sklearn/tables.py
> +        stream.write(f"{line.strip()}\n")
Since this code is a critical part I'd eliminate the `line` variable and write directly to the stream each part of the line.

2024-04-11 11:52 UTC, folmos-at-orange commented on khiops/sklearn/tables.py
> +        stream.write(f"{line.strip()}\n")
And I think that in the case of an empty row you can just put an empty sparse field instead of filling all columns with empty values.

2024-04-11 11:56 UTC, popescu-v commented on tests/test_dataset_class.py
> +            # handle missing values
Ok, I'll remove.

2024-04-11 12:41 UTC, popescu-v commented on khiops/sklearn/tables.py
> +        variables = dictionary.variables[:]
IMHO, we need to iterate over the variables themselves, in order to be able to easily add them to the sparse variable block.

2024-04-11 12:41 UTC, popescu-v commented on khiops/sklearn/tables.py
> +        variables = dictionary.variables[:]
But OK for more locality by moving next to the loop the line which creates the variable list.

2024-04-11 12:46 UTC, popescu-v commented on khiops/sklearn/tables.py
> +        stream.write(f"{line.strip()}\n")
> Since this code is a critical part I'd eliminate the `line` variable and write directly to the stream each part of the line.

OK.

2024-04-11 12:47 UTC, popescu-v commented on khiops/sklearn/tables.py
> +        stream.write(f"{line.strip()}\n")
> And I think that in the case of an empty row you can just put an empty sparse field instead of filling all columns with empty values.

Currently, we add all variables as having missing values. I think we could just add one (let us say the first variable). But I think we need at least one.

2024-04-11 14:00 UTC, popescu-v commented on khiops/sklearn/tables.py
> +        stream.write(f"{line.strip()}\n")
Done. Wrote to the stream directly.

2024-04-11 14:17 UTC, folmos-at-orange commented on khiops/sklearn/tables.py
> +        variables = dictionary.variables[:]
note that `remove_variable` returns the variable object, that's why it is easier to loop over the names.

2024-04-11 14:50 UTC, popescu-v commented on khiops/sklearn/tables.py
> +        variables = dictionary.variables[:]
Ok, change done accordingly.

2024-04-11 15:21 UTC, folmos-at-orange approved these changes

2024-04-11 17:30 UTC, merged