171 implement multi table helper functions
KhiopsML/khiops-python pull request #180
Opened 2024-04-15 15:05 UTC by folmos-at-orange

2024-07-05 12:01 UTC, popescu-v commented on tests/test_helper_functions.py
> +        with contextlib.ExitStack() as exit_stack:
We could have used 4 context managers here, either nested or enumerated, but this would have entailed more nesting levels and been less readable, right?

2024-07-05 12:02 UTC, popescu-v commented on tests/test_helper_functions.py
> +CLIENTS_CSV = """
I would have used these as file-based fixtures (as this is done in other places in the test suite), rather than hard-coded in the testing code itself.

2024-07-05 12:09 UTC, folmos-at-orange commented on khiops/utils/dataset.py
> +        ]
Backwards compatibility.

2024-07-05 12:10 UTC, folmos-at-orange commented on tests/test_helper_functions.py
> +CLIENTS_CSV = """
This has better locality, and you can see in the code the (rather small) test dataset. So this is clearer.

2024-07-29 13:22 UTC, popescu-v commented on khiops/utils/dataset.py
> +        ]
Ok.

2024-07-29 13:24 UTC, popescu-v commented on tests/test_helper_functions.py
> +CLIENTS_CSV = """
Yes, but this breaks homogeneity with the other fixtures used in the code base IMHO. And then, each update to the code would update this whole (biggish) file. Separating the fixtures would allow to focus on the code itself during maintenance IMHO.

2024-08-05 14:16 UTC, folmos-at-orange commented on khiops/utils/dataset.py
> +                self.target_column_type = "Categorical"
In the end I eliminated the state `target_column_type` completely.

2024-08-05 14:28 UTC, popescu-v commented on doc/samples/samples_sklearn.rst
> +        categories = ["comp.graphics", "sci.space", "misc.forsale", "alt.atheism"]
Oh, Ok. Then, also change the comment above: s/load 3 classes/load 4 classes/.

2024-08-05 14:29 UTC, popescu-v commented on khiops/samples/samples_sklearn.py
> +    categories = ["comp.graphics", "sci.space", "misc.forsale", "alt.atheism"]
Ok, +1. This is on the `.py` file but OK.

2024-08-05 14:31 UTC, popescu-v commented on khiops/samples/samples_sklearn.py
> +        No intermediary dense data is used by Khiops because it supports sparse data
Yes, but my expectation is that this is the whole point of sparse support. The contrary would seem surprising to me!

2024-08-05 14:34 UTC, popescu-v commented on khiops/utils/dataset.py
> +        parent_table, child_table = relation[:2]
Ok, I hear your argument.

2024-08-05 14:35 UTC, popescu-v commented on khiops/utils/dataset.py
> +        **Deprecated:** Will be removed in khiops-python 11.
Ok; meanwhile, I would still put just "khiops" in the (user-facing) docstring.

2024-08-05 14:36 UTC, popescu-v commented on khiops/utils/dataset.py
> -            self._init_tables_from_dataframe(
Ok, right.

2024-08-05 14:38 UTC, popescu-v commented on .pre-commit-config.yaml
> +        name: gh-actions
Well, it seems a bit misleading to keep it here me IMHO (unused code, basically). Should we add a custom action, nothing would prevent one from copying this snippet from the `khiops` repo, would it?

2024-08-05 14:39 UTC, popescu-v commented on khiops/utils/dataset.py
> +                self.target_column_type = "Numerical"
Ok.

2024-08-05 14:40 UTC, popescu-v commented on khiops/utils/dataset.py
> +            str(self.data_source.dtypes).replace("\n", ", ")[:-16].replace("    ", ":")
In my book, this is a small, local change. I am not sure it's worthy of a dedicated issue... Unless this would involve revisiting the whole code base from this angle.

2024-08-05 14:42 UTC, popescu-v commented on khiops/utils/dataset.py
> +        output_dataframe = pd.DataFrame(self.data_source.copy())
Ok, until the optimization lands, could one have just one small comment in this respect?

2024-08-05 14:44 UTC, popescu-v commented on khiops/utils/dataset.py
> -            if variable_name != target_column_variable_name:
Ok, so basically now there is no target variable unless needed. Good. But in this case, I am not sure I see the guarantee that, when target variable is added, this done *after* the sparse block creation...

2024-08-05 14:45 UTC, popescu-v commented on khiops/utils/dataset.py
> +            kh.export_dictionary_as_json(tmp_kdic_path, tmp_kdicj_path)
Why is it more so than the other mocks? The infrastructure is there, right?

2024-08-05 14:45 UTC, popescu-v commented on tests/test_sklearn.py
> +            print("")
In that case, I would print something else than the empty string, e.g. `"=="` or something alike.

2024-08-05 14:46 UTC, popescu-v commented on tests/test_dataset_errors.py
> +        bad_key = [AnotherType()]
I think it's worth it, as IMHO readability is improved.

2024-08-05 14:53 UTC, popescu-v commented on tests/test_helper_functions.py
> +CLIENTS_CSV = """
I agree with your last point (fixtures as close to the test). My only caveat with putting fixtures and code in the same file is that the different lifecycles of these parts are conflated in the same file. And this could hinder the Git log inspections in the long run I guess.

2024-08-05 15:41 UTC, folmos-at-orange commented on khiops/samples/samples_sklearn.py
> +        No intermediary dense data is used by Khiops because it supports sparse data
Ok

2024-08-05 15:42 UTC, folmos-at-orange commented on khiops/utils/dataset.py
> +        **Deprecated:** Will be removed in khiops-python 11.
Everywhere is written as `khiops-python` (grep it). I'll keep this until we decide what to do.

2024-08-05 15:43 UTC, folmos-at-orange commented on .pre-commit-config.yaml
> +        name: gh-actions
It cost nothing, and there is no risk.

2024-08-05 15:46 UTC, folmos-at-orange commented on khiops/utils/dataset.py
> -            if variable_name != target_column_variable_name:
It is done after the block creation, because `SparseTable` creates its dictionary. `Dataset` recovers it and adds a target variable.

2024-08-05 15:47 UTC, folmos-at-orange commented on khiops/utils/dataset.py
> +            kh.export_dictionary_as_json(tmp_kdic_path, tmp_kdicj_path)
It is because we call two times the same function. Our custom mocking framework does not support that, and develop it would take a lot of time.

2024-08-05 15:48 UTC, folmos-at-orange commented on tests/test_sklearn.py
> +            print("")
No, the empty line is fine

2024-08-05 15:50 UTC, folmos-at-orange commented on tests/test_dataset_class.py
> +            print(data_type)
It is not there anymore.

2024-08-05 15:51 UTC, folmos-at-orange commented on tests/test_dataset_class.py
> +            assert schema == "snowflake", f"'schema' should be 'snowflake' no {schema}"
Done

2024-08-05 15:51 UTC, folmos-at-orange commented on tests/test_dataset_class.py
>          )
Done

2024-08-05 15:51 UTC, folmos-at-orange commented on tests/test_dataset_errors.py
> +        bad_key = [AnotherType()]
`AnotherType()` is quite readable.

2024-08-05 15:52 UTC, folmos-at-orange commented on tests/test_helper_functions.py
> +CLIENTS_CSV = """
It is a small dataset. And the alternative would require **several** files, it is not worth it.

2024-08-08 15:09 UTC, popescu-v commented on khiops/utils/dataset.py
> +        **Deprecated:** Will be removed in khiops-python 11.
Ok for now. These will all be changed when addressing issue https://github.com/KhiopsML/khiops-python/issues/227.

2024-08-08 15:11 UTC, popescu-v commented on .pre-commit-config.yaml
> +        name: gh-actions
IMHO, code should be there for a reason; otherwise, having the code here seems misleading to me: new developers might start looking for extant actions in the code base, after taking a look at the pre-commit hook file.

2024-08-08 15:19 UTC, popescu-v commented on khiops/utils/dataset.py
> -            if variable_name != target_column_variable_name:
Yeah ok, I got it, it's done afterwards when `_init_target_column` is called.

2024-08-08 15:21 UTC, popescu-v commented on tests/test_sklearn.py
> +            print("")
Ok.

2024-08-08 15:59 UTC, popescu-v commented on khiops/utils/dataset.py
> +            kh.export_dictionary_as_json(tmp_kdic_path, tmp_kdicj_path)
Yeah, I think I get it:
- in the estimators' methods we create `Dataset` which creates a `FileTable`, whereby `export_dictionary_as_json` is called;
- then, `read_dictionary_file` (which is not mocked itself) is called once in the estimators `_fit*` methods, whence calling `export_dictionary_as_json` once more in case of `.kdic`.

We need to be able to index same-method mocks (for the same estimator method) by their calling order IMHO.

2024-08-08 16:33 UTC, popescu-v commented on khiops/utils/dataset.py
> +    """Translates a numpy type to a Khiops dictionary dtype
I don't see the modification here...

2024-08-08 16:43 UTC, popescu-v commented on khiops/utils/dataset.py
> +            str(self.data_source.dtypes).replace("\n", ", ")[:-16].replace("    ", ":")
Ok. Issue made: https://github.com/KhiopsML/khiops-python/issues/229. Closing these threads in this PR.

2024-08-08 17:20 UTC, popescu-v commented on khiops/samples/samples_sklearn.py
> +            os.mkdir(results_dir)
Use `os.makedirs(..., exist_ok=True)` for more conciseness and consistency with the remainder of the samples.

2024-08-08 17:23 UTC, popescu-v commented on khiops/samples/samples_sklearn.py
> +    ).squeeze("columns")
Continue existing comment with something like: `; make sure `y` is a Pandas series`

2024-08-08 17:27 UTC, popescu-v commented on khiops/sklearn/estimators.py
> +    ds_dictionary,
I'm not sure `ds_` is more readable than `dataset_`; I would have kept it as it was.

2024-08-08 17:28 UTC, popescu-v commented on khiops/sklearn/estimators.py
> +    ds_variable_names = set(var.name for var in ds_dictionary.variables)
Use `{...}` instead of `set(...)`: more Pythonic, more concise.

2024-08-08 17:31 UTC, popescu-v commented on khiops/sklearn/estimators.py
> +                f"Unknown label type '{ds.target_column.dtype}'. "
s/Unknown label type/Unknown target type/ to be consistent (wrt. e.g. "Target vector" just above).

2024-08-20 16:45 UTC, popescu-v commented on khiops/sklearn/estimators.py
> +                )
AFAIU, what we can basically have here is `model_var` being "Numerical" or "Time"/"Date"/"Timestamp", or relational types ("Table", "Entity") or a "Structure" type and `ds_var` being "Categorical" or a type among "Time"/"Date"/"Timestamp", or also a relational type, or a Structure type, but different from the type of `model_var`.

On one hand, if `model_var` is Numerical and `ds_var` is Categorical, then it cannot be coerced to `"Numerical"`, ok.

However, I am less certain about the Time/Date/Timestamp types: there is no coercion possible here? And also between Structure and Table?

Hence, I would go for a more explicit error message in this respect (by adding the "cannot be coerced" parts where relevant), and perhaps some comments in the code stating more explicitly what should happen in these cases.

2024-08-20 16:49 UTC, popescu-v commented on khiops/sklearn/estimators.py
> +        if ds.target_column is not None:
Add comment like: "All targets should be defined".

2024-08-20 16:49 UTC, popescu-v commented on khiops/sklearn/estimators.py
> +        ds : `Dataset`
`ds` vs `dataset`: I'm not sure the former is more readable than the latter (see other comments in this respect).

2024-08-20 16:52 UTC, popescu-v commented on khiops/sklearn/estimators.py
> +                *Deprecated input modes* (will be removed in khiops-python 11):
Why a TAB here? I would have expected this text to be aligned to the text above.

2024-08-20 16:54 UTC, popescu-v commented on khiops/sklearn/estimators.py
> +                *Deprecated input modes* (will be removed in khiops-python 11):
Why the TAB here? (See similar comment above in a similar context)

2024-08-20 17:04 UTC, popescu-v commented on khiops/sklearn/estimators.py
> +                  parameter.
Why the TAB here?

2024-08-20 17:08 UTC, popescu-v commented on khiops/sklearn/estimators.py
> +        # pylint: disable=unused-argument
Rather than giving hints to PyLint, I would just mark the dataset parameters as unused:
```python
def _transform_prepare_deployment_model_for_predict(self, _):
    return self.model_.copy()
```

or, to be more explicit:

```python
def _transform_prepare_deployment_model_for_predict(self, _ds):
    return self.model_.copy()
```

This should make PyLint happy AFAIK.

2024-08-20 17:09 UTC, popescu-v commented on khiops/sklearn/estimators.py
> +                  parameter.
Why the TAB here?

2024-08-20 17:10 UTC, popescu-v commented on khiops/sklearn/estimators.py
> +                    - str: A path to a data table file for file-based ``dict`` dataset
Why TAB here?

2024-08-20 17:14 UTC, popescu-v commented on khiops/sklearn/estimators.py
> +        ), "Target variable name has not been set"
`model_main_dictionary_name_` vs "Target variable name"?

2024-08-20 17:14 UTC, popescu-v commented on khiops/sklearn/estimators.py
> +        # Remove the target variabale if it is not present in the input dataset
s/target variabale/target variable/

2024-08-20 17:22 UTC, popescu-v commented on khiops/sklearn/estimators.py
> +        if self.model_target_variable_name_ not in list(ds.main_table.column_ids):
I would use `ds.main_table.column_ids.tolist()` instead of `list(ds.main_table.column_ids)`, to emphasize that we are dealing with a NumPy array here. In this case, the warning also disappears.

2024-08-20 17:24 UTC, popescu-v commented on khiops/sklearn/estimators.py
> +                *Deprecated input modes* (will be removed in khiops-python 11):
Why the extra indentation here?

2024-08-20 17:26 UTC, popescu-v commented on khiops/sklearn/estimators.py
> +                *Deprecated input modes* (will be removed in khiops-python 11):
Why the extra indentation?

2024-08-20 17:28 UTC, popescu-v commented on khiops/sklearn/estimators.py
> +                *Deprecated input modes* (will be removed in khiops-python 11):
Extra indentation?

2024-08-20 17:29 UTC, popescu-v commented on khiops/sklearn/estimators.py
> +        if self.model_target_variable_name_ not in list(ds.main_table.column_ids):
`.tolist()` instead of `list()` (see above)?

2024-08-20 17:29 UTC, popescu-v commented on khiops/sklearn/estimators.py
> +                - tuple: A pair (``path_to_file``, ``separator``).
Indentations?

2024-08-20 17:31 UTC, popescu-v commented on khiops/sklearn/estimators.py
> +        if self.model_target_variable_name_ not in list(ds.main_table.column_ids):
`.tolist()` instead of `list()`?

2024-08-20 18:11 UTC, popescu-v commented on khiops/utils/dataset.py
> +            )
I think this two `if`s can be conflated, as the logic seems the same.

2024-08-20 18:14 UTC, popescu-v commented on khiops/utils/dataset.py
> +                    f"Column names: {list(self.main_table.column_ids)}"
update to "is already present in the main table, whose column names are: ..."

2024-08-20 18:16 UTC, popescu-v commented on khiops/utils/dataset.py
> +                    f"not present in columns '{self.main_table.column_ids}'"
I would update to "not present in main table columns '...'".

2024-08-20 18:17 UTC, popescu-v commented on khiops/utils/dataset.py
>          A dataset is in memory if it is constituted either of only pandas.DataFrame
s/is in memory/is in-memory/ for consistency with the line just above.

2024-08-20 18:21 UTC, popescu-v commented on khiops/utils/dataset.py
> +    def create_table_files_for_khiops(self, out_dir, sort=True):
I would call this `output_dir` as it is a parameter of a "public" method.

2024-08-21 13:53 UTC, popescu-v commented on khiops/utils/helpers.py
> +    The dataset may be multi-table or not. If it is monotable the key of the only key
Rephrase "the key of the only key must be specified" to something like "the key of the only table must be specified".

2024-08-21 13:53 UTC, popescu-v commented on khiops/utils/helpers.py
> +    """Sorts a dataset by its table key columns
I would also state that, at each table level, mergesort is performed, for stability.

2024-08-21 14:19 UTC, popescu-v commented on khiops/utils/helpers.py
> +def _sort_file_table(table, sep, header, output_dir):
I would explain in the docstring that for file-based datasets, sorting is delegated to the Khiops binaries (or engine?). I would also discuss whether the Khiops-based sorting is isofunctional to the mergesort used on dataframe tables. As a user, I would expect it to be:
- I first build a dataset based on a Dataframe and sort it with this helper;
- then, to gain in efficiency (memory efficiency, at least), I switch to a file-based dataset and sort it with this helper (thus delegating the sorting to Khiops itself).
- I would expect the results to be identical; if this is not the case, I would state it the docstring from the outset.

2024-08-21 14:22 UTC, popescu-v commented on khiops/utils/helpers.py
> +        The proportion of the dataset (between 0.0 and 1.0) to be include in the test
s/to be include/to be included/
OR
s/to be include/to include/

2024-08-21 14:28 UTC, popescu-v commented on khiops/utils/helpers.py
> +            train_ds, test_ds = _train_test_split_in_memory_dataset(
I would have `_train_test_split_in_memory_dataset` return a tuple of the same size, irrespective of the `target_column` being `None` or not, and delegate the `train_|test_target_column` assignment to that method.

2024-08-21 14:33 UTC, popescu-v commented on khiops/utils/helpers.py
> +                ds.main_table.data_source, test_size=test_size, **split_params
Couldn't we give empty-array `target_column` to `train_test_split` here? If the result of the split yields empty `train_|test_target_column`s, then we could reassign these to `None`; thus we would call `train_test_split` only once, thus simplifying the code, right?

2024-08-21 15:25 UTC, popescu-v commented on tests/test_dataset_class.py
> +        np.random.seed(31416)
Add comment like
`# Set reproducible initial random state` or something like that.
On the other hand, setting the seed this way is documented as "legacy": https://numpy.org/doc/stable/reference/random/generated/numpy.random.seed.html

Nowadays, we would use a generator: something like:
```python
random_generator = np.random.Generator(np.random.PCG64(seed=31416))
# ...
# instead of np.random.randint(x, y, z)
random_generator.integers(x, y, z)
# instead of np.random.rand(1, 20)[0]
random_generator.random(20)
# instead of np.random.choice(["a", "b", "c", "d"], 20)
random_generator.choice(["a", "b", "c", "d"], 20)
```

Thus, global state is avoided and Pythonic OOP API is used.

2024-08-21 15:27 UTC, popescu-v commented on tests/test_dataset_class.py
> +                warnings.warn("Changed field `Recomended IND` to avoid a Khiops bug")
s/Recomended/Recommended/

2024-08-21 15:28 UTC, popescu-v commented on tests/test_dataset_class.py
> +            #  - the type of "Date" from Timestamp to "Date" as Khiops can detect it
I would rewrite thus:
`#    - the type of "Date" from Timestamp to Date, so that Khiops can detect it`

2024-08-21 15:32 UTC, popescu-v commented on tests/test_dataset_class.py
> +                # shutil.copy(ds.secondary_tables[3].data_source, "./test.txt")
This debugging code should be removed IMHO.

2024-08-21 15:33 UTC, popescu-v commented on tests/test_dataset_class.py
> +        ref_table_names = set(
Use `{...}` instead of `set(...)`: more concise IMHO.

2024-08-21 15:33 UTC, popescu-v commented on tests/test_dataset_class.py
> +        out_table_names = set(dictionary.name for dictionary in out_domain.dictionaries)
`{...}` instead of `set()`

2024-08-21 15:34 UTC, popescu-v commented on tests/test_dataset_class.py
> +        # Check that the main table is root iff for multitable
I would rephrase to something like:
```python
# Check that the main table is root in the multitable case
```

2024-08-23 08:32 UTC, folmos-at-orange commented on khiops/sklearn/estimators.py
> +                f"Unknown label type '{ds.target_column.dtype}'. "
The parlance in sklearn is _label_.

2024-08-23 08:35 UTC, folmos-at-orange commented on khiops/sklearn/estimators.py
> +        if ds.target_column is not None:
Ok

2024-08-23 08:38 UTC, folmos-at-orange commented on khiops/sklearn/estimators.py
> +    ds_dictionary,
Normally I'd use a long name, but the dataset is an ubiquitous object used many times in the module. The notation is clear (as it is `df` for data frames) and I kept the long names in functions.

2024-08-23 08:38 UTC, folmos-at-orange commented on khiops/sklearn/estimators.py
> +    ds_variable_names = set(var.name for var in ds_dictionary.variables)
Ok

2024-08-23 08:39 UTC, folmos-at-orange commented on khiops/utils/dataset.py
>          A dataset is in memory if it is constituted either of only pandas.DataFrame
Ok

2024-08-23 09:24 UTC, folmos-at-orange commented on khiops/sklearn/estimators.py
> +                f"Unknown label type '{ds.target_column.dtype}'. "
Done

2024-08-23 09:25 UTC, folmos-at-orange commented on khiops/sklearn/estimators.py
> +        if ds.target_column is not None:
Added a header comment to if/else block.

2024-08-23 11:49 UTC, folmos-at-orange commented on khiops/utils/dataset.py
> +    """Translates a numpy type to a Khiops dictionary dtype
Now it is done.

2024-08-23 11:59 UTC, folmos-at-orange commented on khiops/utils/dataset.py
> +        output_dataframe = pd.DataFrame(self.data_source.copy())
In second thought given that we sort by default we need to copy to not change the data source.

2024-08-23 12:01 UTC, folmos-at-orange commented on khiops/utils/dataset.py
>          A dataset is in memory if it is constituted either of only pandas.DataFrame
Done

2024-08-23 12:04 UTC, folmos-at-orange commented on khiops/utils/helpers.py
> +    """Sorts a dataset by its table key columns
Ok & Done

2024-08-23 12:04 UTC, folmos-at-orange commented on khiops/utils/helpers.py
> +    The dataset may be multi-table or not. If it is monotable the key of the only key
Ok & done.

2024-08-23 12:08 UTC, folmos-at-orange commented on khiops/utils/helpers.py
> +def _sort_file_table(table, sep, header, output_dir):
The objective here is not having a generic sorter, only a helper function to ease the use of Khiops.

The engine used is of little interest for the user because it is an implementation detail. Nonetheless I added a "Notes" section indicating the choices.

2024-08-23 12:09 UTC, folmos-at-orange commented on tests/test_dataset_class.py
> +class DatasetInputOutputConsistency(unittest.TestCase):
I would not put that constraint in test-case classes. Also, this change is not in this PR!

2024-08-23 12:47 UTC, folmos-at-orange commented on khiops/utils/dataset.py
> +        )
Ok & Done

2024-08-23 12:48 UTC, folmos-at-orange commented on khiops/utils/dataset.py
> +            )
No, because their message is different.

2024-08-23 12:49 UTC, folmos-at-orange commented on khiops/utils/dataset.py
> +                    f"Column names: {list(self.main_table.column_ids)}"
Too verbose.

2024-08-23 12:52 UTC, folmos-at-orange commented on khiops/utils/dataset.py
> +                    f"not present in columns '{self.main_table.column_ids}'"
Ok, and I uniformize it like the message above.

2024-08-23 12:53 UTC, folmos-at-orange commented on khiops/utils/dataset.py
> +    def create_table_files_for_khiops(self, out_dir, sort=True):
is public but only for us, this is fine.

2024-08-23 12:57 UTC, folmos-at-orange commented on khiops/sklearn/estimators.py
> +    ds_variable_names = set(var.name for var in ds_dictionary.variables)
Done

2024-08-23 12:58 UTC, folmos-at-orange commented on khiops/sklearn/estimators.py
> +                )
Ok, but this is for an issue.

2024-08-23 13:19 UTC, popescu-v commented on khiops/utils/dataset.py
> +            )
Yes, but why not have a conflated message like:

```python
raise TypeError(
    type_error_message("y", y, "array-like")
    + " (X's tables are of type numpy.ndarray"
    + " or scipy.sparse.spmatrix or pandas.DataFrame)"
)
```

2024-08-23 13:23 UTC, popescu-v commented on khiops/utils/dataset.py
> +                    f"Column names: {list(self.main_table.column_ids)}"
> Too verbose. This is enough to diagnose any problem.

I'm not sure it would be enough for a novice user. How about s/Column names:/Main table's column names:/ (not too much verbosity added IMHO)?

2024-08-23 13:27 UTC, folmos-at-orange commented on khiops/utils/helpers.py
> +            train_ds, test_ds = _train_test_split_in_memory_dataset(
No, because it would'n have the same behavior as `train_test_split` which returns differently sized tuples (or iterables) depending on its input.

2024-08-23 13:31 UTC, folmos-at-orange commented on khiops/utils/helpers.py
> +                ds.main_table.data_source, test_size=test_size, **split_params
I think this is not possible because `train_test_split` would not accept `None` or an empty array as parameters.

2024-08-23 13:33 UTC, folmos-at-orange commented on khiops/utils/dataset.py
> +            )
The message is less clear that way.

2024-08-23 13:34 UTC, popescu-v commented on khiops/utils/helpers.py
> +def _sort_file_table(table, sep, header, output_dir):
Ok. To me, it would suffice to say that sorting behaves similarly, whether in-memory or file-based dataset are sorted.

2024-08-23 13:36 UTC, popescu-v commented on tests/test_dataset_class.py
> +class DatasetInputOutputConsistency(unittest.TestCase):
Before this change, the `Tests` suffix was part of the testcase class name. This change removed the suffix. I propose to put it back and to thus change only the prefix of the testcase class name.

2024-08-23 13:38 UTC, folmos-at-orange commented on khiops/sklearn/estimators.py
> +        # pylint: disable=unused-argument
Ok & Done.

2024-08-23 13:39 UTC, folmos-at-orange commented on khiops/sklearn/estimators.py
> +        ), "Target variable name has not been set"
Ok & Done.

2024-08-23 13:42 UTC, folmos-at-orange commented on khiops/sklearn/estimators.py
> +        if self.model_target_variable_name_ not in list(ds.main_table.column_ids):
Ok & Done.

2024-08-23 13:43 UTC, folmos-at-orange commented on khiops/sklearn/estimators.py
> +        if self.model_target_variable_name_ not in list(ds.main_table.column_ids):
OK & done

2024-08-23 13:45 UTC, folmos-at-orange commented on khiops/utils/helpers.py
> +    kh.deploy_model(
Ok, added a comment.

2024-08-23 13:47 UTC, folmos-at-orange commented on .pre-commit-config.yaml
> +        name: gh-actions
It is not that misleading. Again it is of little risk.

2024-08-23 13:48 UTC, folmos-at-orange commented on khiops/utils/helpers.py
> +        *Only for file datasets:* The output directory for the sorted files.
Ok & Done.

2024-08-23 14:04 UTC, folmos-at-orange commented on khiops/sklearn/estimators.py
> +        if self.model_target_variable_name_ not in list(ds.main_table.column_ids):
Reverted: `tolist()` is not always available depending of the type of the table. `list` always work.

Reverted below as well.

2024-08-23 16:07 UTC, folmos-at-orange commented on khiops/samples/samples_sklearn.py
> +    ).squeeze("columns")
Ok & Done

2024-08-23 16:32 UTC, folmos-at-orange commented on khiops/sklearn/estimators.py
> +                *Deprecated input modes* (will be removed in khiops-python 11):
Ok & reindented properly

2024-08-23 16:32 UTC, folmos-at-orange commented on khiops/sklearn/estimators.py
> +                *Deprecated input modes* (will be removed in khiops-python 11):
Ok & reindented.

2024-08-23 16:33 UTC, folmos-at-orange commented on khiops/sklearn/estimators.py
> +                  parameter.
Ok & reindented.

2024-08-23 16:33 UTC, folmos-at-orange commented on khiops/sklearn/estimators.py
> +                  parameter.
Ok and reindented.

2024-08-23 16:33 UTC, folmos-at-orange commented on khiops/sklearn/estimators.py
> +                    - str: A path to a data table file for file-based ``dict`` dataset
Ok and reindented.

2024-08-23 16:33 UTC, folmos-at-orange commented on khiops/sklearn/estimators.py
> +                *Deprecated input modes* (will be removed in khiops-python 11):
Ok & reindented.

2024-08-23 16:33 UTC, folmos-at-orange commented on khiops/sklearn/estimators.py
> +                *Deprecated input modes* (will be removed in khiops-python 11):
Ok & reindented.

2024-08-23 16:34 UTC, folmos-at-orange commented on khiops/sklearn/estimators.py
> +                *Deprecated input modes* (will be removed in khiops-python 11):
Ok & reindented.

2024-08-23 16:34 UTC, folmos-at-orange commented on khiops/sklearn/estimators.py
> +                - tuple: A pair (``path_to_file``, ``separator``).
Ok & reindented.

2024-08-23 18:56 UTC, folmos-at-orange commented on khiops/utils/dataset.py
> +    def create_table_files_for_khiops(self, out_dir, sort=True):
But Ok & Done

2024-08-23 18:57 UTC, folmos-at-orange commented on khiops/utils/helpers.py
> +        The proportion of the dataset (between 0.0 and 1.0) to be include in the test
Ok & Done

2024-08-23 19:06 UTC, folmos-at-orange commented on tests/test_dataset_class.py
> +            #  - the type of "Date" from Timestamp to "Date" as Khiops can detect it
It is not because to make Khiops detect it, it is because it detects it as `Date`.

2024-08-23 19:07 UTC, folmos-at-orange commented on tests/test_dataset_class.py
> +                # shutil.copy(ds.secondary_tables[3].data_source, "./test.txt")
Ok & Done

2024-08-23 19:07 UTC, folmos-at-orange commented on tests/test_dataset_class.py
> +        ref_table_names = set(
Ok & Done

2024-08-23 19:08 UTC, folmos-at-orange commented on tests/test_dataset_class.py
> +        out_table_names = set(dictionary.name for dictionary in out_domain.dictionaries)
Ok & Done.

2024-08-23 19:11 UTC, folmos-at-orange commented on tests/test_dataset_class.py
> +        # Check that the main table is root iff for multitable
Rephrased similarly but more clear.

2024-08-23 19:21 UTC, folmos-at-orange commented on khiops/utils/dataset.py
> +            )
Refactored to have particular message for each case

2024-08-26 09:02 UTC, popescu-v commented on khiops/sklearn/estimators.py
> +    ds_dictionary,
Ok for `dataset` in the public API (signatures), vs. `ds` in library code.

2024-08-26 09:05 UTC, popescu-v commented on khiops/sklearn/estimators.py
> +        if self.model_target_variable_name_ not in list(ds.main_table.column_ids):
Ok, I got it.

2024-08-26 09:07 UTC, popescu-v commented on khiops/utils/helpers.py
> +            train_ds, test_ds = _train_test_split_in_memory_dataset(
Ok, got it; we want this to behave similarly to sklearn's `train_test_split` method.

2024-08-26 09:08 UTC, popescu-v commented on khiops/utils/helpers.py
> +                ds.main_table.data_source, test_size=test_size, **split_params
Yes, I got it (see also above).

2024-08-26 09:19 UTC, popescu-v commented on tests/test_dataset_class.py
> +            #  - the type of "Date" from Timestamp to "Date" as Khiops can detect it
Ok, right. Then, how about 
```python
#     - the type of "Date" from Timestamp to Date, the type Khiops detects
```
or something in that vein. The currrent phrasing seems unclear to me.

2024-08-26 09:25 UTC, popescu-v commented on khiops/utils/dataset.py
> +        output_dataframe = pd.DataFrame(self.data_source.copy())
Ok, closing this now.

2024-08-26 09:43 UTC, popescu-v commented on khiops/samples/samples_sklearn.py
> +    ).squeeze("columns")
Add comment `# To ensure Pandas series`

2024-08-26 09:46 UTC, popescu-v commented on khiops/sklearn/estimators.py
> +                f"Unknown label type '{ds.target_column.dtype}'. "
I still see `label` here.

2024-08-26 09:48 UTC, popescu-v commented on khiops/sklearn/estimators.py
> +        if ds.target_column is not None:
I cannot see the comment; where is it?

2024-08-26 09:56 UTC, popescu-v commented on khiops/utils/dataset.py
> +            )
I think this `if` should be removed, as this case is covered by the previous `if` AFAIU.

2024-08-26 09:59 UTC, popescu-v commented on khiops/utils/helpers.py
> +def _sort_file_table(table, sep, header, output_dir):
Ok, the docstring now looks clear to me.

2024-08-26 10:25 UTC, popescu-v commented on tests/test_dataset_class.py
> +        # Check that the main table is root iff for multitable
Yes, it is clearer indeed, ok.

2024-08-26 10:44 UTC, popescu-v commented on khiops/utils/dataset.py
> +                    f"not present in columns '{self.main_table.column_ids}'"
Ok.

2024-08-26 10:47 UTC, popescu-v commented on tests/test_dataset_class.py
> +        np.random.seed(31416)
> Add comment like
> `# Set reproducible initial random state` or something like that.

Comment ^ ?

2024-08-26 11:10 UTC, popescu-v commented on khiops/sklearn/estimators.py
> +                )
Ok. Issue added: https://github.com/KhiopsML/khiops-python/issues/232.

2024-08-26 11:26 UTC, popescu-v commented on khiops/utils/dataset.py
> +    # Check the "tables" field
As this is a module-public API function, we should check that `ds_spec` is a `dict` in the first place IMHO.

2024-08-26 11:28 UTC, popescu-v commented on khiops/utils/dataset.py
> +    if not isinstance(table_spec, tuple):
As this is a module-private function, wouldn't an `assert` be more appropriate for checking the inputs, as this is not a user-facing function?

2024-08-26 11:31 UTC, popescu-v commented on khiops/utils/dataset.py
> +    assert len(ds_spec) > 1
We want to check that, rather `len(ds_spec["tables]) > 1`, right? I would just `assert` that `ds_spec` is a `dict` here and would defer the `len` condition to later, after we have checked that `"tables" in ds_spec` IMHO.

2024-08-26 11:33 UTC, popescu-v commented on khiops/utils/dataset.py
> +    if not is_list_like(relations_spec):
Why is this not an `assert` as the error could only be a programmatic one, because this is a module-private function?

2024-08-26 11:36 UTC, popescu-v commented on khiops/utils/dataset.py
> +            )
I would put this `if` before the previous `for`, thus the check could fail faster, without needing to go through the loop over all the secondary tables.

2024-08-26 11:38 UTC, popescu-v commented on khiops/utils/dataset.py
> +        table_key_error = not set(parent_table_key).issubset(set(child_table_key))
There is no need for `set(child_table_key)` here; just `child_table_key` suffices, as the conversion is implicit.

2024-08-26 11:41 UTC, popescu-v commented on khiops/utils/dataset.py
> +    elif is_list_like(parent_table_key) and isinstance(child_table_key, str):
Should we also fail if e.g. `parent_table_key == ["my_key"]` and `child_table_key == "my_key"`? Conceptually, they key lookup can be performed. Should we handle this as a special case (single-element list parent table key and string child table key, with single-element parent table key element equal to child table key string)?

2024-08-26 11:43 UTC, popescu-v commented on khiops/utils/dataset.py
> +        else:
Shouldn't we also check that `child_table_key` is a `list-like` of `str`s? Otherwise, if there is e.g. an `int` in there, then this code would fail; should we let it just fail in `TypeError`?

2024-08-26 11:44 UTC, popescu-v commented on khiops/utils/dataset.py
> +        else:
Idem, check that `parent_table-key` is a list of `str`s, or else just let it fail with a low-level Python `TypeError`?

2024-08-26 11:46 UTC, popescu-v commented on khiops/utils/dataset.py
> +def _check_no_cycles(relations_spec, main_table_name):
Shouldn't we at least `assert` that we can iterate on `relations_spec`?

2024-08-26 11:51 UTC, popescu-v commented on khiops/utils/dataset.py
>          ``False`` it is considered as numeric. Ignored if ``y`` is ``None``.
What happens if `y` is a `pandas.Series` of dates or timestamps? Are they coerced to `Categorical`?

2024-08-26 11:57 UTC, popescu-v commented on khiops/utils/dataset.py
>          if len(X["tables"]) == 1:
The policy error is that we should fail with `KeyError` if `"tables" not in X`? Idem for `"main_table"`? Or should we rather have a series of `assert`s, as this is a private method?

2024-08-26 12:03 UTC, popescu-v commented on khiops/utils/dataset.py
> +                    (parent, child, relation[2] if len(relation) == 3 else False)
What happens if `X["relations"]` is defined but the tables themselves are `SparseTable` or `NumpyTable`? Shouldn't we check that for `SparseTable` or `NumpTable` the "relation" spec key is not defined, or otherwise just ignore it? Because, as it stands, AFAIU we could have a set of spurious relations, even though `self.secondary_tables` is empty.

2024-08-26 12:08 UTC, popescu-v commented on khiops/utils/dataset.py
> +                self.main_table.khiops_types[self.target_column_id] = "Numerical"
What happens if targets are of type `"Date"` and `categorical_target` is `False`?

2024-08-26 12:25 UTC, popescu-v commented on khiops/utils/dataset.py
>              while tables_to_visit:
I would remove the `parent_table_name` variable and use `parent_table` directly in the call to `dictionary_domain.get_dictionary`.

2024-08-26 12:28 UTC, popescu-v commented on khiops/utils/dataset.py
> +        else:
Add comment like `# Don't provide target for file-based dataset` before the `else`.

2024-08-26 13:40 UTC, popescu-v commented on khiops/utils/dataset.py
>              dictionary.key = list(self.key)
Why `list(...)` here? `self.key` is now already a `list`, isn't it?

2024-08-26 13:41 UTC, popescu-v commented on khiops/utils/dataset.py
>      """Table encapsulating the features dataframe X and the target labels y
Remove `and the target labels y`, as there is no `y` input after the refactoring.

2024-08-26 13:42 UTC, popescu-v commented on khiops/utils/dataset.py
> +    X is of type pandas.DataFrame. y is array-like.
Remove `. y is array-like`: there is no `y` input.

2024-08-26 13:46 UTC, popescu-v commented on khiops/utils/dataset.py
>              raise ValueError("'dataframe' is empty")
Either remove this restriction, or add "non-empty dataframe" to the `PandasTable` class docstring.

I would remove this restriction, unless there is a compelling reason to keep it: the `dataframe` might be the result of a computation and hence could sometimes be empty, right?

2024-08-26 13:54 UTC, popescu-v commented on khiops/utils/dataset.py
>  class NumpyTable(DatasetTable):
I would not mention `(X, y)` as we can't find these in the  inputs to `NumpyTable`'s `__init__` method.

2024-08-26 13:59 UTC, popescu-v commented on khiops/utils/dataset.py
> +        self.data_source = check_array(array, ensure_2d=True, force_all_finite=False)
`force_all_finite` can also be set to `"allow-nan"` if only `numpy.nan` and `pandas.NA` can be accepted. As currently set (to `False`) we also accept `numpy.inf`. Is this what we want? How does Khiops handle `Inf`?

2024-08-26 14:01 UTC, popescu-v commented on khiops/utils/dataset.py
> +            column_id: get_khiops_type(self.data_source.dtype)
I would only call `get_khiops_type(self.data_source.dtype)` once, just before the dict comprehension, as the values for all keys are the same.

2024-08-26 14:04 UTC, popescu-v commented on khiops/utils/dataset.py
>              self.key
I would factor out these asserts in a module-private helper function as they are also used in `PandasTable`'s eponymous method.

2024-08-26 14:06 UTC, popescu-v commented on khiops/utils/dataset.py
>      def _create_dataframe_copy(self):
I would drop this helper altogether: it's one-liner that is also used in the `NumpyTable` in the same context; but it's not used in the other classes.

2024-08-26 14:25 UTC, popescu-v commented on khiops/utils/dataset.py
>          assert key is None, "'key' must be unset for sparse matrix tables"
I'm not sure about the `assert` here: this is a public API: would a `ValueError` be more appropriate here?

2024-08-26 14:27 UTC, popescu-v commented on khiops/utils/dataset.py
>                  type_error_message("'matrix' dtype", matrix.dtype, "numeric")
State in the docstring of the class that the elements of the input sparse matrix must be numeric?

2024-08-26 16:35 UTC, popescu-v commented on khiops/utils/dataset.py
>      key : list-like of str, optional
Move `key` before `sep` to match the signature.

2024-08-26 16:36 UTC, popescu-v commented on khiops/utils/dataset.py
> +        # Check the parameters specific to this sub-class
Shouldn't we also check that `sep` is a 1-character string?

2024-08-26 16:39 UTC, popescu-v commented on khiops/utils/dataset.py
> +        assert json_domain["dictionaries"][0]["name"] == self.name
Why `assert` here? This doesn't look as a programmer error IMHO. `json_domain` is a Khiops output (indirectly).

2024-08-26 16:52 UTC, popescu-v commented on khiops/sklearn/estimators.py
> +def _check_categorical_target_type(ds):
I wonder whether these checks should be done in the `Dataset`: indeed, are there cases of `Dataset` usage, outside of the `sklearn` estimator context, where the target column should have elements of a different type than those checked here?

2024-08-27 08:12 UTC, folmos-at-orange commented on khiops/sklearn/estimators.py
> +                f"Unknown label type '{ds.target_column.dtype}'. "
Done

2024-08-27 08:15 UTC, folmos-at-orange commented on khiops/sklearn/estimators.py
> +        if ds.target_column is not None:
Lost in rebase ... now done.

2024-08-27 08:22 UTC, folmos-at-orange commented on tests/test_dataset_class.py
> +        np.random.seed(31416)
Done

2024-08-27 11:47 UTC, folmos-at-orange commented on tests/test_dataset_class.py
> +            #  - the type of "Date" from Timestamp to "Date" as Khiops can detect it
Ok, rephrased it.

2024-08-27 11:53 UTC, folmos-at-orange commented on khiops/samples/samples_sklearn.py
> +    ).squeeze("columns")
Done

2024-08-27 11:56 UTC, folmos-at-orange commented on khiops/utils/dataset.py
> +            )
Ok & Done

2024-08-27 11:58 UTC, folmos-at-orange commented on khiops/utils/dataset.py
> +    # Check the "tables" field
Ok & Done

2024-08-27 11:59 UTC, folmos-at-orange commented on khiops/utils/dataset.py
> +    if not isinstance(table_spec, tuple):
It is private but it is a "check" routine, so we want the check for errors and report them to the user.

2024-08-27 12:02 UTC, folmos-at-orange commented on khiops/utils/dataset.py
> +    assert len(ds_spec) > 1
Ok & Done.

2024-08-27 12:03 UTC, folmos-at-orange commented on khiops/utils/dataset.py
> +    if ds_spec["main_table"] not in ds_spec["tables"]:
Now it is an assert as suggested above.

2024-08-27 12:05 UTC, folmos-at-orange commented on khiops/utils/dataset.py
> +    if not is_list_like(relations_spec):
Again, because it is a check method and we want to propagate the error to the user.

2024-08-27 12:07 UTC, folmos-at-orange commented on khiops/utils/dataset.py
> +            )
We need the `relation` iteration variable.

2024-08-27 12:31 UTC, folmos-at-orange commented on khiops/utils/dataset.py
> +    elif is_list_like(parent_table_key) and isinstance(child_table_key, str):
Ok, now it reads
```python
    elif is_list_like(parent_table_key) and isinstance(child_table_key, str):
        error_found = len(parent_table_key) != 1 or child_table_key not in parent_table_key
```

2024-08-27 12:32 UTC, folmos-at-orange commented on khiops/utils/dataset.py
> +        else:
I'll add asserts.

2024-08-27 12:34 UTC, folmos-at-orange commented on khiops/utils/dataset.py
> +        else:
Done

2024-08-27 12:34 UTC, folmos-at-orange commented on khiops/utils/dataset.py
> +        else:
Done above.

2024-08-27 12:35 UTC, folmos-at-orange commented on khiops/utils/dataset.py
> +def _check_no_cycles(relations_spec, main_table_name):
This is already checked in the caller, `_check_no_cycles` is part of its implementation.

2024-08-27 12:37 UTC, folmos-at-orange commented on khiops/utils/dataset.py
>          if len(X["tables"]) == 1:
This is checked with the check method called above.

2024-08-27 12:38 UTC, folmos-at-orange commented on khiops/utils/dataset.py
> +    if ds_spec["main_table"] not in ds_spec["tables"]:
I didn't added in the end, see above.

2024-08-27 12:39 UTC, folmos-at-orange commented on khiops/utils/dataset.py
> +    assert len(ds_spec) > 1
I didn't added in the end. Thes series of `_check` methods are the implementation of the main `check` one. These checks are performed in order so we do not need to recheck  (either with exceptions or asserts) the integrity of the spec.

2024-08-27 12:40 UTC, folmos-at-orange commented on khiops/utils/dataset.py
> +        else:
Did'nt added the asserts in the end, see above.

2024-08-27 13:34 UTC, folmos-at-orange commented on khiops/utils/dataset.py
> +                    (parent, child, relation[2] if len(relation) == 3 else False)
Yeah, we haven't check that. I'll check in the main `check` method that the tables can only be `pd.DataFrame`s or `str`s in the multi-table case.

2024-08-27 13:38 UTC, folmos-at-orange commented on khiops/utils/dataset.py
> +            table_type = "main" if ds_spec["main_table"] == table_name else "secondary"
Ok & Done.

2024-08-27 13:44 UTC, folmos-at-orange commented on khiops/utils/dataset.py
> +                self.main_table.khiops_types[self.target_column_id] = "Numerical"
Then it will be deemed a `Numerical` one. 

- In-memory: It won't happen since we check the target type elsewhere (we even check that is finite).
- file: We will just force the type and Khiops will complain if it can't translate that to a proper number.

2024-08-27 13:45 UTC, folmos-at-orange commented on khiops/utils/dataset.py
>              while tables_to_visit:
This part of the code wasn't modified.

2024-08-27 13:49 UTC, folmos-at-orange commented on khiops/utils/dataset.py
>              dictionary.key = list(self.key)
Ok, but out of scope.

2024-08-27 13:51 UTC, folmos-at-orange commented on khiops/utils/dataset.py
> +    X is of type pandas.DataFrame. y is array-like.
I removed the whole paragraph since we have a proper `Parameters` section.

2024-08-27 13:52 UTC, folmos-at-orange commented on khiops/utils/dataset.py
>              raise ValueError("'dataframe' is empty")
If it is empty Khiops will fail. I'll add non-empty.

2024-08-27 13:55 UTC, folmos-at-orange commented on khiops/utils/dataset.py
> +            column_id: get_khiops_type(self.data_source.dtype)
This is clear and there is no need to optimize. Also we would have to add a variable to store it.

2024-08-27 15:19 UTC, folmos-at-orange commented on khiops/utils/dataset.py
> +        else:
Added clarifying comments to `if/else`.

2024-08-27 15:20 UTC, folmos-at-orange commented on khiops/utils/dataset.py
>      """Table encapsulating the features dataframe X and the target labels y
I removed the whole comment now that we have a proper `Parameters` section.

2024-08-27 15:21 UTC, popescu-v commented on khiops/utils/dataset.py
> +    if not isinstance(table_spec, tuple):
Yes, ok, I see: it checks user input directly.

2024-08-27 15:23 UTC, folmos-at-orange commented on khiops/utils/dataset.py
> +        self.data_source = check_array(array, ensure_2d=True, force_all_finite=False)
Not clear, but if there it is a problem Khiops will report it.

2024-08-27 15:24 UTC, popescu-v commented on khiops/utils/dataset.py
> +            )
I have proposed to move this `if`, before the _inner_ `for` just above it, not before the outer for.

2024-08-27 15:26 UTC, popescu-v commented on khiops/utils/dataset.py
> +        else:
IMHO this is just a low-level Python issue: we can't `join` on lists of `ints`...

2024-08-27 15:29 UTC, popescu-v commented on khiops/utils/dataset.py
> +                self.main_table.khiops_types[self.target_column_id] = "Numerical"
Yeah, ok, we defer the checking to Khiops for file-based datasets.

2024-08-27 15:35 UTC, popescu-v commented on khiops/utils/dataset.py
> +        self.data_source = check_array(array, ensure_2d=True, force_all_finite=False)
So, we keep `force_all_finite` set to `True`? If so, I would add a comment providing rationale for it (because otherwise it seems to me like a - somewhat arbitrary w/o any explanation - restriction).

2024-08-27 15:40 UTC, popescu-v commented on khiops/utils/dataset.py
> +    assert len(ds_spec) > 1
Yeah, ok, I think I kind of see your point. In this case, I'm not sure I get what this assert that there are at least 2 keys in `ds_spec` brings us.

2024-08-27 15:42 UTC, popescu-v commented on khiops/utils/dataset.py
> +    if ds_spec["main_table"] not in ds_spec["tables"]:
Yeah, Ok, I'll close this thread for now, but IMHO we need to discuss the general rationale of these checks: what (shallow structure, contents, partial content) / where (in general public methods, in "private" implementations?) / how to check (runtime exceptions, asserts?).

2024-08-27 15:43 UTC, popescu-v commented on khiops/utils/dataset.py
> +        else:
This is a low-level Python issue IMHO (see comment above).

2024-08-27 15:43 UTC, popescu-v commented on khiops/utils/dataset.py
> +                    (parent, child, relation[2] if len(relation) == 3 else False)
Ok.

2024-08-27 15:43 UTC, folmos-at-orange commented on khiops/utils/dataset.py
>                  type_error_message("'matrix' dtype", matrix.dtype, "numeric")
Ok, but this is out of scope.

2024-08-27 15:43 UTC, folmos-at-orange commented on khiops/utils/dataset.py
> +            column_id: get_khiops_type(matrix.dtype) for column_id in self.column_ids
As stated above this is fine.

2024-08-27 15:45 UTC, folmos-at-orange commented on khiops/utils/dataset.py
>      key : list-like of str, optional
Ok & Done.

2024-08-27 15:45 UTC, folmos-at-orange commented on khiops/utils/dataset.py
> +        # Check the parameters specific to this sub-class
The API calls will.

2024-08-27 15:51 UTC, folmos-at-orange commented on khiops/utils/dataset.py
> +        assert json_domain["dictionaries"][0]["name"] == self.name
Ok & Done.

2024-08-27 15:52 UTC, folmos-at-orange commented on khiops/utils/dataset.py
> -    target_column : :external:term:`array-like`, optional
Ok & Done.

2024-08-27 16:00 UTC, folmos-at-orange commented on khiops/utils/dataset.py
>  class NumpyTable(DatasetTable):
Ok & Done.

2024-08-27 16:00 UTC, popescu-v commented on khiops/utils/dataset.py
> +    elif is_list_like(parent_table_key) and isinstance(child_table_key, str):
Yeah, I think that covers it. I would close as soon as this is pushed.

2024-08-27 16:03 UTC, popescu-v commented on khiops/utils/dataset.py
>          assert key is None, "'key' must be unset for sparse matrix tables"
Ok, I see your point. However, I had previously thought that since this was a big refactoring anyway, opportunistic improvements such as this one would be allowed. But ok for keeping this out of the PR, to keep the PR as focused as possible.

2024-08-27 16:04 UTC, popescu-v commented on khiops/utils/dataset.py
>                  type_error_message("'matrix' dtype", matrix.dtype, "numeric")
Ok, but see previous comment above (scope of the PR vs. small opportunistic improvements).

2024-08-27 16:21 UTC, folmos-at-orange commented on khiops/utils/dataset.py
> +            )
Ok, I get it but we do not need to optimize this.

2024-08-27 16:22 UTC, folmos-at-orange commented on khiops/utils/dataset.py
> +        else:
This is already checked in `_check_table_key`

2024-08-27 16:24 UTC, popescu-v commented on khiops/utils/dataset.py
> +        else:
Ok, got it.

2024-08-28 07:34 UTC, folmos-at-orange commented on khiops/sklearn/estimators.py
> +                f"Unknown label type '{ds.target_column.dtype}'. "
Reverted because the sklearn tests require 'label' in this message.

2024-08-28 09:39 UTC, popescu-v commented on khiops/sklearn/estimators.py
> +                f"Unknown label type '{ds.target_column.dtype}'. "
Ok, but then why not use "label" in `_check_categorical_target_type` as well, for consistency?

2024-08-28 09:54 UTC, popescu-v commented on tests/test_dataset_class.py
> +            #  - the type of "Date" from Timestamp to "Date" as Khiops can detect it
s/the Khiops detects/the type Khiops detects/

2024-08-28 10:29 UTC, folmos-at-orange commented on tests/test_dataset_class.py
> +            #  - the type of "Date" from Timestamp to "Date" as Khiops can detect it
Ok & Done

2024-08-28 11:39 UTC, folmos-at-orange commented on khiops/utils/dataset.py
> +                    (parent, child, relation[2] if len(relation) == 3 else False)
Done. I added a test to `test_dataset_errors` for this check.

2024-08-28 13:27 UTC, popescu-v commented on khiops/utils/dataset.py
> +                    (parent, child, relation[2] if len(relation) == 3 else False)
I see. One checks that (in the multi-table case) all secondary tables have the same type as the main table.

2024-08-28 16:58 UTC, popescu-v commented on CHANGELOG.md
> +- (General) `train_test_split_dataset` helper function to ease the splitting in train/test for
I would s/for multi-table datasets/for mono- or multi-table datasets/, because both are handled.

2024-08-28 16:59 UTC, popescu-v commented on CHANGELOG.md
> +- (General) `sort_dataset` helper function to ease the sorting by key of multi-table datasets.
I would s/for multi-table datasets/for mono- or multi-table datasets/, because both are handled.

2024-08-28 17:52 UTC, popescu-v commented on tests/test_dataset_errors.py
> +        """Test Dataset raising ValueError if a MT spec havea an empty table key"""
s/havea/has/

2024-09-03 19:04 UTC, folmos-at-orange commented on CHANGELOG.md
> +- (General) `sort_dataset` helper function to ease the sorting by key of multi-table datasets.
The helper is useful only for multi-table, so I announce it where it matters.

2024-09-05 14:28 UTC, popescu-v commented on tests/test_dataset_errors.py
> +        """Test Dataset raising ValueError if a MT spec have an empty table key"""
s/if a MT spec have an empty table key/if an MT spec has an empty table key/

2024-09-13 16:14 UTC, folmos-at-orange commented on tests/test_dataset_errors.py
> +        """Test Dataset raising ValueError if a MT spec have an empty table key"""
Ok & done everywhere.

2024-09-13 16:15 UTC, popescu-v requested changes
Provide further explanations in three commit messages:
- commit: https://github.com/KhiopsML/khiops-python/pull/180/commits/1bbae130dff6707df5efa5bfc6eb383f751ae50a : provide explanation of what the refactoring consists of and, more important, provide rationale for why this was necessary.
- commit https://github.com/KhiopsML/khiops-python/pull/180/commits/9047000d8fff43eaff97086fce8d3dba8d5abf84 : explain briefly what the simplification consists of, and why it was necessary (in this PR)

2024-09-13 16:59 UTC, popescu-v approved these changes

2024-09-16 03:56 UTC, merged