49 add standard sklearn estimator attributes
KhiopsML/khiops-python pull request #190
Opened 2024-06-18 13:31 UTC by nairbenrekia

2024-06-27 18:38 UTC, folmos-at-orange requested changes

2024-06-27 18:38 UTC, folmos-at-orange commented on khiops/sklearn/estimators.py
> +                [[var.name] for var in modeling_report.selected_variables]
Eliminate the brackets around `var.name`.

2024-06-27 18:38 UTC, folmos-at-orange commented on khiops/sklearn/estimators.py
> +        self.n_features_evaluated_ = preparation_report.evaluated_variable_number
This a little more tricky, because you have to add also
- The number of evaluated pairs
- The number of evaluated trees

The first are in the bivariate preparation report. However for the trees we still don't have an object, so you'll have to recover it from the JSON object `model_report_raw_`. It should be `self.model_report_raw_["treePreparationReport"]["summary"]["evaluatedVariables"]`.

2024-06-27 18:38 UTC, folmos-at-orange commented on khiops/sklearn/estimators.py
>          )
General comment:

Add to the training samples, just after the `fit` call, a part where you print some info about the selected features, something along the lines of:
```python

# Show the feature importance info
print(f"Features evaluated: {khc.n_features_evaluated_}")
print(f"Features selected : {khc.n_feature_used_}")
print(f"Top 3 used features")
for i, feature in enumerate(khc.feature_used_names_[:3]):
    print(f"{feature} - Importance {khc.feature_used_importances_[i][2]}")
```

2024-06-27 18:38 UTC, folmos-at-orange commented on khiops/sklearn/estimators.py
> +        Level of the features evaluated by the regressor.
I'd add `See below for an explanation of the level`.

2024-06-27 18:38 UTC, folmos-at-orange commented on khiops/sklearn/estimators.py
> +        Level, Weight and Importance of the features used by the regressor.
Also for the importances:
- Add that they are of dimension `(n_features_used_, 3)`
- Add a brief explanation for the Level, Weight and the Importance
  - Level: A measure of how well the feature predicts by itself the target. Values in [0,1], the more approaches to 1 the better predicts the target.
  - Weight: A measure of the contribution in the model to the target prediction. Values in [0,1], the more approaches to 1 the more the variable contributes to the model.
  - Importance: The geometric mean of the Level and Weight. A feature is important if its predicts well the target by itself and its contribution in the model is significant.

2024-07-01 09:39 UTC, nairbenrekia commented on khiops/sklearn/estimators.py
> +        Level, Weight and Importance of the features used by the classifier.
Ok.

2024-07-01 10:27 UTC, nairbenrekia commented on khiops/sklearn/estimators.py
> +        Level, Weight and Importance of the features used by the regressor.
Ok. I used the definitions of KhiopsGuide.pdf.

2024-07-01 11:10 UTC, nairbenrekia commented on khiops/sklearn/estimators.py
> +
Yes. Ok.

2024-07-01 11:10 UTC, nairbenrekia commented on khiops/sklearn/estimators.py
> +        Level of the features evaluated by the encoder.
Ok.

2024-07-01 11:10 UTC, nairbenrekia commented on khiops/sklearn/estimators.py
> +
Ok.

2024-07-01 11:13 UTC, nairbenrekia commented on khiops/sklearn/estimators.py
> +            self.n_feature_used_ = len(self.feature_used_names_)
Ok.

2024-07-01 11:14 UTC, nairbenrekia commented on khiops/sklearn/estimators.py
> +                [[var.name] for var in modeling_report.selected_variables]
Ok.

2024-07-01 11:18 UTC, nairbenrekia commented on khiops/sklearn/estimators.py
> +        Level of the features evaluated by the regressor.
Ok.

2024-07-01 11:53 UTC, nairbenrekia commented on khiops/sklearn/estimators.py
> +        self.n_features_evaluated_ = preparation_report.evaluated_variable_number
Thanks. Ok.

2024-07-01 20:52 UTC, nairbenrekia commented on tests/test_estimator_attributes.py
> +
True. Ok.

2024-07-01 20:52 UTC, nairbenrekia commented on tests/test_estimator_attributes.py
> +        self.assertEqual(khc_adult.is_multitable_model_, False)
Ok.

2024-07-01 20:54 UTC, nairbenrekia commented on tests/test_estimator_attributes.py
> +        self.assertEqual(model.is_fitted_, True)
Ok.

2024-07-18 12:24 UTC, nairbenrekia commented on khiops/sklearn/estimators.py
>          )
Ok.

2024-07-18 16:22 UTC, nairbenrekia commented on tests/test_estimator_attributes.py
> +        self.assertEqual(khc_adult.n_features_in_, len(X.columns))
Ok.

2024-08-05 15:58 UTC, folmos-at-orange approved these changes

2024-08-05 15:59 UTC, merged