192 simplify mpi command according to recent khiops env changes
KhiopsML/khiops-python pull request #193
Opened 2024-06-20 16:34 UTC by popescu-v

closes #192

2024-06-24 09:21 UTC, folmos-at-orange requested changes

2024-06-24 09:21 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +                # OpenMPI
I'd put a more explicit comment: In Linux we use OpenMPI.

2024-06-24 09:21 UTC, folmos-at-orange commented on .github/workflows/pip.yml
>        - name: Run tests
We cannot merge this until we resolve the name of the variable.

2024-06-24 09:21 UTC, folmos-at-orange commented on .github/workflows/unit-tests.yml
>            KHIOPS_DOCKER_RUNNER_URL: https://localhost:11000
All commits should be squashed.

2024-06-24 09:26 UTC, popescu-v commented on khiops/core/internals/runner.py
> +                # OpenMPI
Ok, fair enough.

2024-06-24 09:26 UTC, popescu-v commented on .github/workflows/pip.yml
>        - name: Run tests
Yes, right.

2024-06-24 09:27 UTC, popescu-v commented on .github/workflows/unit-tests.yml
>            KHIOPS_DOCKER_RUNNER_URL: https://localhost:11000
Yes, once we settle on the name of the variable.

2024-06-24 09:42 UTC, popescu-v commented on khiops/core/internals/runner.py
> +                # OpenMPI
Done.

2024-06-24 13:44 UTC, folmos-at-orange requested changes

2024-06-24 13:44 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +                # For Linux native installations we use OpenMPI
Also comment that we honor `KHIOPS_MPI_VERBOSE`

2024-06-24 13:44 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
>              mpiexec_path = os.environ.get("KHIOPS_MPIEXEC_PATH") or shutil.which(
Add also the documentation for `KHIOPS_MPI_VERBOSE` and copy it to `notes.rst`.

2024-06-24 13:44 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +                    self.mpi_command_args.append("--quiet")
I'd be possible to add a test to `KhiopsCoreVariousTests`

2024-06-24 13:54 UTC, popescu-v commented on khiops/core/internals/runner.py
> +                    self.mpi_command_args.append("--quiet")
Yes, ok.

2024-06-24 13:55 UTC, popescu-v commented on khiops/core/internals/runner.py
>              mpiexec_path = os.environ.get("KHIOPS_MPIEXEC_PATH") or shutil.which(
Ok.

2024-06-24 13:55 UTC, popescu-v commented on khiops/core/internals/runner.py
> +                # For Linux native installations we use OpenMPI
Ok.

2024-06-24 16:21 UTC, popescu-v commented on khiops/core/internals/runner.py
> +                # For Linux native installations we use OpenMPI
Done.

2024-06-24 16:21 UTC, popescu-v commented on khiops/core/internals/runner.py
>              mpiexec_path = os.environ.get("KHIOPS_MPIEXEC_PATH") or shutil.which(
Done.

2024-06-24 16:21 UTC, popescu-v commented on khiops/core/internals/runner.py
> +                    self.mpi_command_args.append("--quiet")
Done.

2024-06-24 16:21 UTC, popescu-v commented on .github/workflows/unit-tests.yml
>            KHIOPS_DOCKER_RUNNER_URL: https://localhost:11000
Done.

2024-06-24 16:25 UTC, folmos-at-orange requested changes

2024-06-24 16:25 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +        implementations, this flag currently has no effect
I'd move just after `KHIOPS_MPI_COMMAND_ARGS` and reword to:

```
verbosity of the MPI command; if equal to "false" then it adds the `--quiet` 
option to the MPI command, otherwise it does nothing. Only works if: 

- The OS is Linux, and
- the installation is Khiops system-wide + ``khiops-python`` ``pip``, and
- the environment variable `KHIOPS_MPI_COMMAND_ARGS` is not set
```

2024-06-24 16:25 UTC, folmos-at-orange commented on tests/test_core.py
> +            # By default, "--quiet" is an OpenMPI command argument
Move before the `if`

2024-06-24 16:25 UTC, folmos-at-orange commented on tests/test_core.py
> +            # By default, "--quiet" is an OpenMPI command argument
This test should be skipped in systems other than Linux

2024-06-24 16:25 UTC, folmos-at-orange commented on tests/test_core.py
> +
Why the asserts are in `try` blocks ?

2024-06-24 16:30 UTC, popescu-v commented on tests/test_core.py
> +            # By default, "--quiet" is an OpenMPI command argument
Ok.

2024-06-24 16:31 UTC, popescu-v commented on tests/test_core.py
> +            # By default, "--quiet" is an OpenMPI command argument
Ok, right.

2024-06-24 16:36 UTC, popescu-v commented on khiops/core/internals/runner.py
> +        implementations, this flag currently has no effect
Actually, the behaviour (as per the https://github.com/KhiopsML/khiops/issues/310) is the other way around: if the variable is not defined or is set to something else than "true", then `--quiet` is added (by default); if the variable is set to true, then the `--quiet` option is not added.

2024-06-24 16:43 UTC, popescu-v commented on khiops/core/internals/runner.py
> +        implementations, this flag currently has no effect
Done: rephrased the doc a bit, as suggested (modulo the important nuance highlighted in the previous comment).

2024-06-24 16:43 UTC, popescu-v commented on tests/test_core.py
> +            # By default, "--quiet" is an OpenMPI command argument
Done.

2024-06-24 16:44 UTC, popescu-v commented on tests/test_core.py
> +            # By default, "--quiet" is an OpenMPI command argument
Done.

2024-06-24 16:44 UTC, popescu-v commented on tests/test_core.py
> +
So that we restore the previous verbosity even if the assertions fail.

2024-06-25 04:15 UTC, folmos-at-orange commented on tests/test_core.py
> +
Ok

2024-06-25 04:19 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +        then it adds the `--quiet` option; else, it does nothing. Only works if:
Add an empty line after `:` (sphinx won't work otherwise). Also I'd check that the rendering is ok.

2024-06-25 04:21 UTC, folmos-at-orange requested changes

2024-06-25 04:21 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +        - the environment variable `KHIOPS_MPI_COMMAND_ARGS` is not set
Add an empty line after the `:`, otherwise sphinx won't work. Also I'd check that the rendering is ok.

2024-06-25 04:21 UTC, folmos-at-orange commented on doc/notes.rst
> +    - the environment variable `KHIOPS_MPI_COMMAND_ARGS` is not set
Same as above.

2024-06-25 08:40 UTC, popescu-v commented on khiops/core/internals/runner.py
> +        implementations, this flag currently has no effect
Why is this thread still not resolved? Is it because we need to reach consensus on the behavior of this enironment variable?

2024-06-25 08:43 UTC, popescu-v commented on khiops/core/internals/runner.py
> +        - the environment variable `KHIOPS_MPI_COMMAND_ARGS` is not set
Ok.

2024-06-25 08:47 UTC, popescu-v commented on doc/notes.rst
> +    - the environment variable `KHIOPS_MPI_COMMAND_ARGS` is not set
Ok.

2024-06-25 09:14 UTC, popescu-v commented on doc/notes.rst
> +    - the environment variable `KHIOPS_MPI_COMMAND_ARGS` is not set
Done.

2024-06-25 09:14 UTC, popescu-v commented on khiops/core/internals/runner.py
> +        - the environment variable `KHIOPS_MPI_COMMAND_ARGS` is not set
Done. It renders OK.

2024-06-25 09:18 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +        implementations, this flag currently has no effect
Yes, I'm just waiting for the confirmation of BG

2024-06-28 13:39 UTC, popescu-v commented on khiops/core/internals/runner.py
> +        implementations, this flag currently has no effect
To be addressed in another PR.

2024-06-28 13:41 UTC, merged