Reactivate the integration tests for remote file access (GCS, S3)
KhiopsML/khiops-python pull request #210
Opened 2024-07-11 10:38 UTC by tramora

Docker is installed in the khiopspydev docker image so that it can start the local fake servers .
The container must be started with the --privileged option otherwise docker inside the container would not start.
The fake servers are pre-provisioned with sample files to be ready before the tests run

2024-08-14 16:43 UTC, tramora commented
@popescu-v & @folmos-at-orange : a detail we forgot the S3 & GCS drivers are not released publicly and thus not available in the dev image. When trying to access to the remote files during the tests khiops complains
```
error : there is no driver available for the URI scheme 'gs://'
error : there is no driver available for the URI scheme 's3://'
```

2024-08-20 13:03 UTC, popescu-v commented
> @popescu-v & @folmos-at-orange : a detail we forgot the S3 & GCS drivers are not released publicly and thus not available in the dev image. When trying to access to the remote files during the tests khiops complains
> 
> ```
> error : there is no driver available for the URI scheme 'gs://'
> error : there is no driver available for the URI scheme 's3://'
> ```

Yes, AFAIU we need to wait for the drivers to be publicly released before the tests can work.

2024-10-21 13:41 UTC, popescu-v commented on .github/workflows/dev-docker.yml
> +  DEFAULT_KHIOPS_S3_DRIVER_VERSION: 0.0.12
I would use `_REVISION` instead of `_VERSION` to be consistent with `DEFAULT_KHIOPS_REVISION` and `DEFAULT_SERVER_REVISION`.

2024-10-21 13:43 UTC, popescu-v commented on .github/workflows/dev-docker.yml
> +      khiops-s3-driver-version:
I would use `-revision` instead of `-version` for consistency.

2024-10-21 13:48 UTC, popescu-v commented on .github/workflows/unit-and-integration-tests.yml
> +name: Unit & Integration Tests
I would go for simply "Tests" and `tests.yml`: shorter, more concise and allowing us more freedom to add different kinds of tests as well (non-regression, functional - actually, some Python "unit tests" are rather functional,  etc).

2024-10-21 14:01 UTC, popescu-v commented on packaging/docker/khiopspydev/Dockerfile.ubuntu
> +  && (dpkg -i --force-all KHIOPS_CORE.deb || true) && apt-get -f -y install \
Split in two lines on ` && `.

2024-10-21 14:05 UTC, popescu-v commented on packaging/docker/khiopspydev/Dockerfile.ubuntu
> +    && true
s/`_VERSION`/`_REVISION`/ (see relevant comment above).

2024-10-21 14:06 UTC, popescu-v commented on packaging/docker/khiopspydev/Dockerfile.ubuntu
> +    && (dpkg -i --force-all khiops-gcs.deb khiops-s3.deb || true) && apt-get -f -y install \
Split in two lines on ` && `: thus each different command has its own line, which is consistent with the rest of the file.

2024-10-21 14:06 UTC, popescu-v commented on packaging/docker/khiopspydev/Dockerfile.ubuntu
> +    && wget -O khiops-s3.deb https://github.com/KhiopsML/khiopsdriver-s3/releases/download/${KHIOPS_S3_DRIVER_VERSION}/khiops-s3_${KHIOPS_S3_DRIVER_VERSION}.deb \
s/`_VERSION`/`_REVISION`/ (see relevant comment above).

2024-10-21 14:40 UTC, popescu-v commented on packaging/docker/khiopspydev/run_fake_remote_file_servers.sh
> +  -p 4569 &
IMHO the port should not be hard-coded, but instead be passed as a variable or extracted from `AWS_ENDPOINT_URL`.

2024-10-21 14:42 UTC, popescu-v commented on tests/resources/remote-access/s3-bucket/khiops-cicd/samples/Iris/Iris.kdic/.fakes3_metadataFFF/metadata
> +---
Do we need to commit these metadata files?

2024-10-21 14:45 UTC, popescu-v commented on tests/test_remote_access.py
> +    # `AWS_SHARED_CREDENTIALS_FILE` and `AWS_CONFIG_FILE` that references files
AFAIK, the advantage of using an `AWS_SHARED_CREDENTIALS_FILE` is to centralize the "sensitive" information into a file that can be protected through access control so that only dedicated user (in dedicated group) can read it. And besides, the current modification obliges to expose the "sensitive" credentials a such ("in clear") in the environment. I'm not sure this is good practice.

Hence, I would maintain the file-based configuration:
- create the file on the Docker container
- add relevant credentials within
- protect the file through `chmod`.

2024-10-23 17:24 UTC, tramora commented on .github/workflows/dev-docker.yml
> +  DEFAULT_KHIOPS_S3_DRIVER_VERSION: 0.0.12
Variable name changed

2024-10-23 17:24 UTC, tramora commented on .github/workflows/dev-docker.yml
> +      khiops-s3-driver-version:
Variable name changed

2024-10-23 17:24 UTC, tramora commented on .github/workflows/unit-and-integration-tests.yml
> +name: Unit & Integration Tests
Label changed and yaml file renamed

2024-10-23 17:24 UTC, tramora commented on packaging/docker/khiopspydev/Dockerfile.ubuntu
> +  && (dpkg -i --force-all KHIOPS_CORE.deb || true) && apt-get -f -y install \
reformatting done

2024-10-23 17:25 UTC, tramora commented on packaging/docker/khiopspydev/Dockerfile.ubuntu
> +RUN chmod +x /scripts/*.sh && \
precision done

2024-10-23 17:25 UTC, tramora commented on packaging/docker/khiopspydev/Dockerfile.ubuntu
> +    && (dpkg -i --force-all khiops-gcs.deb khiops-s3.deb || true) && apt-get -f -y install \
reformatting done

2024-10-23 17:25 UTC, tramora commented on packaging/docker/khiopspydev/Dockerfile.ubuntu
> +    && wget -O khiops-s3.deb https://github.com/KhiopsML/khiopsdriver-s3/releases/download/${KHIOPS_S3_DRIVER_VERSION}/khiops-s3_${KHIOPS_S3_DRIVER_VERSION}.deb \
Variable name changed

2024-10-23 17:28 UTC, tramora commented on packaging/docker/khiopspydev/Dockerfile.ubuntu
> +# Do not use the latest fakes3 version because starting from 1.3.1 a licence is required
The pinned version of fakes3 covers all the needs for a remote access with the possibility of pre-provisionning the server with test files before it start.

Accordingly to the documentation s3rver does not provide this feature (yet)

2024-10-23 17:28 UTC, tramora commented on packaging/docker/khiopspydev/run_fake_remote_file_servers.sh
> +  -p 4569 &
port number extracted from the URL

2024-10-23 17:30 UTC, tramora commented on tests/resources/remote-access/s3-bucket/khiops-cicd/samples/Iris/Iris.kdic/.fakes3_metadataFFF/metadata
> +---
Yes unfortunately, fakes3 needs these files otherwise the preprovisioned files are ignored

2024-10-23 17:48 UTC, popescu-v commented on packaging/docker/khiopspydev/Dockerfile.ubuntu
> +# Do not use the latest fakes3 version because starting from 1.3.1 a licence is required
OK, then, to mitigate further maintenance issue, I would state this in a TODO comment; something like:
```
# TODO: Switch to https://github.com/jamhall/s3rver (MIT-licensed) as soon as it supports pre-provisioning the server with fixtures.
```
?

2024-10-23 17:51 UTC, popescu-v commented on tests/resources/remote-access/s3-bucket/khiops-cicd/samples/Iris/Iris.kdic/.fakes3_metadataFFF/metadata
> +---
OK, then I would put all these metadata files in a separate commit whose commit message states precisely this. Thus, this could be reverted more easily once the switch to s3ver (or another alternative) is done.

2024-10-23 17:55 UTC, popescu-v commented on .github/workflows/tests.yml
> +      image: ghcr.io/khiopsml/khiops-python/khiopspydev-ubuntu22.04:10.2.3-b.5.s3-gcs-remote-files
IMHO, all tests should be unified in a single job which uses this docker file tag. IMHO, we can update the default value for the tag, as well as for the inputs (on this branch). This was also done for other PRs (like switching to conda-forge etc).

But this update (in all impacted workflows, including pip or api-docs !) should be in a separate commit IMHO so that we identify it easily.

2024-10-23 18:00 UTC, popescu-v commented on packaging/docker/khiopspydev/run_fake_remote_file_servers.sh
> +  -p "${PORT_NUMBER:-4569}" &
Should only be `-p $PORT_NUMBER` IMHO.

2024-10-24 09:51 UTC, folmos-at-orange requested changes

2024-10-24 09:51 UTC, folmos-at-orange commented on tests/resources/remote-access/gcs-bucket/khiops-cicd/samples/Iris/Iris.txt
We really should avoid adding data files to the repository. These can be retrieved with the `kh-download-samples` tool.

2024-10-28 13:22 UTC, popescu-v commented on tests/resources/remote-access/s3-bucket/khiops-cicd/samples/Iris/Iris.kdic/.fakes3_metadataFFF/metadata
> +---
If `kh-download-datasets` is used to download the samples, then there is no need of pre-provisioning the files with the storage. Hence, there is no need for storing the metadata files anymore.

2024-11-21 10:57 UTC, folmos-at-orange commented on tests/resources/remote-access/gcs-bucket/khiops-cicd/samples/Iris/Iris.txt
I saw the files removed. I resolve this.

2024-12-16 10:07 UTC, popescu-v commented
> There is an issue remaining that breaks the tests and that I cannot fix right now.
> 
> It seems that khiops under the conda env cannot use the remote files drivers installed system wide. They cannot be installed via conda as there is no conda release yet.

This is true. Hence, IMHO the way to go for the current PR is to test the remote access only in the native case (Conda environments for test, but with the native `khiops-core` and drivers packages installed).

Then, as soon as the Conda packages for the drivers are available, a new PR should activate these integration tests in full Conda environments.

2024-12-16 14:11 UTC, tramora commented on .github/workflows/unit-and-integration-tests.yml
> +  test-access-to-remote-files:
No duplication anymore

2024-12-16 14:14 UTC, tramora commented on packaging/docker/khiopspydev/Dockerfile.ubuntu
> +# Do not use the latest fakes3 version because starting from 1.3.1 a licence is required
I started evaluating jamhall/s3rver but unfortunatly it is not fully compatible with our basic usage.
I ended in putting this comment
```
# if fakes3 is no longer compatible think about switching to an alternative and fully compatible server
```

2024-12-16 14:15 UTC, tramora commented on tests/resources/remote-access/s3-bucket/khiops-cicd/samples/Iris/Iris.kdic/.fakes3_metadataFFF/metadata
> +---
no pre-provisioning is done any longer, every test is set up with previously downloaded samples

2024-12-16 14:17 UTC, tramora commented on tests/test_remote_access.py
> +    # `AWS_SHARED_CREDENTIALS_FILE` and `AWS_CONFIG_FILE` that references files
The alternative AWS_* env variables are replaced by a configuration and credentials files referenced by the corresponding variables (AWS_CONFIG_FILE and AWS_SHARED_CREDENTIALS_FILE)

2024-12-16 14:19 UTC, tramora commented on tests/test_remote_access.py
> +    # for the integration tests
Rollback to the check to the pair of env variables GOOGLE_APPLICATION_CREDENTIALS and GCS_BUCKET_NAME

2024-12-16 14:20 UTC, tramora commented on .github/workflows/tests.yml
> +      image: ghcr.io/khiopsml/khiops-python/khiopspydev-ubuntu22.04:10.2.3-b.5.s3-gcs-remote-files
Fixed

2024-12-16 14:20 UTC, tramora commented on packaging/docker/khiopspydev/run_fake_remote_file_servers.sh
> +  -p "${PORT_NUMBER:-4569}" &
Fixed

2024-12-19 17:37 UTC, folmos-at-orange requested changes

2024-12-19 17:37 UTC, folmos-at-orange commented on tests/test_remote_access.py
> +
To avoid using `hasattr` and setting up your own temporary urls, instead of a per test setup/tear-down, I'd use one for the whole class. 

- In the `setupClass` method you simply set the env var `KHIOPS_TMP_DIR` with a fresh runner.
- In the `tearDownClass` method you clean up everything and restore the original temporary directory and runner.

Something like this example
```python
import unittest
import os
import subprocess
from khiops import core as kh
from khiops.core.internals.runner import KhiopsLocalRunner


class TestWithAltRunner(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        # Save the original runner and temp dir
        cls.original_runner = kh.get_runner()
        cls.original_khiops_temp_dir = os.environ.get("KHIOPS_TMP_DIR")

        # Set the test suite temp dir
        os.environ["KHIOPS_TMP_DIR"] = "/tmp/mytmpdir/" # replace here with the URL
        cls.runner = KhiopsLocalRunner()
    @classmethod
    def tearDownClass(cls):
        # Restore the original runner and temp dir
        kh.set_runner(cls.original_runner)
        if cls.original_khiops_temp_dir is None:
            del os.environ["KHIOPS_TMP_DIR"]
        else:
            os.environ["KHIOPS_TMP_DIR"] = cls.original_khiops_temp_dir

        # Clean the whole alternative temporary file
        # ...

    def test(self):
        print("\n======= Current test runner =========")
        kh.get_runner().print_status()
```

2024-12-20 18:08 UTC, tramora commented on tests/test_remote_access.py
> +        """
Fixed

2024-12-20 18:09 UTC, tramora commented on tests/test_remote_access.py
> +            # )
The code was left in comment if later debug is needed. Comment removed

2024-12-20 18:09 UTC, tramora commented on tests/test_remote_access.py
> +            are released as conda packages
Typo fixed

2024-12-20 18:09 UTC, tramora commented on tests/test_remote_access.py
> +                    f"{proto}://{bucket_name}/khiops-cicd/samples/" + file, "/tmp/dummy"
Fixed

2024-12-20 18:11 UTC, tramora commented on .github/workflows/tests.yml
> +          echo "HOME=${HOME}"
The command was put for diagnosis purpose : the HOME env variable was not expanded everywhere and I needed to see its value to copy it. Command removed

2024-12-20 18:14 UTC, tramora commented on .github/workflows/tests.yml
> +        ghcr.io/khiopsml/khiops-python/khiopspydev-ubuntu22.04:${{ inputs.image-tag || '10.2.3.0.s3-gcs-remote-files' }}
I may have misunderstood the process agreed with @popescu-v.
As long as the PR is in review,  the specific image build with this branch is not set yet as the latest.
Just before the merge then I can change to the latest.

2024-12-20 18:14 UTC, tramora commented on .github/workflows/dev-docker.yml
> +        description: Version of the driver used for remote files on Google Cloud Storage (GCS)
Rewording done

2024-12-20 18:20 UTC, popescu-v commented on khiops/core/internals/filesystems.py
> +        except Exception as e:
I would also restrict the "catch" here to `S3UploadFailedError`:
```python
except S3UploadFailedError as exc:
    raise RuntimeError(...) from exc
```
Thus, wenever there is a different (unexpected) exception, it would not be handled and whence would be propagated to the caller code so that we know about it (e.g. from inspecting the CI logs).

2024-12-20 18:22 UTC, popescu-v commented on packaging/conda/meta.yaml
> +    - pyopenssl>=24.0.0
Do we need `pyopenssl` to impose a specific lower bound of the version?

2024-12-20 18:25 UTC, popescu-v commented on packaging/docker/khiopspydev/Dockerfile.ubuntu
> +# You will have to add the `add-hosts` input instead (https://github.com/docker/build-push-action/#inputs)
Why can't we do this directly here? This Docker file is only useful in the CI context anyway.

2024-12-20 18:30 UTC, popescu-v commented on tests/test_remote_access.py
> +    # but are regarded unsecure
I would replace the last phrase "However, ..." with emphasis on the improved security of the alternative approach, like:

```bash
# However, storing the credentials in config files is more secure, because these can be protected by access policies.
```

2024-12-20 18:42 UTC, popescu-v commented on tests/test_remote_access.py
> +            # CONDA_DEFAULT_ENV and CONDA_PROMPT_MODIFIER
Rather `CONDA_PREFIX` than `CONDA_DEFAULT_ENV` (the former gives full path to the env).

But this would not work in a "conda-based" environment anyway (i.e. khiops is installed in a Conda env, but code is run from outside the Conda env (i.e. `CONDA_*` vars are not set: look for "conda-based" in runner.py).

Hence, we need to find a solution for this, because we don't want to use native drivers with Conda-installed khiops packages.

A solution might be to rely on `kh.get_runner().print_status()` and to look-up "install type" in the output of the function. `is_in_a_conda_env()` would return `True` if install type is either "conda" or "conda-based".

Something like:

```python
# At the beginning (if not already done)
from khiops import core as kh
#...

@staticmethod
def is_in_a_conda_env():
    status_message = kh.get_runner()._build_status_message()[0]
    for status_line in status_message.splitlines():
        if "install type" in status_line:
            install_type = status_line.split(":").strip()
            break
     return install_type in ("conda", "conda-based")
```

2024-12-20 19:02 UTC, popescu-v commented on tests/test_remote_access.py
> +            return conda_default_env and conda_default_env.endswith("_conda")
The `.endswith` leaks CI details in the tests (as the `_conda` env names for Conda-installed `khiops-core` is a CI detail).

The proposal from the previous comment avoids this.

2024-12-20 19:05 UTC, popescu-v commented on tests/test_remote_access.py
> +                # TODO : Temporary skip the test under a conda environment
Rephrase TODO comment to something like
`# TODO: Temporary skip the test for Conda-installed khiops-core`

2024-12-20 19:13 UTC, popescu-v commented on tests/test_remote_access.py
> +            # WARNING : khiops temp files cannot be remote
Add empty line before the comment (to have paragraphs).

2024-12-20 19:14 UTC, popescu-v commented on tests/test_remote_access.py
> +            # whereas root_temp_dir
Delete "whereas".

Add empty line before the beginning of the comment (to have the commented block as a paragraph).

2024-12-20 19:14 UTC, popescu-v commented on tests/test_remote_access.py
> +            # WARNING : khiops temp files cannot be remote
Add empty line before comment.

2024-12-20 19:15 UTC, popescu-v commented on tests/test_remote_access.py
> +            # whereas root_temp_dir
Delete "whereas". Add empty line before the first line of the comment.

2024-12-20 19:15 UTC, popescu-v requested changes
See the comments.

2024-12-27 15:41 UTC, folmos-at-orange commented on setup.py
> +            "pyopenssl": ["pyopenssl>=24.0.0"],
Then the dependency should impose its restriction on this package. Unless there are serious problems we should remove this.

2025-01-06 10:01 UTC, folmos-at-orange commented on .github/workflows/tests.yml
> +        ghcr.io/khiopsml/khiops-python/khiopspydev-ubuntu22.04:${{ inputs.image-tag || '10.2.3.0.s3-gcs-remote-files' }}
Ok. To fix beforem merging then.

2025-01-08 15:02 UTC, popescu-v commented on setup.py
> +            "pyopenssl": ["pyopenssl>=24.0.0"],
> Then the dependency should impose its restriction on this package. Unless there are serious problems we should remove this.

@tramora : Is there any specific version pinning issue with this package?

2025-01-08 17:06 UTC, popescu-v commented on packaging/docker/khiopspydev/Dockerfile.ubuntu
> +# Do not use the latest fakes3 version because starting from 1.3.1 a licence is required
Ok.

2025-01-08 17:11 UTC, popescu-v commented on .github/workflows/tests.yml
> +      image: ghcr.io/khiopsml/khiops-python/khiopspydev-ubuntu22.04:10.2.3-b.5.s3-gcs-remote-files
Ok.

2025-01-13 15:07 UTC, popescu-v commented on tests/test_remote_access.py
> +            # root_temp_dir
Add empty line before comment to make it a paragraph.

2025-01-13 15:08 UTC, popescu-v commented on tests/test_remote_access.py
> +            # root_temp_dir
Add empty line before comment to make it a paragraph.

2025-01-15 12:45 UTC, folmos-at-orange commented on tests/test_remote_access.py
> +            are released as conda packages
I still see `Temporary` (-> `Temporarily`)

2025-01-15 12:52 UTC, folmos-at-orange commented on tests/test_remote_access.py
> +
I created the issue https://github.com/KhiopsML/khiops-python/issues/328.

**You may resolve this once you have read this message**

2025-01-15 12:57 UTC, folmos-at-orange requested changes

2025-01-15 12:57 UTC, folmos-at-orange commented on setup.py
>      )
The `pyopenssl` dependency should go in the `s3` list, as it only affects the `boto3` extra.

2025-01-15 12:57 UTC, folmos-at-orange commented on tests/test_remote_access.py
> +            """
Titles should fit the line.

The title is the minimal summary. If there are more details put in in the body.

2025-01-15 12:57 UTC, folmos-at-orange commented on tests/test_remote_access.py
> +        """
I think this is `#` comment, not a docstring.

2025-01-15 13:58 UTC, popescu-v commented on run_fake_remote_file_servers.sh
I also fail to see the need for this top-level symlink to the real file which is in the `packaging/docker/khiopspydev` directory, and which is copied, in the `Dockerfile`, to the in-container `/scripts` directory.

2025-01-15 14:06 UTC, popescu-v commented on packaging/docker/khiopspydev/Dockerfile.ubuntu
> +COPY ./run_fake_remote_file_servers.sh /scripts/run_fake_remote_file_servers.sh
Conflate with line n° 57 into ( the trailing `/` for the destination directory is needed when copying several files IIRC):

```sh
COPY ./run_service.sh ./run_fake_remote_servers.sh /scripts/
```

2025-01-15 16:25 UTC, tramora commented on packaging/docker/khiopspydev/Dockerfile.ubuntu
> +COPY ./run_fake_remote_file_servers.sh /scripts/run_fake_remote_file_servers.sh
layers optimization done

2025-01-15 16:25 UTC, tramora commented on tests/test_remote_access.py
> +        """
Fixed

2025-01-15 16:25 UTC, tramora commented on tests/test_remote_access.py
> +            """
Fixed

2025-01-15 16:26 UTC, tramora commented on setup.py
>      )
Fixed

2025-01-15 16:26 UTC, tramora commented on .github/workflows/tests.yml
> +          GITHUB_WORKSPACE: ${{ github.workspace }}
Fixed

2025-01-15 16:26 UTC, tramora commented on tests/test_remote_access.py
> +            print(
Fixed

2025-01-15 16:26 UTC, tramora commented on tests/test_remote_access.py
> +            # root_temp_dir
Fixed

2025-01-15 16:26 UTC, tramora commented on tests/test_remote_access.py
> +            # root_temp_dir
Fixed

2025-01-15 16:28 UTC, tramora commented on packaging/docker/khiopspydev/Dockerfile.ubuntu
> +# You will have to add the `add-hosts` input instead (https://github.com/docker/build-push-action/#inputs)
Unfortunately as stated in the comment, the modification /etc/hosts is not possible here as buildx will mount the / filesystem readonly.

2025-01-15 18:04 UTC, folmos-at-orange approved these changes

2025-01-15 18:09 UTC, popescu-v commented on packaging/docker/khiopspydev/Dockerfile.ubuntu
> +# You will have to add the `add-hosts` input instead (https://github.com/docker/build-push-action/#inputs)
Ok.

2025-01-15 18:20 UTC, popescu-v requested changes
Address https://github.com/KhiopsML/khiops-python/pull/210#discussion_r1891415778.

Shorten commit message of https://github.com/KhiopsML/khiops-python/pull/210/commits/2dbb34e66dfa9edd41d02f89c9fbb7573f752323 to "Update copy_from_local and copy_to_local for S3".

2025-01-16 12:23 UTC, tramora commented
> Address [#210 (comment)](https://github.com/KhiopsML/khiops-python/pull/210#discussion_r1891415778).
> 
> Shorten commit message of [2dbb34e](https://github.com/KhiopsML/khiops-python/commit/2dbb34e66dfa9edd41d02f89c9fbb7573f752323) to something like "Update copy_from_local and copy_to_local for S3".

Both issues addressed

2025-01-30 16:46 UTC, popescu-v commented on .github/workflows/tests.yml
> +          # that every GCS client can read must also be set
For the time being, we cannot use any known available fake GCS server, as they are not supported. Hence, I would remove these comment lines.

2025-01-30 16:49 UTC, popescu-v commented on .github/workflows/tests.yml
> +          token_format: access_token
Why is this line needed here, whereas in https://github.com/KhiopsML/khiopsdriver-gcs/blob/main/.github/workflows/pack-conda.yml#L112 it is not?

2025-01-31 11:49 UTC, tramora commented on .github/workflows/tests.yml
> +          token_format: access_token
Requesting an OAuth2 https://github.com/google-github-actions/auth?tab=readme-ov-file#inputs-generating-oauth-20-access-tokens had the border advantage of failing at this authentication step if the google service account is misconfigured. The feeback is a few minutes later (during the tests) otherwise but OK to remove this call.

2025-01-31 12:16 UTC, tramora commented on .github/workflows/tests.yml
> +          # that every GCS client can read must also be set
The comments were removed

2025-01-31 14:53 UTC, popescu-v commented on .github/workflows/tests.yml
> +          # for the tests with S3
Move this comment one line above.

2025-01-31 14:54 UTC, popescu-v commented on .github/workflows/tests.yml
> +          # common var for tests with GCS & S3
Update comment to something like: `# Var for tests with S3` (it does not apply to GCS anymore AFAIU).

2025-01-31 14:57 UTC, popescu-v commented on .github/workflows/tests.yml
> +          token_format: access_token
Ok.

2025-01-31 16:01 UTC, popescu-v commented on packaging/docker/khiopspydev/run_fake_remote_file_servers.sh
> +#!/bin/bash
Rename file to "run_fake_s3_remote_file_server.sh".

2025-01-31 17:02 UTC, tramora commented on .github/workflows/tests.yml
> +          # common var for tests with GCS & S3
Fixed

2025-01-31 17:03 UTC, tramora commented on .github/workflows/tests.yml
> +          # for the tests with S3
Fixed

2025-01-31 17:09 UTC, popescu-v commented on tests/test_remote_access.py
>              self.skip_if_no_config()
IMHO we should skip these tests unless a specific environment variable is set via a specific CI workflow input (similar to the long tests switching). Thusly, we make sure these tests are run on-demand, whence avoiding to use the GCS bucket on each commit on each MR.

2025-02-03 14:43 UTC, tramora commented on tests/test_remote_access.py
>              self.skip_if_no_config()
reuse of the `skip_long_test` mechanism done (renamed to `skip_expensive_test`)

2025-02-03 16:03 UTC, popescu-v commented on tests/test_helper.py
>          if "UNITTEST_ONLY_SHORT_TESTS" in os.environ:
I would rename this variable to something like `SKIP_EXPENSIVE_TESTS`, while keeping the same execution semantics.

2025-02-04 13:19 UTC, tramora commented on .github/workflows/tests.yml
>          run: echo "UNITTEST_ONLY_SHORT_TESTS=true" >> "$GITHUB_ENV"
done

2025-02-04 13:19 UTC, tramora commented on tests/test_remote_access.py
> +            with suppress(FileNotFoundError):
done

2025-02-04 17:01 UTC, popescu-v approved these changes
LGTM.

However, https://github.com/KhiopsML/khiops-python/pull/210#discussion_r1907345903 needs to be taken into account before merging into `dev-v10`.

2025-02-05 09:30 UTC, merged