Use conda forge to build package
KhiopsML/khiops-python pull request #223
Opened 2024-08-02 14:21 UTC by popescu-v

closes #189

2024-08-04 16:26 UTC, folmos-at-orange requested changes

2024-08-04 16:26 UTC, folmos-at-orange commented on .github/workflows/conda.yml
> +      - name: Install Miniforge3
Just `Miniforge` (without `3`) and similarly all below

2024-08-04 16:26 UTC, folmos-at-orange commented on .github/workflows/unit-tests.yml
> +          /root/miniforge3/bin/conda install -y -n py${{ matrix.python-version }}_conda --file test-requirements.txt
Why use the full path? The documentation of setup-miniconda shows that you can just use `conda`. I'd change it in the CI worflow to improve readability.

2024-08-05 10:19 UTC, popescu-v commented on .github/workflows/conda.yml
> +      - name: Install Miniforge3
Ok.

2024-08-05 10:20 UTC, popescu-v commented on .github/workflows/unit-tests.yml
> +          /root/miniforge3/bin/conda install -y -n py${{ matrix.python-version }}_conda --file test-requirements.txt
It was just the minimal change with respect to what we had before. And it was to emphasize that we use the "Conda" that we installed, in the relevant directory.

But IMHO we can try to simplify this and just use `conda` in the PR that would deal with issue https://github.com/KhiopsML/khiops-python/issues/191.

2024-08-05 15:57 UTC, folmos-at-orange approved these changes

2024-08-19 15:36 UTC, popescu-v commented on .github/workflows/conda.yml
> +      - name: Install Miniforge3
Done.

2024-08-19 15:54 UTC, popescu-v commented on .github/workflows/unit-tests.yml
> +          /root/miniforge3/bin/conda install -y -n py${{ matrix.python-version }}_conda --file test-requirements.txt
> Why use the full path? The documentation of setup-miniconda shows that you can just use `conda`. I'd change it in the CI worflow to improve readability.

I have tried; it doesn't work: https://github.com/KhiopsML/khiops-python/actions/runs/10456619218/job/28954341545#step:8:18.

2024-08-22 15:34 UTC, folmos-at-orange commented on .github/workflows/unit-tests.yml
> +          /root/miniforge3/bin/conda install -y -n py${{ matrix.python-version }}_conda --file test-requirements.txt
Okay.

2024-10-07 14:27 UTC, folmos-at-orange requested changes

2024-10-07 14:27 UTC, folmos-at-orange commented on .github/workflows/unit-tests.yml
> +          /root/miniforge3/bin/conda install -y -n py${{ matrix.python-version }}_conda --file test-requirements.txt
I'd just add two environment variables to improve readability (I think we did a similar thing in khiops core)
```bash
CONDA="/root/miniforge3/bin/conda"
CONDA_ENVS="py${{ matrix.python-version }} py${{ matrix.python-version }}_conda"
for CONDA_ENV in "$CONDA_ENVS"
do
  mkdir -p -m "$CONDA_ENV"
  $CONDA install -y -n "$CONDA_ENV" unittest-xml-reporting
  $CONDA install -y -n "$CONDA_ENV" --file test-requirements.txt
done
```

2024-10-07 14:27 UTC, folmos-at-orange commented on .github/workflows/unit-tests.yml
> +          /root/miniforge3/bin/conda run --no-capture-output -n py${{ matrix.python-version }}_conda coverage xml -o "reports/py${{ matrix.python-version }}_conda/py-coverage.xml"
Same refactoring as above.

2024-10-14 15:31 UTC, popescu-v commented on .github/workflows/unit-tests.yml
> +          /root/miniforge3/bin/conda install -y -n py${{ matrix.python-version }}_conda --file test-requirements.txt
Ok & Done.

2024-10-14 15:31 UTC, popescu-v commented on .github/workflows/unit-tests.yml
> +          /root/miniforge3/bin/conda run --no-capture-output -n py${{ matrix.python-version }}_conda coverage xml -o "reports/py${{ matrix.python-version }}_conda/py-coverage.xml"
Ok & Done.

2024-10-14 16:05 UTC, folmos-at-orange approved these changes

2024-10-14 17:49 UTC, merged