191 test khiopspydev docker images before pushing them to the registry
KhiopsML/khiops-python pull request #226
Opened 2024-08-07 18:08 UTC by popescu-v

closes #191

2024-08-19 17:52 UTC, popescu-v commented
> If I understood well, the docker image for dev will be still named (and tagged) this way :
> 
> ```
> khiopspydev-<OS among ubuntu22.04 and rocky9>:<khiops revision>.<image revision, number starting from 0>
> 
> If the image is built against the dev or main git branches an additional "latest" tag is set
> ```
> 
> It seems that the image revision is set manuallly by the user. There may be a risk that 2 users set the same image revision and thus overwrite the image. But it may be an acceptable risk.

Yes, IMHO it is an acceptable risk. Otherwise, we would need a different mechanism for ensuring no override occurs, e.g. use the commit hash in / as the image revision part of the Docker image tag (less readable)?

2024-08-22 13:54 UTC, folmos-at-orange requested changes

2024-08-22 13:54 UTC, folmos-at-orange commented on .github/workflows/api-docs.yml
> +  DEFAULT_IMAGE_REVISION: latest
I'd uniformize the use of either `_TAG`(`-tag`) or '_REVISION' (`-revision`) in all workflows/jobs. I'm inclined to 'TAG' since it is shorter.

2024-08-22 13:54 UTC, folmos-at-orange commented on .github/workflows/dev-docker.yml
> +  DEFAULT_IMAGE_REVISION: 0
If the value is mandatory then we do not need a default value.

2024-08-22 13:54 UTC, folmos-at-orange commented on .github/workflows/api-docs.yml
> +          echo "Setting development Docker image tag"
This step is not necessary and it makes more complex the workflow. I'd just use
``${{ inputs.image-revision || env.DEFAULT_IMAGE_REVISION }}``.

2024-08-22 13:54 UTC, folmos-at-orange commented on .github/workflows/dev-docker.yml
> +      - name: Set up Docker image tags
`the Docker`

2024-08-22 13:54 UTC, folmos-at-orange commented on .github/workflows/pip.yml
> +      image-tag: ${{ inputs.image-revision || env.DEFAULT_IMAGE_REVISION }}
I'd just use the "or" incantation below instead of creating a job output. And in all jobs where you use this pattern.

2024-08-22 13:56 UTC, popescu-v commented on .github/workflows/api-docs.yml
> +          echo "Setting development Docker image tag"
I tried to, but it seems that `env` is not accessible here.

2024-08-22 13:57 UTC, popescu-v commented on .github/workflows/pip.yml
> +      image-tag: ${{ inputs.image-revision || env.DEFAULT_IMAGE_REVISION }}
At the beginning, I had tried to, but it seems that `env` is not accessible there.

2024-08-22 13:57 UTC, popescu-v commented on .github/workflows/dev-docker.yml
> +      - name: Set up Docker image tags
Ok.

2024-08-22 13:59 UTC, popescu-v commented on .github/workflows/api-docs.yml
> +  DEFAULT_IMAGE_REVISION: latest
Yes; we should however pay attention to the fact that sometimes we talk about the last field, some other times we talk about the whole tag x.y.z.REVISION. So, I would use TAG for the full tag and REVISION for its last field. But I would re-check all usages to make sure we're consistent here.

2024-08-22 14:35 UTC, folmos-at-orange commented on .github/workflows/dev-docker.yml
> +  DEFAULT_IMAGE_REVISION: 0
After offline discussion this value is ok but it will be renamedto `DEFAULT_IMAGE_INCREMENT`

2024-08-22 15:41 UTC, popescu-v commented on .github/workflows/api-docs.yml
> +  DEFAULT_IMAGE_REVISION: latest
Done: `INCREMENT` in `dev-docker` for the last part of the tag; `TAG` in the other workflows for the whole image tag.

2024-08-22 15:42 UTC, popescu-v commented on .github/workflows/dev-docker.yml
> +  DEFAULT_IMAGE_REVISION: 0
Done. Kept the default value and removed the mandatory requirement.

2024-08-22 15:42 UTC, popescu-v commented on .github/workflows/api-docs.yml
> +          echo "Setting development Docker image tag"
Done everywhere needed.

2024-08-22 15:45 UTC, popescu-v commented on .github/workflows/dev-docker.yml
> +      - name: Set up Docker image tags
Done.

2024-08-22 15:45 UTC, popescu-v commented on .github/workflows/pip.yml
> +      image-tag: ${{ inputs.image-revision || env.DEFAULT_IMAGE_REVISION }}
This is now moot, as the `env` is not used anymore in this context (see above).

2024-08-22 16:07 UTC, folmos-at-orange approved these changes

2024-08-23 10:59 UTC, folmos-at-orange approved these changes

2024-08-23 11:36 UTC, merged