While preprocessing the datatable format specification remove any ambiguity
KhiopsML/khiops-python pull request #230
Opened 2024-08-19 12:09 UTC by tramora

Should (partially) address the issue #208. The remaining fix must be done in `khiops-api-base`

2024-08-19 12:40 UTC, popescu-v commented on khiops/core/api.py
> +    if header_line or (field_separator is not None and field_separator != ""):
IMHO, the condition can be simplified to `if header_line or field_separator`. Indeed, if `field_separator` is truthy, it means that it cannot be `None` or the empty string; conversely, if `field_separator` is `None` or the empty string, then it would be falsy.

2024-08-19 12:44 UTC, popescu-v commented on khiops/core/api.py
> +        header_line = False
IMHO, the documentation should also be updated accordingly, if this is the desired behavior: in https://khiopsml.github.io/khiops-python/core/generated/khiops.core.api.html#module-khiops.core.api, the behavior of this flag can be clarified IMHO.

2024-08-19 12:45 UTC, popescu-v commented on khiops/core/api.py
> +        detect_format = False
IMHO, the documentation should be updated accordingly in https://khiopsml.github.io/khiops-python/core/generated/khiops.core.api.html#module-khiops.core.api : replace "it's ignored" with "it's set to `False`".

2024-08-19 12:53 UTC, popescu-v commented on tests/test_core.py
> +    A context to mock the low level `~.KhiopsLocalRunner.raw_run` function (by default)
I would try to use the `ScenarioWriteRunner` instead of mocking the high-level `run`, knowing that `task_args` are used for writing the scenarios: in that runner class, a specialized implementation of "high-level" `run` method exists already. I would try to update it, and the associated tests, for that matter.

2024-08-19 12:55 UTC, popescu-v requested changes
See comments.

2024-08-19 16:19 UTC, tramora commented on khiops/core/api.py
> +    if header_line or (field_separator is not None and field_separator != ""):
Simplified

2024-08-19 16:19 UTC, tramora commented on khiops/core/api.py
> +        detect_format = False
Documentation updated

2024-08-19 16:22 UTC, tramora commented
I just noticed that @folmos-at-orange has already worked on this subject and created the [related branch](https://github.com/KhiopsML/khiops-python/tree/208-detect_format-is-not-ignored-when-headerline-and-separator-are-provided).
The 2 drafts are surely conflicting

2024-08-20 08:59 UTC, tramora commented on tests/test_core.py
> +    A context to mock the low level `~.KhiopsLocalRunner.raw_run` function (by default)
I seemed better and simplier to me to check the tasks args values before writing the scenario but you are right using the `ScenarioWriterRunner` will test all the process. It's cleaner afterwards and uses an existing runner for tests.
I rolled back the changes in `MockedRunnerContext` and adapted the test.

2024-08-20 13:34 UTC, popescu-v commented on .pre-commit-config.yaml
> +        additional_dependencies: [maison<2.0.0]
IMHO, this should be in a separate commit (it is extraneous to the scope of the current PR, although needed).

2024-08-20 13:37 UTC, popescu-v commented on khiops/core/api.py
> +        task_args.get("detect_format", True),
Why do we need to enforce the `True` by default here? The default `True` value of the `detect_format` kwarg of the API functions is not enough?

2024-08-20 14:28 UTC, popescu-v commented on tests/test_core.py
> +            }
OK for now. Once Python 3.8 is dropped, we should be able to simplify this snippet to:

```python
merged_kwargs = {
    "additional_data_tables": {
        "Accident`Vehicles": "/tmp/Vehicules.txt"
    },
    "max_trees": 0,
} | test[1]
```
Perhaps adding a `TODO` comment in this respect would be useful?

2024-08-22 09:01 UTC, tramora commented on .pre-commit-config.yaml
> +        additional_dependencies: [maison<2.0.0]
You are right, I splitted it in a different commit

2024-08-22 09:06 UTC, tramora commented on khiops/core/api.py
> +        task_args.get("detect_format", True),
It was a preparation of the change in the `khiops-api-base` (call of the `kh._preprocess_tasks_arguments` function) where I was not sure a default value of `detect_format` was set.

By the way I also fixed a problem for tasks that do not have format_spec in their signature.

2024-08-22 09:06 UTC, tramora commented on tests/test_core.py
> +            #     -> 'header_line': False, 'field_separator': '', defect_format: False
Fixed. Hopefully it was only in the comments

2024-08-22 09:07 UTC, tramora commented on tests/test_core.py
> +            }
You are right. I added the comment.

2024-09-24 13:04 UTC, tramora commented
To be closed as duplicated PR #234

2024-09-24 13:04 UTC, closed without merging