Factor out Khiops and task argument preprocessing in a public function
KhiopsML/khiops-python pull request #234
Opened 2024-08-28 16:35 UTC by popescu-v

closes #208

2024-08-28 17:04 UTC, folmos-at-orange commented on khiops/core/api.py
> +def preprocess_arguments(args):
For better locality move after `_run_task` and before `_preprocess_task_arguments`.

2024-08-28 17:09 UTC, folmos-at-orange commented on khiops/core/api.py
> +    (`CommandLineOptions` instance, bool) tuple, with:
The pattern in this type of documentation is 
```
tuple
    A 2-tuple containing:
    - A `~.CommandLineOptions` instance
    - A `bool` that is ``True`` whether the `dictionary_file_or_domain` is a `~.DictionaryDomain` instance
```

See for example `train_predictor`.

2024-08-28 17:10 UTC, folmos-at-orange commented on khiops/core/api.py
> +def preprocess_arguments(args):
Also, since this refactoring is only to acomodate `khrun` (which will be replaced) I'd mark the function as private (`_` prefix).

2024-08-28 17:12 UTC, folmos-at-orange commented on khiops/core/api.py
> +    return (command_line_options, task_is_called_with_domain)
The parentheses are not necessary.

2024-08-28 17:13 UTC, folmos-at-orange requested changes
See above.

2024-08-28 17:14 UTC, popescu-v commented on khiops/core/api.py
> +    (`CommandLineOptions` instance, bool) tuple, with:
Yes, right, my bad. I would fix this.

2024-08-28 17:14 UTC, popescu-v commented on khiops/core/api.py
> +    return (command_line_options, task_is_called_with_domain)
Indeed; I would remove them.

2024-08-28 17:16 UTC, popescu-v commented on khiops/core/api.py
> +def preprocess_arguments(args):
> For better locality move after `_run_task` and before `_preprocess_task_arguments`.

Ok.

2024-08-28 17:20 UTC, popescu-v commented on khiops/core/api.py
> +def preprocess_arguments(args):
> Also, since this refactoring is only to acomodate `khrun` (which will be replaced) I'd mark the function as private (`_` prefix). We will probably defactor this in the future.

Yeah, we could still use it while it is necessary, then de-factor it, indeed. However, having it public and properly documented would help with code understanding a(nd reuse as well), IMHO.

2024-08-28 17:28 UTC, folmos-at-orange commented on khiops/core/api.py
> +def preprocess_arguments(args):
This will be used only once in code that is not public. It is refactored only for convenience but is not part of the API (even the "internals" API).

2024-08-28 17:46 UTC, popescu-v commented on khiops/core/api.py
> +    (`CommandLineOptions` instance, bool) tuple, with:
Done.

2024-08-28 17:48 UTC, popescu-v commented on khiops/core/api.py
> +def preprocess_arguments(args):
Done for the first point. Not convinced for the second point (see my comment above).

2024-08-28 17:48 UTC, popescu-v commented on khiops/core/api.py
> +    return (command_line_options, task_is_called_with_domain)
Done.

2024-08-28 18:25 UTC, popescu-v commented on khiops/core/api.py
> +def preprocess_arguments(args):
Done & Done (both points).

2024-08-29 09:16 UTC, folmos-at-orange approved these changes

2024-08-29 15:10 UTC, popescu-v commented
Pushed alpha tag 10.2.2.5-a.1 on the feature branch of this PR.

2024-10-07 14:52 UTC, tramora commented
Thank you for the change.

I used this pre-release as a base for modifications in a POC version of `khiops-api-base/kh-run`

Indeed eventually it fixed the customer issue : https://github.com/KhiopsML/khiops/issues/345 because it now produces these directives 
```
TrainDatabase.HeaderLineUsed true
TrainDatabase.FieldSeparator
```
instead of the previous ones 
```
TrainDatabase.HeaderLineUsed true
TrainDatabase.FieldSeparator 
TrainDatabase.DatabaseFormatDetector.DetectFileFormat
```
So we do not face any longer the issue khiops core must fix in the next release.

A few remarks though we may have discussed already :

## Public function to use

Both `khiops.core.api._preprocess_arguments` and `khiops.core.api._preprocess_tasks_arguments` have the private _ prefix and thus by convention are not officially exposed. 

In `khiops-api-base/kh-run`  the second `khiops.core.api._preprocess_tasks_arguments` is to be used in a loop of the `api_calls`.

## Asserts & default values

Because of asserts in code, the caller has the burden to set the default values of the 2 parameters `header_line` and `field_separator` along with `detect_format` before calling the API. It would have been nice if the API could handle the "business rules" internally.

## Semantic

The initial input protobuf payload contains only the `detect_format=True` param. It is quite surprising to end with a `HeaderLineUsed true` in the generated scenario even if the docstring states it clearly (I was forced to set the default values of `header_line` and `field_separator`)

```
It's ignored if ``header_line`` or ``field_separator`` are set.
```

2024-10-14 14:10 UTC, tramora commented
As the produced output was incorrect (see the previous comment about the semantic), I tweaked in the last commit the `khiops-api-base/kh-run` code in order to both keep the semantic and to try to avoid ambiguity for khiops.

However the ambiguities remain (in **bold** below) and we are waiting for a khiops release to fix the issue https://github.com/KhiopsML/khiops/issues/345 about the `DetectFileFormat` 

| Input to `khiops-api-base/kh-run`| Output to khiops after processing by the API | Notes |
|---|---|---|
|*no input*|defect_format=True, header_line=True, field_separator=''|**Room for improvement here (for human readers) : set header_line to False as detect_format will take precedence**|
| header_line=True|defect_format=False, header_line=True, field_separator=''|
|field_separator=','|defect_format=False, header_line=True, field_separator=','|**Room for improvement here, header_line should be left False as it does not correlate with the modified field**|
| detect_format=True|defect_format=True, header_line=True, field_separator=''|**Room for improvement here (for human readers) : set header_line to False as detect_format will take precedence**|
| detect_format=True, field_separator=',' |defect_format=False, header_line=True, field_separator=','|**Room for improvement here, header_line should be left False as it does not correlate with the modified field**|

2024-10-21 15:07 UTC, popescu-v commented
> Thank you for the change.
> 
> I used this pre-release as a base for modifications in a POC version of `khiops-api-base/kh-run`
> 
> Indeed eventually it fixed the customer issue : [KhiopsML/khiops#345](https://github.com/KhiopsML/khiops/issues/345) because it now produces these directives
> 
> ```
> TrainDatabase.HeaderLineUsed true
> TrainDatabase.FieldSeparator
> ```
> 
> instead of the previous ones
> 
> ```
> TrainDatabase.HeaderLineUsed true
> TrainDatabase.FieldSeparator 
> TrainDatabase.DatabaseFormatDetector.DetectFileFormat
> ```
> 
> So we do not face any longer the issue khiops core must fix in the next release.
> 
> A few remarks though we may have discussed already :
> ## Public function to use
> 
> Both `khiops.core.api._preprocess_arguments` and `khiops.core.api._preprocess_task_arguments` have the private _ prefix and thus by convention are not officially exposed.
> 
> In `khiops-api-base/kh-run` the second `khiops.core.api._preprocess_task_arguments` is to be used in a loop of the `api_calls`.
> 
> Branch : https://gitlab.tech.orange/khiops/khiops-api-base/-/tree/preprocess_task_arguments?ref_type=heads
> ## Asserts & default values
> 
> Because of asserts in code, the caller has the burden to set the default values of the 2 parameters `header_line` and `field_separator` along with `detect_format` before calling the API. It would have been nice if the API could handle the "business rules" internally.
> ## Semantic
> 
> The initial input protobuf payload contains only the `detect_format=True` param. It is quite surprising to end with a `HeaderLineUsed true` in the generated scenario even if the docstring states it clearly (I was forced to set the default values of `header_line` and `field_separator`).
> 
> ```
> (detect_format) ignored if ``header_line`` or ``field_separator`` are set.
> ```

Yes, here it should be ```is set to ``False`` if `header_line`` or ``field_separator`` are set```. On the other hand, if `header_line None`, then `header_line` is set to `True` in all cases; this where the documentation seems inexact, as it states that this should be the case only if `detect_format` is set to `False`.

2024-10-23 12:57 UTC, folmos-at-orange requested changes

2024-10-23 12:57 UTC, folmos-at-orange commented on khiops/core/api.py
> +        - It transforms the field separator "\\t" to the empty string ""
The second `\` is not necessary: we are in a raw string `r"..."`

2024-10-23 12:57 UTC, folmos-at-orange commented on khiops/core/api.py
> +        effect as "\\t". Sets ``detect_format`` to ``False`` if set.
I'd keep the old phrasing of the default value ("default `True` if ..."). This way the user is immediately informed about the default value and doesn't have to look below for the side effect.

I'm ok with the "Sets `detect_format` .. to ``False``" change.

2024-10-23 12:57 UTC, folmos-at-orange commented on khiops/core/api.py
General comment on the doc commit: Why the message says that in _now_ reflects the current behavior? It is just a rephrasing.

2024-10-23 12:57 UTC, folmos-at-orange commented on khiops/core/api.py
> +        - It transforms the field separator "\\t" to the empty string ""
And all below.

2024-10-23 12:57 UTC, folmos-at-orange commented on .github/workflows/api-docs.yml
> +        default: 10.2.3-b.5.0
General Comment: I'd rephrase the commit
Set _in CI_ Khiops core packages version to the latest beta

2024-10-23 13:28 UTC, popescu-v commented on khiops/core/api.py
IMHO, no: before it was stated that:
- `detect_format` is ignored if at least one of `header_line` or `field_separator` is set; whereas, in reality, it set to `False`, which has the consequence of not performing automatic format detection on the binary Khiops side.
- `header_line` has `True` as default value, which is not strictly true, because the default value is `None`, in which case the attribute is set to `True` *afterwards*; the current discourse seems misleading, in that it creates the expectation that the default value is `True`;
- similar situation for `field_separator`, where the default value is not "\t", but `None`, in which case the attribute is set to "" *afterwards*; and "\t" and "" are equivalent *for the Khiops binaries* only.

So, the goal of this commit is to make sure the documentation reflects current behavior and semantics.

2024-10-23 13:29 UTC, popescu-v commented on .github/workflows/api-docs.yml
> +        default: 10.2.3-b.5.0
Yes, OK for the addition, thus the intent is clearer.

2024-10-23 13:33 UTC, popescu-v commented on khiops/core/api.py
> +        effect as "\\t". Sets ``detect_format`` to ``False`` if set.
IMHO, it is better that the documentation reflects *exactly* the behavior (w/o shortcuts); otherwise, it seems misleading (see the other related comment). So, I would keep `None` as default value, with the statement of the side effect: longer-winded, but more correct IMHO. And IMHO this becomes even more important for client usage.

As for breaking the pattern for `header_line`: IMHO we are obliged to do so, in order to establish the "link" between the default `None` and the consequent default `True` as a side-effect. Otherwise, the documentation is not faithful to the implemented behavior IMHO.

2024-10-23 13:34 UTC, popescu-v commented on khiops/core/api.py
> +        - It transforms the field separator "\\t" to the empty string ""
Ok, I will recheck in all cases and change where mandated by the `r"..."`.

2024-10-23 13:39 UTC, popescu-v commented on khiops/core/api.py
> +        - It transforms the field separator "\\t" to the empty string ""
Done.

2024-10-23 13:45 UTC, popescu-v commented on .github/workflows/api-docs.yml
> +        default: 10.2.3-b.5.0
Done.

2024-10-23 15:04 UTC, popescu-v commented on khiops/core/api.py
> +        effect as "\\t". Sets ``detect_format`` to ``False`` if set.
Done as discussed.

2024-10-23 15:04 UTC, popescu-v commented on khiops/core/api.py
Removed the "reflects the current behavior" part.

2024-10-23 15:24 UTC, tramora commented
Go for it for this PR despite the ambiguities remaining : https://github.com/KhiopsML/khiops-python/pull/234#issuecomment-2411385695

However the issue https://github.com/KhiopsML/khiops/issues/345 on the khiops core side is not fixed yet (in `10.2.3-b.5`) so the final state remains the same.

2024-10-23 15:25 UTC, tramora approved these changes

2024-10-23 15:26 UTC, folmos-at-orange requested changes

2024-10-23 15:26 UTC, folmos-at-orange commented on khiops/core/api.py
> +    field_separator : str, optional (default "")
Set the default value to `\t` as before. Again, this _is_ its semantic value. And all below.

2024-10-23 15:26 UTC, folmos-at-orange commented on khiops/core/api.py
> +        is set to ``True``.
-> ```Ignored if ``detect_format`` is ``True`` ```.

2024-10-23 16:23 UTC, popescu-v commented on khiops/core/api.py
> +    field_separator : str, optional (default "")
Ok & Done.

2024-10-23 16:24 UTC, popescu-v commented on khiops/core/api.py
> +        is set to ``True``.
Ok & Done.

2024-10-23 17:28 UTC, merged