71 add khiops parameters to predictor constructors
KhiopsML/khiops-python pull request #242
Opened 2024-09-10 12:59 UTC by nairbenrekia

2024-09-16 04:22 UTC, folmos-at-orange requested changes
In addition to the coments, we add the new parameters to the `test_sklearn.KhiopsSklearnParameterPassingTests` test suite.

2024-09-16 04:22 UTC, folmos-at-orange commented on khiops/samples/samples_sklearn.py
> +
Remove this empty line.

2024-09-16 04:22 UTC, folmos-at-orange commented on khiops/sklearn/estimators.py
> +
Remove this empty line.

2024-09-16 04:22 UTC, folmos-at-orange commented on khiops/sklearn/estimators.py
> +        n_selected_features=0,
I'd reverse the order of these two, as the second one in more important (even more important in future versions).

We should do this in all three signatures and its documentation.

2024-09-16 04:22 UTC, folmos-at-orange commented on khiops/sklearn/estimators.py
> +    keep_initial_features : bool, default ``False``
The parameters must be in the same order as the signature. So, for example, `transform_pairs` should go after the other `transform` paramaters.

2024-09-16 10:39 UTC, nairbenrekia commented on khiops/samples/samples_sklearn.py
> +
Ok.

2024-09-16 10:41 UTC, nairbenrekia commented on khiops/sklearn/estimators.py
> +
Ok.

2024-09-16 13:54 UTC, nairbenrekia commented on khiops/sklearn/estimators.py
> +        n_selected_features=0,
Ok.

2024-09-16 16:05 UTC, nairbenrekia commented on khiops/sklearn/estimators.py
> +    keep_initial_features : bool, default ``False``
Ok. I changed the order of transform_pairs in the definitions and the constructor. There is no misalignment in the order. Unless, you would like an alignment with the signature of estimators in Khiops-Core.

2024-09-16 16:10 UTC, nairbenrekia commented on khiops/sklearn/estimators.py
> +        keep_initial_features=False,
Ok.

2024-10-09 05:06 UTC, folmos-at-orange requested changes

2024-10-10 10:30 UTC, nairbenrekia commented on khiops/sklearn/estimators.py
> +        kwargs["construction_rules"] = kwargs.pop("construction_rules")
Ok.

2024-10-10 10:31 UTC, nairbenrekia commented on khiops/sklearn/estimators.py
> +        0 it selects all the features kept in the training.
Ok.

2024-10-10 10:35 UTC, nairbenrekia commented on khiops/sklearn/estimators.py
> +        0 it selects all the features kept in the training.
Ok.

2024-10-10 11:04 UTC, nairbenrekia commented on khiops/sklearn/estimators.py
> +        kwargs["group_target_value"] = kwargs.pop("group_target_value")
Ok.

2024-10-22 14:30 UTC, popescu-v commented on khiops/samples/samples_sklearn.py
> +def khiops_classifier_advanced():
I would update the name to a more explicit one; something like `khiops_classifier_with_hyperparameters`?

2024-10-22 14:31 UTC, popescu-v commented on khiops/samples/samples_sklearn.py
> +def khiops_encoder_advanced():
Rename to `khiops_encoder_with_hyperparameters` (also see comment above)?

2024-10-22 14:32 UTC, popescu-v commented on khiops/sklearn/estimators.py
> +            if not isinstance(self.specific_pairs, list):
Rather `if not is_list_like(self.specific_pairs)` ?

2024-10-22 14:33 UTC, popescu-v commented on khiops/sklearn/estimators.py
> +                    type_error_message("specific_pairs", self.specific_pairs, list)
`"''list-like"` instead of `list`?

2024-10-22 14:34 UTC, popescu-v commented on khiops/sklearn/estimators.py
> +                )
Why not "list-like" instead of the precise `list` (see comments above)?

2024-10-23 10:25 UTC, nairbenrekia commented on khiops/samples/samples_sklearn.py
> +def khiops_classifier_advanced():
Ok.

2024-10-23 10:25 UTC, nairbenrekia commented on khiops/samples/samples_sklearn.py
> +def khiops_encoder_advanced():
Ok.

2024-10-23 10:27 UTC, nairbenrekia commented on khiops/sklearn/estimators.py
> +            if not isinstance(self.specific_pairs, list):
Ok if you prefer !

2024-10-23 10:27 UTC, nairbenrekia commented on khiops/sklearn/estimators.py
> +                    type_error_message("specific_pairs", self.specific_pairs, list)
Ok if you prefer !

2024-10-23 10:36 UTC, nairbenrekia commented on khiops/sklearn/estimators.py
> +            if not isinstance(self.specific_pairs, list):
Yes. I would also relax this constraint.

2024-10-23 10:36 UTC, nairbenrekia commented on khiops/sklearn/estimators.py
> +                    type_error_message("specific_pairs", self.specific_pairs, list)
Yes. I would also relax this constraint.

2024-10-23 10:36 UTC, nairbenrekia commented on khiops/sklearn/estimators.py
> +                )
Yes. I would also relax this constraint.

2024-10-23 11:35 UTC, popescu-v approved these changes

2024-10-23 11:37 UTC, merged