171 implement multi table helper functions (second round)
KhiopsML/khiops-python pull request #248
Opened 2024-09-18 16:25 UTC by folmos-at-orange

2024-10-21 16:16 UTC, popescu-v commented on doc/samples/samples.rst
> +.. autofunction:: sort_data_tables_mt
AFAIR, we should only have the `train_test_split` multi-table here, not the `sort`. Hence, this should be removed from the current PR and added to a different one I guess.

2024-10-21 16:18 UTC, popescu-v commented on doc/samples/samples_sklearn.rst
> +    from sklearn.datasets import load_iris
This goes beyond the scope of the PR IMHO.

2024-10-21 16:18 UTC, popescu-v commented on doc/samples/samples_sklearn.rst
> +    X, y = load_iris(return_X_y=True)
IMHO this helper should be in a different PR.

2024-10-21 16:25 UTC, popescu-v commented on khiops/core/internals/runner.py
> +def _check_samples_dir(samples_dir):
This should disappear after rebase on `dev`.

2024-10-21 16:28 UTC, popescu-v commented on khiops/samples/samples.py
> +def sort_data_tables_mt():
This should be in a different PR (the scope of the current PR is to only add the `train_test_split` multi-table).

2024-10-21 16:28 UTC, popescu-v commented on khiops/samples/samples.py
> +    sort_data_tables_mt,
Out of the scope of the current PR AFAIU.

2024-10-21 16:29 UTC, popescu-v commented on khiops/samples/samples_sklearn.py
> +    X, y = load_iris(return_X_y=True)
This helper seems of the scope of the current PR AFAIU.

2024-10-21 16:30 UTC, popescu-v commented on khiops/samples/samples_sklearn.py
> +    khe = KhiopsEncoder(transform_type_numerical="part_label")
Why is this change needed? Could you add a comment to explain?

2024-10-21 16:34 UTC, popescu-v commented on khiops/sklearn/estimators.py
>  def _check_dictionary_compatibility(
Why are these changes part of the scope of the current PR? It seems to me they are not. But if they are, they should occur in a separate, clearly-identified commit IMHO, which states the rationale of these changes being included in this PR.

2024-10-21 16:36 UTC, popescu-v commented on khiops/sklearn/estimators.py
> +        if deployment_ds.is_in_memory:
This change is out of the scope of the current PR AFAIU. If ancillary improvements are included in the PR, then they should be a in a separate commit or set of commits clearly identifying these changes as such and explaining the rationale for them.

2024-10-21 16:38 UTC, popescu-v commented on khiops/sklearn/estimators.py
> +        if ds.is_multitable:
Idem, this seems out of the scope of the PR. It should be included in a separate commit / set of commits stating the rationale for it.

2024-10-21 16:39 UTC, popescu-v commented on khiops/sklearn/estimators.py
> +                f"X has {len(ds_domain.dictionaries)} table(s), "
All these variable renamings should be in a separate commit for better "reviewability" of the PR (although they don't seem to be necessary to the PR).

2024-10-21 16:41 UTC, popescu-v commented on khiops/sklearn/estimators.py
> +        assert hasattr(
Why is this refactoring needed in this PR? If it is needed, then it should go in a separate commit (different from the commit that introduces the `train_test_split_dataset` helper) that explains the rationale.

2024-10-22 12:38 UTC, folmos-at-orange commented on doc/samples/samples_sklearn.rst
> +    from sklearn.datasets import load_iris
Ok

2024-10-22 12:40 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +def _check_samples_dir(samples_dir):
It did.

2024-10-22 12:40 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +    """Detect the Linux distribution name
It did

2024-10-22 12:40 UTC, folmos-at-orange commented on khiops/samples/samples_sklearn.py
> +    X, y = load_iris(return_X_y=True)
Ok

2024-10-22 12:42 UTC, folmos-at-orange commented on khiops/sklearn/estimators.py
>  def _check_dictionary_compatibility(
This change is ok after offline discussion.

2024-10-22 12:43 UTC, folmos-at-orange commented on khiops/sklearn/estimators.py
> +        if deployment_ds.is_in_memory:
This change is ok after offline discussion.

2024-10-22 12:43 UTC, folmos-at-orange commented on khiops/sklearn/estimators.py
> +        if ds.is_multitable:
This change is ok after offline discussion.

2024-10-22 13:02 UTC, popescu-v commented on khiops/utils/helpers.py
> +        raise ValueError("Only Pandas and Numpy datasets may be used in this method.")
I would slightly rephrase to "Only Pandas dataframe or NumPy array-based datasets can be used in this method."

2024-10-22 13:02 UTC, popescu-v commented on khiops/utils/helpers.py
> +        raise ValueError("Only Pandas and Numpy datasets may be used in this method.")
Also, this also works with sparse datasets, right? If so, then we should mention it, right?

2024-10-22 13:06 UTC, popescu-v commented on khiops/utils/helpers.py
> +        train_ds, test_ds = _train_test_split_in_memory_dataset(
IMHO, `_train_test_split_in_memory_dataset` should have the same return type (3-tuple) in all cases. If `y` is `None`, then the returned target could be also `None`.

Thus, the `if/else` block can be simplified: only `train_target_column = None` would remain in the `if y is None` block.

2024-10-22 13:44 UTC, popescu-v commented on khiops/samples/samples_sklearn.py
> +    khe = KhiopsEncoder(transform_type_numerical="part_label")
Isn't it `"part label"` as per the documentation (w/o underscore)?

2024-10-22 14:09 UTC, popescu-v commented on khiops/samples/samples_sklearn.py
> +    X_train, X_test = train_test_split_dataset(
`train_test_split_dataset` does not support file datasets. Hence, this sample should not be updated to using the new train/test split feature. Otherwise, the sample fails.

2024-10-22 14:14 UTC, popescu-v commented on khiops/utils/helpers.py
> +        A dataset spec. The tables must be either `pandas.DataFrame` or file path
Remove `"or file path references"` (these are not supported).

2024-10-22 14:21 UTC, popescu-v requested changes
See comments.

2024-10-23 06:58 UTC, folmos-at-orange commented on khiops/utils/helpers.py
> +        raise ValueError("Only Pandas and Numpy datasets may be used in this method.")
Ok

2024-10-23 06:58 UTC, folmos-at-orange commented on khiops/samples/samples_sklearn.py
> +    X_train, X_test = train_test_split_dataset(
Ok for remove & Done

2024-10-23 07:06 UTC, folmos-at-orange commented on khiops/samples/samples_sklearn.py
> +    khe = KhiopsEncoder(transform_type_numerical="part_label")
Yes, the encoded variables are the intervals, so it is more pedagogical.

2024-10-23 07:10 UTC, folmos-at-orange commented on khiops/samples/samples_sklearn.py
> +    X, y = load_iris(return_X_y=True)
Done

2024-10-23 07:10 UTC, folmos-at-orange commented on doc/samples/samples_sklearn.rst
> +    X, y = load_iris(return_X_y=True)
Done

2024-10-23 07:15 UTC, folmos-at-orange commented on doc/samples/samples_sklearn.rst
> +    from sklearn.datasets import load_iris
Reversion Done

2024-10-23 07:28 UTC, folmos-at-orange commented on khiops/utils/helpers.py
> +        train_ds, test_ds = _train_test_split_in_memory_dataset(
Ok & Done.

I left the 2-tuple or 4-tuple pattern only the return of the `train_test_split_dataset` so it matches that of sklearn.

2024-10-23 07:28 UTC, folmos-at-orange commented on khiops/utils/helpers.py
> +        raise ValueError("Only Pandas and Numpy datasets may be used in this method.")
Added `Scipy sparse`, Done.

2024-10-23 09:36 UTC, popescu-v commented on khiops/samples/samples_sklearn.py
> +    khe = KhiopsEncoder(transform_type_numerical="part_label")
Ok, fair enough.

2024-10-23 09:37 UTC, popescu-v commented on khiops/utils/helpers.py
> +        train_ds, test_ds = _train_test_split_in_memory_dataset(
Yes, ok for keeping the 2-/4- tuple pattern for the public helper.

2024-10-23 10:11 UTC, folmos-at-orange commented on khiops/utils/helpers.py
> +        A dataset spec. The tables must be either `pandas.DataFrame` or file path
Ok.

I uniformized with the docstring of estimators, added the file-path caveat and added a `Raises` section.

2024-10-23 11:20 UTC, popescu-v commented on khiops/utils/helpers.py
> +         File-path based datasets are not accepted.
I would avoid negative phrasings, and rather eliminate this statement altogether, as file-path datasets are deprecated and would go away anyway. Instead, I would add a positive formulation that would match the error message: `Pandas, NumPy, SciPy sparse datasets are accepted.`

2024-10-23 11:23 UTC, popescu-v commented on khiops/utils/helpers.py
> +        A dataset spec. The tables must be either `pandas.DataFrame` or file path
OK, but see the other new comment on this. Closing this thread, as the new thread would remain.

2024-10-23 11:59 UTC, folmos-at-orange commented on khiops/utils/helpers.py
> +         File-path based datasets are not accepted.
Done rephrased.

2024-10-23 15:36 UTC, popescu-v commented on khiops/utils/helpers.py
> +         File-path based datasets are not accepted.
Ok, with the caveat to remove the `Only` once file datasets are removed (for v11).

2024-10-23 16:13 UTC, popescu-v approved these changes
LGTM.

2024-10-23 16:21 UTC, merged