Add set latest docker dev
KhiopsML/khiops-python pull request #249
Opened 2024-09-18 16:27 UTC by folmos-at-orange

2024-09-30 08:30 UTC, popescu-v commented on .github/workflows/dev-docker.yml
> +        default: '0'
I don't think we need quotes here (see above).

2024-09-30 08:32 UTC, popescu-v commented on .github/workflows/dev-docker.yml
> -          if [[ "$GITHUB_REF" == "refs/heads/main" || "$GITHUB_REF" == "refs/heads/dev" ]]
IMHO we want to be able to set the `latest` tag on request, *only when* on `main` or `dev` (i.e. when the feature branch has been merge). I don't think we want to be able to set `latest` on a feature branch, because `latest` being the default tag, other feature branches might still accidentally use a per-feature branch `latest`. So, I would reinstate the previous code and add the new condition as `&&`.

2024-09-30 08:33 UTC, popescu-v requested changes
See comments (among which one important one, IMHO).

2024-09-30 18:10 UTC, folmos-at-orange commented on .github/workflows/dev-docker.yml
> +  DEFAULT_IMAGE_INCREMENT: '0'
Ok, changed to number.

2024-09-30 18:10 UTC, folmos-at-orange commented on .github/workflows/dev-docker.yml
> +        default: '0'
Ok as above.

2024-09-30 18:18 UTC, folmos-at-orange commented on .github/workflows/dev-docker.yml
> -          if [[ "$GITHUB_REF" == "refs/heads/main" || "$GITHUB_REF" == "refs/heads/dev" ]]
Ok & done.

2024-10-07 13:46 UTC, popescu-v commented on .github/workflows/dev-docker.yml
> -          if [[ "$GITHUB_REF" == "refs/heads/main" || "$GITHUB_REF" == "refs/heads/dev" ]]
Ok, right.

2024-10-07 13:47 UTC, popescu-v commented on .github/workflows/dev-docker.yml
> +        default: '0'
Ok, good.

2024-10-08 09:10 UTC, popescu-v approved these changes
LGTM. Can be merged IMHO, via a merge commit.

2024-10-08 09:12 UTC, merged