245 support the new version of khiops env
KhiopsML/khiops-python pull request #252
Opened 2024-10-07 13:26 UTC by popescu-v

2024-10-08 10:12 UTC, folmos-at-orange requested changes

2024-10-08 12:43 UTC, popescu-v commented on khiops/core/internals/runner.py
> +        khiops_env_path += ".exe"
Yes indeed. Done.

2024-10-08 12:45 UTC, popescu-v commented on khiops/core/internals/runner.py
> +        instance.
> Refer the user in second person as it is usually shorter. For ex.
> 
> ```
> You may not set this value directly. Instead set the `KHIOPS_PROC_NUMBER` environment variable and then create another instance of `~.KhiopsLocalRunner`.
> ```
> 
> Also user `~` to shorten the links when cross referencing with Sphinx.

Ok & Done.

2024-10-08 12:46 UTC, popescu-v commented on khiops/core/internals/runner.py
> +        instance.
> Also, we could add an advanced `restart` method (later, as there is a "contournement"). For example, for large number small task it is faster to set the the number to `1` temporarily. This is because it avoids the MPI overhead.

This is for a different issue IMHO. Could you file it?

2024-10-08 12:53 UTC, popescu-v commented on khiops/core/internals/runner.py
>          stdout, _, return_code = self.raw_run("khiops", ["-v"], use_mpi=False)
Yes, after centralizing the environment intialization in `__init__` and local runner initialization in `get_runner`, this is moot.

2024-10-08 13:09 UTC, popescu-v commented on khiops/core/internals/runner.py
> +                command = shlex.split(f"bash -c '{khiops_env_path} --env'")
`shlex.split` should do a more "standards-compliant" split AFAIK; e.g. the part between single quotes `'` is atomic following the split.

2024-10-08 13:11 UTC, popescu-v commented on khiops/core/internals/runner.py
> +                command = f"cmd /C call {khiops_env_path} --env"
I would let `Popen` on Windows handle the spaces semantics including for cases when there are spaces in the path.

2024-10-08 13:11 UTC, popescu-v commented on khiops/core/internals/runner.py
> +                    # Set the Khiops process number according to the
Ok & Done.

2024-10-08 13:12 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +        instance.
After our offline discussion I do not think it is necessary.

2024-10-08 13:15 UTC, popescu-v commented on khiops/core/internals/runner.py
> +                        os.environ["KHIOPS_COCLUSTERING_PATH"] = var_value
Ok. Moved them at the top.

2024-10-08 13:15 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +                command = shlex.split(f"bash -c '{khiops_env_path} --env'")
Ok

2024-10-08 13:15 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +                command = f"cmd /C call {khiops_env_path} --env"
shlex doesn't work here ?

2024-10-08 13:20 UTC, popescu-v commented on khiops/core/internals/runner.py
> +                    # binaries
Ok & Done.

2024-10-08 13:34 UTC, popescu-v commented on khiops/core/internals/runner.py
> +            )
Yes, it is, in the sense that `KHIOPS_MPI_COMMAND` is set to `""`, but no warning is issued. Hence, I think we could drop the assignment of the empty list to `_mpi_command_args` here.

2024-10-08 13:51 UTC, popescu-v commented on khiops/core/internals/runner.py
> +            ) as khiops_process:
Ok & Done.

2024-10-08 13:52 UTC, popescu-v commented on khiops/core/internals/runner.py
> +    def _patch_path_to_mpi_command(self, installation_method):
Ok & Done.

2024-10-08 13:57 UTC, popescu-v commented on khiops/core/internals/runner.py
> +        self._check_tools()
Ok & Moved the check just after the parsing of `khiops_env`.

2024-10-08 14:02 UTC, popescu-v commented on khiops/core/internals/runner.py
>          status_msg += f"version         : {self._khiops_version}\n"
Yes, `_khiops_version` is not initialized beforehand. Irrespective of `khiops_env`, `_khiops_version` is initialized by `_get_khiops_version` which is called by the `khiops_version` property indeed. Hence:
- I changed to `self.khiops_version` and it works
- we can discuss whether `_khiops_version` should also be initialized from the outset (in `get_runner`) or not; if so, then we could file a different PR for this.

2024-10-08 14:03 UTC, popescu-v commented on khiops/core/internals/runner.py
> +            self._initialize_khiops_environment()
Yes, this should be moot now (see above).

2024-10-08 14:04 UTC, popescu-v commented on khiops/core/internals/runner.py
> +            self._initialize_khiops_environment()
Yes, this should be OK now (see above).

2024-10-08 14:08 UTC, popescu-v commented on khiops/core/internals/runner.py
> +        # Set the MODL_Coclustering path, check and initialize the version
Oh I see: we should reinstate the `_initialize_khiops_version` right after `_check_tools`. Whence, `self.khiops_version` should work.

2024-10-08 14:28 UTC, popescu-v commented on khiops/core/internals/runner.py
> +            self._initialize_khiops_environment()
Yes, this should now be moot (see above).

2024-10-08 15:29 UTC, popescu-v commented on doc/notes.rst
> +environment variables listed below. They can be split into two groups:
IMHO, it is useful to keep the distinction: the two variables "part of the Khiops API" are officially documented as such in `khiops_env`. The third one is not. IMHO, the minimal change for the scope of the current PR is to keep them separated in groups.

2024-10-08 15:30 UTC, popescu-v commented on doc/notes.rst
> +environment variables listed below. They can be split into two groups:
Added the remark that `KHIOPS_SAMPLES_DIR` is only for the Python library.

2024-10-08 16:14 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +        # Set the MODL_Coclustering path, check and initialize the version
I was more talking about the comment. It should not say anything about the version.

2024-10-08 16:22 UTC, popescu-v commented on khiops/core/internals/runner.py
> +        # Set the MODL_Coclustering path, check and initialize the version
Ok, I see. Removed that part.

2024-10-08 16:22 UTC, popescu-v commented on khiops/core/internals/runner.py
> +            )
Done.

2024-10-09 17:31 UTC, popescu-v commented on khiops/core/internals/runner.py
> +        # khiops_env is always in path for a proper installation
KHIOPS_HOME fallback for Windows native has been implemented. So has been CI test for this. So, this thread can be closed IMHO.

2024-10-09 17:32 UTC, popescu-v commented on khiops/core/internals/runner.py
> +                command = shlex.split(f"bash -c '{khiops_env_path} --env'")
Yes, done, with `[khiops_env_path, "--env"] as in the previous code.

2024-10-09 17:32 UTC, popescu-v commented on khiops/core/internals/runner.py
> +                command = f"cmd /C call {khiops_env_path} --env"
Yes, simplified all this (see above).

2024-10-09 17:41 UTC, popescu-v commented on doc/notes.rst
> +environment variables listed below. They can be split into two groups:
Ok & Done.

2024-10-10 08:53 UTC, folmos-at-orange requested changes

2024-10-10 08:53 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +            elif not os.path.exists(self._tool_path(tool_name)):
Looking at the implementation of `_tool_path` it never returns `None`.

2024-10-10 08:53 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +# Runner (backend) of Khiops Python, by default None
-> `by defaulte None for lazy initialization`

2024-10-10 08:53 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +
The lazy initialization is part of the implementation. So I would not document it.

2024-10-10 08:53 UTC, folmos-at-orange commented on tests/test_khiops_integrations.py
> +            and os.access(runner.khiops_coclustering_path, os.X_OK)
I would not use `and` and put the asserts separately so when they fail we know exactly why.

2024-10-10 08:53 UTC, folmos-at-orange commented on tests/test_sklearn.py
> +                    "check_estimators_dtypes",
This is an important test, we should not leave it out easily. Is there any easy way to fix this ?

2024-10-10 08:57 UTC, popescu-v commented on .github/workflows/api-docs.yml
> +        ghcr.io/khiopsml/khiops-python/khiopspydev-ubuntu22.04:${{ inputs.image-tag || '10.2.3-b.3.with_native_10.2.3-b.3' }}
IMHO, it should stay like now until Khiops (core) 10.2.3 is formally released. At that time, we should:
- rebuild the docker image on `dev` with tag `latest`, using `10.2.3` as `khiops-revision` / `DEFAULT_KHIOPS_REVISION`
- change, via a "squash merge" on `dev`, the image tag to `latest` on all relevant workflows og `khiops-python`.

2024-10-10 08:59 UTC, popescu-v commented on .github/workflows/unit-tests.yml
> +        description: Khiops Windows Desktop Application Release Version
Ok.

2024-10-10 08:59 UTC, popescu-v commented on .github/workflows/unit-tests.yml
> +          DEFAULT_KHIOPS_DESKTOP_REVISION: 10.2.3-b.3
Yes, right, it seems cleaner this way.

2024-10-10 09:00 UTC, popescu-v commented on .github/workflows/unit-tests.yml
> +          pip install -r test-requirements.txt
Yes, right.

2024-10-10 09:00 UTC, popescu-v commented on .github/workflows/unit-tests.yml
> +          # tooling
Ok.

2024-10-10 09:00 UTC, popescu-v commented on .github/workflows/unit-tests.yml
> +          # that update it
Ok with the rephrasing.

2024-10-10 09:01 UTC, popescu-v commented on .github/workflows/unit-tests.yml
> +          python -c "import khiops.core as kh; kh.get_runner().print_status()"
No, because the Khiops Python library is not installed in the environment (only the repo is cloned / checked out).

2024-10-10 09:01 UTC, popescu-v commented on khiops/core/internals/runner.py
> +        status_msg += f"executables dir : {os.path.dirname(self._khiops_path)}\n"
Yes, right.

2024-10-10 09:01 UTC, popescu-v commented on khiops/core/internals/runner.py
> +        Set by the upstream `khiops_env` script from the `khiops-core` package.
Ok.

2024-10-10 09:02 UTC, popescu-v commented on khiops/core/internals/runner.py
> +            elif not os.path.exists(self._tool_path(tool_name)):
Ok, I will look into this inconsistency.

2024-10-10 09:02 UTC, popescu-v commented on khiops/core/internals/runner.py
> +# Runner (backend) of Khiops Python, by default None
Ok.

2024-10-10 09:02 UTC, popescu-v commented on khiops/core/internals/runner.py
> +
Ok, fair enough.

2024-10-10 09:48 UTC, folmos-at-orange commented on tests/test_sklearn.py
> +                    "check_estimators_dtypes",
I think I found a way to resolve this exception: See https://github.com/KhiopsML/khiops-python/issues/256 .

We can close this thread.

2024-10-10 09:54 UTC, popescu-v commented on tests/test_khiops_integrations.py
> +            and os.access(runner.khiops_coclustering_path, os.X_OK)
Ok, it seems better this way, right.

2024-10-10 09:55 UTC, popescu-v commented on tests/test_sklearn.py
> +                    "check_estimators_dtypes",
I couldn't find one in a reasonable amount of time. But I would very well see an issue (and dedicated PR) to address this.

2024-10-10 10:05 UTC, popescu-v commented on .github/workflows/pip.yml
> +          kh-status | grep "MPI command" | grep -wq "mpiexec"
Done.

2024-10-10 10:06 UTC, popescu-v commented on .github/workflows/unit-tests.yml
> +        description: Khiops Windows Desktop Application Release Version
Done.

2024-10-10 10:06 UTC, popescu-v commented on .github/workflows/unit-tests.yml
> +          DEFAULT_KHIOPS_DESKTOP_REVISION: 10.2.3-b.3
Done.

2024-10-10 10:07 UTC, popescu-v commented on .github/workflows/unit-tests.yml
> +          pip install -r test-requirements.txt
Done.

2024-10-10 10:07 UTC, popescu-v commented on .github/workflows/unit-tests.yml
> +          # tooling
Done.

2024-10-10 10:08 UTC, popescu-v commented on .github/workflows/unit-tests.yml
> +          # that update it
Done.

2024-10-10 10:10 UTC, popescu-v commented on khiops/core/internals/runner.py
> +        status_msg += f"executables dir : {os.path.dirname(self._khiops_path)}\n"
Done.

2024-10-10 10:10 UTC, popescu-v commented on khiops/core/internals/runner.py
> +        Set by the upstream `khiops_env` script from the `khiops-core` package.
Done.

2024-10-10 10:19 UTC, popescu-v commented on khiops/core/internals/runner.py
> +            elif not os.path.exists(self._tool_path(tool_name)):
Done. Eliminated these checks altogether, because:
- the `khiops_path` and `khiops_coclustering` path setters check that their arguments are existing paths
- `_tool_path` asserts that `khiops_path` and `khiops_coclustering_path` are not `None`

2024-10-10 10:19 UTC, popescu-v commented on khiops/core/internals/runner.py
> +# Runner (backend) of Khiops Python, by default None
Done.

2024-10-10 10:20 UTC, popescu-v commented on khiops/core/internals/runner.py
> +
Done: dropped this paragraph altogether.

2024-10-10 10:21 UTC, popescu-v commented on tests/test_khiops_integrations.py
> +            and os.access(runner.khiops_coclustering_path, os.X_OK)
Done.

2024-10-10 10:23 UTC, popescu-v commented on tests/test_sklearn.py
> +                    "check_estimators_dtypes",
Ok. I would address this issue in release `10.2.3.1`.

2024-10-10 12:24 UTC, folmos-at-orange commented on .github/workflows/conda.yml
> +          conda install --channel conda-forge --channel khiops-dev khiops-core=$KHIOPS_CORE_VERSION
Ok

2024-10-10 12:33 UTC, folmos-at-orange commented on .github/workflows/unit-tests.yml
> +          python -c "import khiops.core as kh; kh.get_runner().print_status()"
OK

2024-10-10 13:44 UTC, folmos-at-orange requested changes
All minor stuff.

However, it doesn't work in macOS. A change in `khiops_env` is necessary.

2024-10-10 13:44 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
>          status_msg += f"MPI command     : {mpi_command_args_msg}\n"
Align the `:` so they are all in the same place (as it was before). Also I'd put `Khiops CC path` instead of `Khiops Coclustering path`.

2024-10-10 13:44 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +    """Check `khiops_env` exists relative to the specified environment dir"""
Double backticks to avoid reST errors.

2024-10-10 13:44 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +        You may not set this value directly. Instead, set the `KHIOPS_PROC_NUMBER`
Double backticks in KHIOPS_PROC_NUMBER to avoid reST errors.

2024-10-10 13:44 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +    - the `khiops-core` Linux native package installed on the local machine, or
Double backticks to avoid reST errors.

2024-10-10 13:44 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +        """str: Path to the `MODL*` Khiops binary
Double backticks to avoid reST errors.

2024-10-10 13:44 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +        Set by the `khiops_env` script from the `khiops-core` package.
Double backticks to avoid reST errors.

2024-10-10 13:44 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +        Set by the `khiops_env` script from the `khiops-core` package.
Double backticks to avoid reST errors.

2024-10-10 13:44 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +        """str: Path to the `MODL_Coclustering` Khiops Coclustering binary
Double backticks to avoid reST errors.

2024-10-10 16:01 UTC, popescu-v commented on khiops/core/internals/runner.py
> +    """Check `khiops_env` exists relative to the specified environment dir"""
Done.

2024-10-10 16:01 UTC, popescu-v commented on khiops/core/internals/runner.py
> +        You may not set this value directly. Instead, set the `KHIOPS_PROC_NUMBER`
Done.

2024-10-10 16:02 UTC, popescu-v commented on khiops/core/internals/runner.py
> +    - the `khiops-core` Linux native package installed on the local machine, or
Done.

2024-10-10 16:03 UTC, popescu-v commented on khiops/core/internals/runner.py
> +        """str: Path to the `MODL*` Khiops binary
Done.

2024-10-10 16:03 UTC, popescu-v commented on khiops/core/internals/runner.py
> +        Set by the `khiops_env` script from the `khiops-core` package.
Done.

2024-10-10 16:03 UTC, popescu-v commented on khiops/core/internals/runner.py
> +        Set by the `khiops_env` script from the `khiops-core` package.
Done.

2024-10-10 16:03 UTC, popescu-v commented on khiops/core/internals/runner.py
> +        """str: Path to the `MODL_Coclustering` Khiops Coclustering binary
Done.

2024-10-10 16:08 UTC, popescu-v commented on khiops/core/internals/runner.py
>          status_msg += f"MPI command     : {mpi_command_args_msg}\n"
Done & Done.

2024-10-10 16:10 UTC, popescu-v commented
> All minor stuff.
> 
> However, it doesn't work in macOS. A change in `khiops_env` is necessary.
> 
> _Update:_
> 
> I'd also make private `get_linux_distribution_name` , `check_samples_dir` and `get_dir_status` so they dont pollute the documentation.

- `get_linux_distribution_name` was moved to `test_khiops_integrations.py` and made private therein; it is no longer necessary in the runner code (as those variables are set by `khiops_env` now).
- the two other methods were made private.

2024-10-14 09:00 UTC, folmos-at-orange approved these changes

2024-10-14 09:06 UTC, popescu-v commented on tests/test_khiops_integrations.py
> +        linux_distribution = _get_linux_distribution_name()
Indeed, it seems you are right! I removed it.

2024-10-14 09:06 UTC, popescu-v commented on tests/test_khiops_integrations.py
> +
Done: removed it altogether (see the comments below).

2024-10-14 10:41 UTC, folmos-at-orange approved these changes

2024-10-14 10:41 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +        status_msg += "Khiops binary status\n"
I'd put `Khiops executable status (output of 'khiops -s')`

2024-10-14 10:41 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +        # On success retrieve the status and added to the message
Empty line above this.

2024-10-14 10:43 UTC, popescu-v commented on khiops/core/internals/runner.py
> +        status_msg += "Khiops binary status\n"
Ok, it seems clearer indeed.

2024-10-14 10:43 UTC, popescu-v commented on khiops/core/internals/runner.py
> +        # On success retrieve the status and added to the message
Ok.

2024-10-14 11:08 UTC, popescu-v commented on khiops/core/internals/runner.py
> +        status_msg += "Khiops binary status\n"
Done.

2024-10-14 11:08 UTC, popescu-v commented on khiops/core/internals/runner.py
> +        # On success retrieve the status and added to the message
Done.

2024-10-14 13:52 UTC, merged