Raise a visible error in the border case where no error message is available
KhiopsML/khiops-python pull request #255
Opened 2024-10-09 17:29 UTC by tramora

Should fix #253

2024-10-18 06:45 UTC, folmos-at-orange approved these changes

2024-10-18 06:45 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +                    "but no message is available\n"
Remove the `\n`

2024-10-18 06:45 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +            # no message available, an error must be raised though
I'd put `Raise an exception anyway if the return code was not zero with no messages`

2024-10-18 06:45 UTC, folmos-at-orange commented on tests/test_core.py
> +                    9,  # non-zero error code
You can use named parameters to self document:
```
create_mocked_raw_run(
    stdout=False,
    stderr=False,
    return_code=9
)

2024-10-21 10:03 UTC, tramora commented on khiops/core/internals/runner.py
> +                    "but no message is available\n"
You are right. I removed it

2024-10-21 10:03 UTC, tramora commented on khiops/core/internals/runner.py
> +            # no message available, an error must be raised though
Indeed clearer. Modification done

2024-10-21 10:03 UTC, tramora commented on tests/test_core.py
> +                    9,  # non-zero error code
Indeed I used the named params but kept the comments

2024-10-21 13:29 UTC, popescu-v commented on tests/test_core.py
> +        with self.assertRaises(KhiopsRuntimeError):
I would also test the error message:
```python
        with self.assertRaises(KhiopsRuntimeError) as context:
            # The rest of the code as-is
        expected_msg = "khiops execution had errors (return code 9) but no message is available"
        output_msg = str(context.exception )
        self.assertEqual(output_msg, expected_msg)
```

2024-10-21 13:36 UTC, popescu-v requested changes
See comment.

2024-10-21 14:54 UTC, folmos-at-orange commented on khiops/core/internals/runner.py
> +            # no message available, an error must be raised though
I'd put it before the `else` to follow the usual codebase pattern.

2024-10-23 16:16 UTC, tramora commented on tests/test_core.py
> +        with self.assertRaises(KhiopsRuntimeError):
Indeed it ensures the `KhiopsRuntimeError` was raised for the specific cause not because of another one.
However I'm reluctant to test against labels vs ids (because of i18n or encoding differences that can make the test fail) but it's OK here.
Change done.

2024-10-23 17:41 UTC, popescu-v commented on tests/test_core.py
> +        with self.assertRaises(KhiopsRuntimeError):
Ok.

2024-10-24 12:49 UTC, tramora commented on khiops/core/internals/runner.py
> +            # no message available, an error must be raised though
Modification done. Even if I would naturally keep it close to test against the return_code

2024-10-24 13:08 UTC, popescu-v approved these changes
LGTM

2024-10-24 13:14 UTC, merged