Run some samples in the platform-specific integration tests
KhiopsML/khiops-python pull request #261
Opened 2024-10-15 13:34 UTC by popescu-v

Thusly, we test that Khiops actually runs on Windows and Rocky Linux.

2024-10-15 13:43 UTC, folmos-at-orange requested changes

2024-10-15 13:45 UTC, popescu-v commented on .github/workflows/unit-tests.yml
> +          PRTE_MCA_rmaps_default_mapping_policy: :oversubscribe
Yes: https://github.com/open-mpi/ompi/issues/8955#issuecomment-846272943.

2024-10-15 13:46 UTC, popescu-v commented on .github/workflows/unit-tests.yml
> +          python -m khiops.samples.samples -i deploy_model -e
The obstacle is that the Khiops Python library is not installed in the current environment (there never was any Pip install being done here). Only the sources have been checked out.

2024-10-15 13:50 UTC, folmos-at-orange commented on .github/workflows/unit-tests.yml
> +          python -m khiops.samples.samples -i deploy_model -e
Ok

2024-10-15 13:54 UTC, folmos-at-orange commented on .github/workflows/unit-tests.yml
> +          PRTE_MCA_rmaps_default_mapping_policy: :oversubscribe
Ok

2024-10-15 16:14 UTC, folmos-at-orange approved these changes

2024-10-16 12:23 UTC, folmos-at-orange approved these changes

2024-10-16 12:23 UTC, folmos-at-orange commented on .github/workflows/unit-tests.yml
> +            $(Resolve-Path '.' | % {$_.toString()})
I'd just use 1 line

2024-10-16 12:23 UTC, folmos-at-orange commented on .github/workflows/unit-tests.yml
> +          # Otherwise, presumably as a side-effect of refreshing the environment, invoking `python` directly results in invoking the system-cached Python on the runner
I'd split this into two lines

2024-10-16 12:23 UTC, folmos-at-orange commented on .github/workflows/unit-tests.yml
> +          # Execute complete Khiops sample (train and deploy model)
I'd remove `complete`

2024-10-16 12:23 UTC, folmos-at-orange commented on .github/workflows/unit-tests.yml
> +          # Execute complete Khiops Coclustering sample (train and deploy model)
I'd remove `complete`

2024-10-16 12:23 UTC, folmos-at-orange commented on .github/workflows/unit-tests.yml
> +          # Execute complete Khiops sample (train and deploy model), which uses MPI
I'd remove `complete`

2024-10-16 12:23 UTC, folmos-at-orange commented on .github/workflows/unit-tests.yml
> +          # Otherwise, presumably as a side-effect of refreshing the environment, invoking `python` directly results in invoking the system-cached Python on the runner
Moreover I'd restructure the phrase for clarity
```
# Otherwise invoking `python` directly invokes the system-cached Python on the runner
# This is a side-effect of refreshing the environment
```

2024-10-16 12:24 UTC, popescu-v commented on .github/workflows/unit-tests.yml
> +            $(Resolve-Path '.' | % {$_.toString()})
Ok.

2024-10-16 12:24 UTC, popescu-v commented on .github/workflows/unit-tests.yml
> +          # Otherwise, presumably as a side-effect of refreshing the environment, invoking `python` directly results in invoking the system-cached Python on the runner
Ok.

2024-10-16 12:24 UTC, popescu-v commented on .github/workflows/unit-tests.yml
> +          # Execute complete Khiops sample (train and deploy model)
Ok.

2024-10-16 12:24 UTC, popescu-v commented on .github/workflows/unit-tests.yml
> +          # Execute complete Khiops Coclustering sample (train and deploy model)
Ok.

2024-10-16 12:24 UTC, popescu-v commented on .github/workflows/unit-tests.yml
> +          # Execute complete Khiops sample (train and deploy model), which uses MPI
Ok.

2024-10-16 14:38 UTC, merged