Update CHANGELOG
KhiopsML/khiops-python pull request #276
Opened 2024-11-12 13:50 UTC by popescu-v

related_to #275

2024-11-12 14:18 UTC, folmos-at-orange requested changes
Missing docs:

- README.md: Unify Installation procedure
- doc/index.rst: Unify installation procedure
- doc/notes.rst: Remove "Environment Variables" section
- khiops/core/api.py: Remove reference to `_core-api-env-vars`

2024-11-12 14:18 UTC, folmos-at-orange commented on CHANGELOG.md
> +  `khiops` channel.
I'll rephrase to enphasize that we do not depend on the "problematic" `default` anaconda channel. The specific packages we depend on are not relevant.
```
The Conda package does not depend anymore on the `default` Anaconda channel. 
The package can be installed using only the `conda-forge` and `khiops` channels.
```

2024-11-12 14:18 UTC, folmos-at-orange commented on CHANGELOG.md
> +    used on all supported platforms for setting the execution environment.
This is too technical
```
Improve and simplify the integration with the `khiops-core` 
package via its `khiops_env` script.
```

2024-11-12 16:02 UTC, popescu-v commented on CHANGELOG.md
> +- (`sklearn`) Complete support fo `core` API functions parameters in the
Done & Done.

2024-11-12 16:03 UTC, popescu-v commented on CHANGELOG.md
> +  `khiops` channel.
I would avoid negative phrasings. I'll change to `The package only depends on the `conda-forge` and `khiops` channels.`

2024-11-12 16:05 UTC, popescu-v commented on CHANGELOG.md
> +    used on all supported platforms for setting the execution environment.
Ok. Changed as suggested.

2024-11-12 16:11 UTC, popescu-v commented
> Missing docs:
> 
>     * README.md: Unify Installation procedure

OK & Done.

> 
>     * doc/index.rst: Unify installation procedure

OK & Done.

> 
>     * doc/notes.rst: Remove "Environment Variables" section

Not yet:
- `KHIOPS_SAMPLES_DIR` must be maintained
- `KHIOPS_PROC_NUMBER`, `KHIOPS_MEMORY_LIMIT` and  `KHIOPS_TMP_DIR` must be maintained untill https://github.com/KhiopsML/khiops-python/issues/263 lands (in 10.2.3.1).

> 
>     * khiops/core/api.py: Remove reference to `_core-api-env-vars`

Not yet: see above.

2024-11-13 07:33 UTC, folmos-at-orange commented on README.md
> +conda install -c khiops khiops
It is cleaner to just put one line
```
conda install -c conda-forge -c khiops khiops
```
This works because the `-c` flag puts in priority the channel, so `--override-channels` is not necessary: it will work in any environment.

Similarly is `index.rst`

2024-11-13 07:34 UTC, folmos-at-orange commented on .github/workflows/api-docs.yml
General comment: The TODO in the commit messsage adds no relevant information to the history, I'd eliminate it

2024-11-13 09:58 UTC, popescu-v commented on README.md
> +conda install -c khiops khiops
OK; and I can also drop the Minoforge / vanilla Anaconda distinction.

2024-11-13 09:58 UTC, popescu-v commented on .github/workflows/api-docs.yml
OK, it was just a reminder to myself that we need to do this before tagging the 10.2.3.0 release.

2024-11-13 10:04 UTC, popescu-v commented on README.md
> +conda install -c khiops khiops
Done.

2024-11-13 10:07 UTC, folmos-at-orange approved these changes

2024-11-13 10:27 UTC, merged