Eliminate is_fitted_ sklearn attribute
KhiopsML/khiops-python pull request #280
Opened 2024-11-18 15:47 UTC by folmos-at-orange

2025-01-07 16:55 UTC, popescu-v commented on khiops/sklearn/estimators.py
> +            pass
I would explain in a comment here why we ignore the exception.

2025-01-07 16:59 UTC, popescu-v commented on khiops/sklearn/estimators.py
> +            raise AssertionError("Model not fit yet")
I would remove the "yet" word and just say "The model is not fitted" (I would use "fitted" here to emphasize the technical process of fitting it to data, rather than the model is not "fit" as "suitable").

2025-01-07 17:02 UTC, popescu-v commented on tests/test_sklearn.py
> +        """Test that export operations raise a NonFitted exceptions when non-fitted
s/a NonFitted exceptions/a NotFittedError exception/

2025-01-07 17:03 UTC, popescu-v requested changes
See the comments.

2025-01-08 08:03 UTC, folmos-at-orange commented on khiops/sklearn/estimators.py
> +            pass
Ok & Done.

2025-01-08 08:03 UTC, folmos-at-orange commented on khiops/sklearn/estimators.py
> +            raise AssertionError("Model not fit yet")
Ok & Done.

2025-01-08 08:03 UTC, folmos-at-orange commented on tests/test_sklearn.py
> +        """Test that export operations raise a NonFitted exceptions when non-fitted
Ok & Done.

2025-01-08 10:26 UTC, popescu-v commented on tests/test_sklearn.py
> +        """Test that export functions raise NonFittedError exceptions when non-fitted
s/NonFittedError/NotFittedError/ (No*t* instead of No*n*)

2025-01-08 10:27 UTC, popescu-v approved these changes
LGTM, but there remains a really small typo to fix (see remaining comment).

2025-01-08 11:48 UTC, merged