Add PR template
KhiopsML/khiops-python pull request #281
Opened 2024-11-18 16:29 UTC by folmos-at-orange

2024-11-19 09:26 UTC, tramora approved these changes
Looks good for me

2024-11-19 17:40 UTC, popescu-v commented on .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
> +- [ ] Self-Review: Review "Files Changed" tab and fix any problems you find before requesting
I would add one more item:
```md
- [  ] Self-review: Make sure all PR checks (GitHub workflows) run and finish successfully before requesting a review
```

2024-11-19 17:42 UTC, popescu-v commented on .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
> +name: Generic PR template
I'm not sure we need to follow this template for `dev` -> `main` PRs on pending releases: it seems to me that the checklists should be simplified for this case (as already checked in the PRs for  merging branches into `dev`).

2024-11-19 17:45 UTC, popescu-v requested changes
See comments.

2024-11-20 08:50 UTC, folmos-at-orange commented on .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
> +- [ ] Self-Review: Review "Files Changed" tab and fix any problems you find before requesting
I'll reword to add these points.

2024-11-20 08:51 UTC, folmos-at-orange commented on .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
> +name: Generic PR template
Ok. I'll change the title and see if I can put some constraints.

2024-11-20 09:09 UTC, folmos-at-orange commented on .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
> +- [ ] Self-Review: Review "Files Changed" tab and fix any problems you find before requesting
Done

2024-11-20 09:13 UTC, folmos-at-orange commented on .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
> +name: Generic PR template
In the end I think it is better just to keep one template: The merges `dev`-> `main` are rare and we know that we can safely ignore most of the template.

If find too much complex to have another template just for these rare merges: The gain is very limited.

2024-11-20 10:28 UTC, popescu-v commented on .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
> +- [ ] Self-Review: Review "Files Changed" tab and fix any problems you find before requesting
Ok.

2024-11-20 10:28 UTC, popescu-v commented on .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
> +name: Generic PR template
OK, fair enough. However, I would just one note that all those steps can be sidestepped for these kinds of PRs.

2024-11-20 10:32 UTC, folmos-at-orange commented on .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
> +  - [ ] Check that your changes render well in HTML
Way too complicated. It is easier to build the docs and check them locally, I can point to the proper doc.

2024-11-20 10:33 UTC, folmos-at-orange commented on .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
> +name: Generic PR template
Let's not overload the checklist. I think this is fine.

2024-11-20 10:38 UTC, popescu-v commented on .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
> +  - [ ] Check that your changes render well in HTML
IMHO, we need to rigorously check the built artifact: building locally has 2 drawbacks IMHO:
1. We need to set-up and maintain a whole environment for this
2. We have no guarantee that this environment (whence the result of the build) is 100 % in sync with the result of the workflow.

However, I agree that we can just open `index.html` in the browser, there is no need for the HTTP server launch.

2024-11-20 10:39 UTC, folmos-at-orange commented on .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
> +  - [ ] Check that your changes render well in HTML
A compromise after offline discussion: Download the artifact and say to load `index.html` in a browser (usually it is just a double click)

2024-11-20 10:50 UTC, popescu-v approved these changes
LGTM

2024-11-20 12:15 UTC, merged