2 khiops coclustering simplification fails on non ascii data
KhiopsML/khiops-python pull request #3
Opened 2023-06-30 15:54 UTC by popescu-v

Closes #2.

2023-06-30 16:16 UTC, felipe-olmos-orange requested changes

2023-06-30 16:16 UTC, felipe-olmos-orange commented on pykhiops/core/internals/io.py
> +        """ """
rename to `write_khiops_json_file`.

And write the docstring.

2023-06-30 16:16 UTC, felipe-olmos-orange commented on pykhiops/core/internals/io.py
> +            json_payload = json.dumps(self.json_data, ensure_ascii=False)
rename to `json_string`

2023-06-30 16:16 UTC, felipe-olmos-orange commented on pykhiops/core/internals/io.py
> +            # Do not escape non-ASCII Unicode characters; keep them as such
"keep them as such" is redundant

2023-06-30 16:16 UTC, felipe-olmos-orange commented on pykhiops/core/internals/io.py
> +            # when its init arguments are changed after initialization
Just say `Store a copy of the data to be able to write copies of it`

2023-06-30 16:16 UTC, felipe-olmos-orange commented on pykhiops/sklearn/estimators.py
> +        self.model_report_.dump_khiops_json_data(full_coclustering_file_path)
We should deprecate `model_report_raw_` since now can be accessed with `model_report_.json_data`.

2023-06-30 16:16 UTC, felipe-olmos-orange commented on pykhiops/core/internals/io.py
> +import copy
General comment: Before merging add a GitHub workflow to execute the pre-commit checks 
(you can copy that of khiops: https://github.com/KhiopsML/khiops/blob/dev/.github/workflows/pre-commit-checks.yml)

2023-06-30 16:31 UTC, popescu-v commented on pykhiops/core/internals/io.py
> +import copy
Ok; I will do this in the same PR.

2023-06-30 16:34 UTC, popescu-v commented on pykhiops/sklearn/estimators.py
> +        self.model_report_.dump_khiops_json_data(full_coclustering_file_path)
Ok; I plan to write a property which will raise a deprecation warning on access and return `model_report_.json_data`.

2023-06-30 17:32 UTC, popescu-v commented on pykhiops/core/internals/io.py
> +        """ """
My bad for the docstring. Done.

2023-06-30 17:32 UTC, popescu-v commented on pykhiops/core/internals/io.py
> +            json_payload = json.dumps(self.json_data, ensure_ascii=False)
Done.

2023-06-30 17:32 UTC, popescu-v commented on pykhiops/core/internals/io.py
> +            # Do not escape non-ASCII Unicode characters; keep them as such
Ok; removed.

2023-06-30 17:32 UTC, popescu-v commented on pykhiops/core/internals/io.py
> +            # when its init arguments are changed after initialization
Ok; rephrased as requested.

2023-06-30 17:33 UTC, popescu-v commented on pykhiops/sklearn/estimators.py
> +        self.model_report_.dump_khiops_json_data(full_coclustering_file_path)
Done.

2023-06-30 17:44 UTC, popescu-v commented on pykhiops/core/internals/io.py
> +import copy
Done.

2023-07-04 13:10 UTC, felipe-olmos-orange commented on .github/workflows/pre-commit-checks.yml
> +
This is not necessary

2023-07-04 15:57 UTC, felipe-olmos-orange commented on .github/workflows/pre-commit-checks.yml
> +
Ok, then it is not necessary to do it with `&&`. When you use `|`  it is a if it were a text file.

Also rename to "Install khiops-python dependencies"

2023-07-04 16:08 UTC, popescu-v commented on .github/workflows/pre-commit-checks.yml
> +
Ok, the required changes have been implemented.

2023-07-05 08:14 UTC, felipe-olmos-orange approved these changes

2023-07-05 08:26 UTC, merged