83 vendor khiops with pykhiops
KhiopsML/khiops-python pull request #91
Opened 2023-07-06 09:57 UTC by popescu-v

2023-08-18 09:11 UTC, felipe-olmos-orange requested changes
Additionally we should make a converter script to migrate from `pykhiops` to `khiops-python`

2023-08-18 09:11 UTC, felipe-olmos-orange commented on .github/workflows/run-unit-tests.yml
>        - name: Run Unit Tests
Opportunistically I would refactor this so the setting of `UNITTTEST_ONLY_SHORT_TEST` is made in step with an `if` field.

2023-08-18 09:11 UTC, felipe-olmos-orange commented on README.md
> +- [The Khiops native binaries][khiops] (>=9.0)
Remove this. Now they are included. We'll make a section for advanced installs for the case of system-wide khiops installs.

2023-08-18 09:11 UTC, felipe-olmos-orange commented on README.md
> +The main documentation of the Khiops Python library is available [here][pykhiops-doc].
Also change the name of the reference to `khiops-python-doc`

2023-08-18 09:11 UTC, felipe-olmos-orange commented on README.md
> +from khiops import core as pk
We should change the `core` alias from `pk` to `kh` everywhere

2023-08-18 09:11 UTC, felipe-olmos-orange commented on README.md
> +converts a Khiops 9 script to a Khiops 10 script
We can remove this section. I don't think people need to migrate anymore. Additionnaly we should remove the converter code and entry-point.

2023-08-18 09:11 UTC, felipe-olmos-orange commented on khiops/__init__.py
> +The main package for Khiops support for Python.
-> Main module of the Khiops Python package

2023-08-18 09:11 UTC, felipe-olmos-orange commented on khiops/__init__.py
> +   pk.train_predictor(...)
`pk` -> `kh`

2023-08-18 09:11 UTC, felipe-olmos-orange commented on khiops/__init__.py
> +    Python"""
this version of Khiops Python -> this package's version

(so it fits in one line)

2023-08-18 09:17 UTC, popescu-v commented on .github/workflows/build-conda-package.yml
> +    shell: bash -el {0}
This doesn't seem to be the case: see https://github.com/marketplace/actions/setup-miniconda#important

2023-08-18 09:18 UTC, popescu-v commented on .github/workflows/build-conda-package.yml
> +        if: ${{ github.event_name == 'push' }}
Yeah, ok, less clutter indeed.

2023-08-18 09:18 UTC, popescu-v commented on .github/workflows/build-conda-package.yml
> +        if: ${{ github.event_name == 'workflow_dispatch' }}
Ok.

2023-08-18 09:28 UTC, felipe-olmos-orange commented on .github/workflows/build-conda-package.yml
> +    shell: bash -el {0}
Ok

2023-08-18 09:51 UTC, popescu-v commented on .github/workflows/build-conda-package.yml
> +          # See issue https://github.com/actions/checkout/issues/701
Ok, I will rephrase.

2023-08-18 09:51 UTC, popescu-v commented on .github/workflows/build-conda-package.yml
> +          KHIOPS_REVISION: ${{ env.KHIOPS_REVISION }}
Right, this seems redundant.

2023-08-18 09:53 UTC, popescu-v commented on .github/workflows/build-conda-package.yml
> +        if: success() || failure()
Right; I will remove this `if`.

2023-08-18 09:53 UTC, popescu-v commented on .github/workflows/build-conda-package.yml
> +          retention-days: 1
Ok.

2023-08-18 09:54 UTC, popescu-v commented on .github/workflows/build-conda-package.yml
> +  package-conda:
Ok.

2023-08-18 09:54 UTC, popescu-v commented on .github/workflows/build-conda-package.yml
> +  test:
Ok.

2023-08-18 09:54 UTC, popescu-v commented on .github/workflows/build-conda-package.yml
> +        if: success() || failure()
Right, I will remove this `if`.

2023-08-18 09:55 UTC, popescu-v commented on .github/workflows/build-conda-package.yml
> +          ref: v10.1.1
Yes: an input on `workflow_dispatch`, a default value on `push`, right?

2023-08-18 09:55 UTC, popescu-v commented on .github/workflows/build-conda-package.yml
> +          SAMPLES_SKLEARN=`conda run --no-capture-output python -W ignore -c "import khiops.samples.samples_sklearn as s; print(s.__file__)"`
AFAIR, I needed to add this; but I will check again, to be sure.

2023-08-18 09:55 UTC, popescu-v commented on .github/workflows/build-conda-package.yml
> +  release:
Ok.

2023-08-18 09:59 UTC, popescu-v commented on .pre-commit-config.yaml
> +        exclude: packaging/conda/(meta|conda_build_config).yaml
For `meta.yaml`, it's because of the Jinja templating part which makes `yamlfix` go awry.
For `build_conda_config.yaml`, it's because it puts all Python versions in a list, which makes it more difficult to comment out specific versions and only keep relevant ones, during development.
But, before merge, IMHO we could only keep `meta.yaml` in the exclusion files.

2023-08-18 10:06 UTC, popescu-v commented on .github/workflows/build-conda-package.yml
> +          echo "SINGLE_VERSION=$SINGLE_VERSION" >> "$GITHUB_ENV"
> And what is `SINGLE_VERSION` ? It should dissapear once we synchronize the manual (osx-arm64) and automatic builds ?

`SINGLE_VERSION` is a safeguard for detecting tag mismatches between the Git tag (used for Linux, Mac OS x86, Windows packages) and the tag used for manually generating the Mac OS arm64 package.
But I agree that once the package building process is fully automated (i.e. once GitHub provides support for Mac OS arm64 runners), this safeguard can be removed.

2023-08-18 10:10 UTC, popescu-v commented on .github/workflows/pre-commit-checks.yml
> +          rm -rf khiops.egg-info
AFAIK, an easier way would be to `pip install pip-tools`, then to do `pip `python -m piptools compile -o requirements.txt` and then to `pip install -r requirements.txt`, but this adds an extra dependency to `pip-tools` in the development environment.

2023-08-18 10:17 UTC, popescu-v commented on .github/workflows/build-conda-package.yml
> +          echo "SINGLE_VERSION=$SINGLE_VERSION" >> "$GITHUB_ENV"
> Instead of sed/awk the bz2 files why not parse the output of `conda search -c ./ khiops`

Yes, we could, but AFAIK this would also boil down to using AWK: ``conda search -c ./ khiops | awk 'NR > 2 {print $2}'. Moreover, `conda search` would only give the version of the supported platform (ubuntu for the release) and would not allow us to check that versions are coherent between the platforms, especially for the manually-built Mac OS arm64.

2023-08-18 10:17 UTC, popescu-v commented on README.md
> +- [The Khiops native binaries][khiops] (>=9.0)
Ok, the `README` needs a dedicated refactoring pass IMHO.

2023-08-18 12:50 UTC, popescu-v commented on README.md
> +from khiops import core as pk
Ok.

2023-08-18 12:50 UTC, popescu-v commented on README.md
> +converts a Khiops 9 script to a Khiops 10 script
Ok for removing the converter code and its entry point.

2023-08-18 12:51 UTC, popescu-v commented on khiops/__init__.py
> +The main package for Khiops support for Python.
Ok.

2023-08-18 12:54 UTC, popescu-v commented on .github/workflows/build-conda-package.yml
> +        run: |-
Ok, I will check this.

2023-08-18 13:33 UTC, popescu-v commented on .github/workflows/build-conda-package.yml
> +        run: |-
Ok, removed.

2023-08-18 13:47 UTC, popescu-v commented on .github/workflows/run-unit-tests.yml
>        - name: Run Unit Tests
Ok.

2023-08-18 13:48 UTC, popescu-v commented on README.md
> +The main documentation of the Khiops Python library is available [here][pykhiops-doc].
Ok.

2023-08-18 13:54 UTC, popescu-v commented on khiops/__init__.py
> +    Python"""
Ok.

2023-08-18 14:01 UTC, felipe-olmos-orange commented on .pre-commit-config.yaml
> +        exclude: packaging/conda/(meta|conda_build_config).yaml
Ok

2023-08-18 14:03 UTC, felipe-olmos-orange commented on .github/workflows/pre-commit-checks.yml
> +          rm -rf khiops.egg-info
Add the dependency, we can afford development dependencies.

2023-08-18 16:07 UTC, popescu-v commented on khiops/__init__.py
> +   pk.train_predictor(...)
Ok.

2023-08-18 16:44 UTC, popescu-v commented on .github/workflows/build-conda-package.yml
> +        if: ${{ github.event_name == 'push' }}
Done.

2023-08-18 16:44 UTC, popescu-v commented on .github/workflows/build-conda-package.yml
> +        if: ${{ github.event_name == 'workflow_dispatch' }}
Done.

2023-08-18 16:44 UTC, popescu-v commented on .github/workflows/build-conda-package.yml
> +          # See issue https://github.com/actions/checkout/issues/701
Done.

2023-08-18 16:44 UTC, popescu-v commented on .github/workflows/build-conda-package.yml
> +        run: |-
Done; removed.

2023-08-18 16:44 UTC, popescu-v commented on .github/workflows/build-conda-package.yml
> +          KHIOPS_REVISION: ${{ env.KHIOPS_REVISION }}
Done; removed.

2023-08-18 16:45 UTC, popescu-v commented on .github/workflows/build-conda-package.yml
> +        if: success() || failure()
Done.

2023-08-18 16:45 UTC, popescu-v commented on .github/workflows/build-conda-package.yml
> +          retention-days: 1
Done.

2023-08-18 16:45 UTC, popescu-v commented on .github/workflows/build-conda-package.yml
> +  package-conda:
Done.

2023-08-18 16:45 UTC, popescu-v commented on .github/workflows/build-conda-package.yml
> +  test:
Done.

2023-08-18 16:45 UTC, popescu-v commented on .github/workflows/build-conda-package.yml
> +        if: success() || failure()
Done; removed.

2023-08-18 16:46 UTC, popescu-v commented on .github/workflows/build-conda-package.yml
> +        run: |-
Done.

2023-08-18 16:46 UTC, popescu-v commented on .github/workflows/build-conda-package.yml
> +  release:
Done.

2023-08-18 16:47 UTC, popescu-v commented on .pre-commit-config.yaml
> +        exclude: packaging/conda/(meta|conda_build_config).yaml
Done; only kept `meta.yaml` in the file exclusions.

2023-08-18 16:47 UTC, popescu-v commented on .github/workflows/pre-commit-checks.yml
> +          rm -rf khiops.egg-info
Done; dependency install simplified according to comment https://github.com/KhiopsML/khiops-python/pull/91#discussion_r1298276935.

2023-08-18 16:48 UTC, popescu-v commented on .github/workflows/run-unit-tests.yml
>        - name: Run Unit Tests
Done.

2023-08-18 16:48 UTC, popescu-v commented on README.md
> +- [The Khiops native binaries][khiops] (>=9.0)
Done.

2023-08-18 16:48 UTC, popescu-v commented on README.md
> +The main documentation of the Khiops Python library is available [here][pykhiops-doc].
Done.

2023-08-18 16:48 UTC, popescu-v commented on README.md
> +from khiops import core as pk
Done.

2023-08-18 16:49 UTC, popescu-v commented on README.md
> +converts a Khiops 9 script to a Khiops 10 script
Done.

2023-08-18 16:49 UTC, popescu-v commented on khiops/__init__.py
> +The main package for Khiops support for Python.
Done.

2023-08-18 16:49 UTC, popescu-v commented on khiops/__init__.py
> +   pk.train_predictor(...)
Done throughout the code base.

2023-08-18 16:54 UTC, popescu-v commented on khiops/__init__.py
> +    Python"""
Done.

2023-08-18 17:31 UTC, popescu-v commented on .pre-commit-config.yaml
> +        exclude: packaging/conda/(meta|conda_build_config).yaml
Actually, no: if we `yamlfix` `conda_build_config.yaml`, then only the Python 3.11 package is built, which means that the tests fail on other Pythons, e.g. https://github.com/KhiopsML/khiops-python/actions/runs/5904978935/job/16018897091 for the failure, and https://github.com/KhiopsML/khiops-python/actions/runs/5904978935/job/16018164417#step:7:1222 for the build (to see that only the Python 3.11 package is generated).

2023-08-21 08:17 UTC, felipe-olmos-orange commented on .github/workflows/build-conda-package.yml
> +          # See issue https://github.com/actions/checkout/issues/701
Ok, but i think we should allow 100 chars width so the new comment fits in one line

2023-08-21 08:20 UTC, felipe-olmos-orange commented on .pre-commit-config.yaml
> +        exclude: packaging/conda/(meta|conda_build_config).yaml
Ok

2023-08-21 08:22 UTC, felipe-olmos-orange commented on .github/workflows/build-conda-package.yml
> +          echo "SINGLE_VERSION=$SINGLE_VERSION" >> "$GITHUB_ENV"
Ok. Comment that we should remove this when the we build all on Github

2023-08-21 08:27 UTC, felipe-olmos-orange commented on .github/workflows/build-conda-package.yml
> +          echo "SINGLE_VERSION=$SINGLE_VERSION" >> "$GITHUB_ENV"
And the `SINGLE_VERSION` one-liner put it in various lines. If i recall well you can do
```
SINGLE_VERSION=$( \
  awk '{ \
    for ... \
  ... \
)

2023-08-21 08:37 UTC, popescu-v commented on .github/workflows/build-conda-package.yml
> +          SAMPLES_SKLEARN=`conda run --no-capture-output python -W ignore -c "import khiops.samples.samples_sklearn as s; print(s.__file__)"`
We indeed do not seem to need this. Hence, I removed it.

2023-08-21 08:38 UTC, popescu-v commented on .github/workflows/build-conda-package.yml
> +          echo "SINGLE_VERSION=$SINGLE_VERSION" >> "$GITHUB_ENV"
Yes, ok.

2023-08-21 08:38 UTC, popescu-v commented on .github/workflows/pre-commit-checks.yml
> +          rm -rf khiops.egg-info
Ok.

2023-08-21 08:38 UTC, popescu-v commented on .github/workflows/run-unit-tests.yml
>        - name: Run Unit Tests
Ok, I will drop these sigils.

2023-08-21 14:24 UTC, popescu-v commented on .github/workflows/build-conda-package.yml
> +          # See issue https://github.com/actions/checkout/issues/701
Ok.

2023-08-22 08:49 UTC, popescu-v commented on .github/workflows/pre-commit-checks.yml
> +          rm -rf khiops.egg-info
Done.

2023-08-22 08:49 UTC, popescu-v commented on .github/workflows/run-unit-tests.yml
>        - name: Run Unit Tests
Done.

2023-08-23 16:40 UTC, popescu-v commented
> Additionally we should make a converter script to migrate from `pykhiops` to `khiops-python`

We already provide a deprecation path: users are warned if they import pykhiops or use pk-status.

Having a converter script would incur the risk of moving into subjective areas, e.g. converting `import pykhiops.core as pk` into `import khiops.core as kh`, where `kh` is an arbitrary choice and, besides, users could have been using something else than `pk` and this would be hard to detect, thus making such a script rather brittle IMHO.

The deprecation path provides sufficient safeguards IMHO, while being robust enough.

2023-08-24 17:36 UTC, popescu-v commented on .github/workflows/build-conda-package.yml
> +          echo "SINGLE_VERSION=$SINGLE_VERSION" >> "$GITHUB_ENV"
Done.

2023-08-25 18:27 UTC, felipe-olmos-orange requested changes

2023-08-28 09:44 UTC, popescu-v commented on .github/workflows/build-conda-package.yml
> +          C:\Miniconda3\envs\true\Scripts\kh-status.exe
I will rename the environment to `khiops-python-env`. Hence, the path will be `C:\Miniconda3\envs\khiops-python-env\Scripts\kh-status.exe`.

2023-08-28 09:44 UTC, popescu-v commented on .github/workflows/build-conda-package.yml
> +          KHIOPS_SAMPLES_DIR: ${{ github.workspace }}/khiops-samples
Ok, I will resolve this conversation then.

2023-08-28 09:46 UTC, popescu-v commented on .github/workflows/build-conda-package.yml
> +          python $SAMPLES_SKLEARN -i khiops_coclustering -e
Ok, that would spare us from having to determine the path to the samples.

2023-08-28 09:47 UTC, popescu-v commented on .github/workflows/build-conda-package.yml
> +      - name: Download artifacts
Ok.

2023-08-28 09:47 UTC, popescu-v commented on .github/workflows/build-conda-package.yml
> +          conda index ./artifacts/
Yes, it is.

2023-08-28 09:48 UTC, popescu-v commented on .github/workflows/build-conda-package.yml
> +          # To be removed once GitHub supports Mac OS arm64
Well, I would not crowd the `khiops-python` code base with this, since this is a specific and temporary, purely CI/CD-related "sorcery".

2023-08-28 09:51 UTC, popescu-v commented on .github/workflows/build-pip-package.yml
> +          KHIOPS_LOCATION=$(pip show khiops | awk '/^Location:/ { print $2 }')
Ok for `KHIOPS_PYTHON_PATH` (as `-` hyphens are not valid in (Ba)sh variable names).

2023-08-28 09:53 UTC, popescu-v commented on .github/workflows/build-conda-package.yml
> +      - name: Download artifacts
Ok.

2023-08-28 09:59 UTC, popescu-v commented on .github/workflows/build-conda-package.yml
> +          path: artifacts
Ok.

2023-08-28 10:01 UTC, popescu-v commented on khiops/__init__.py
> +class _Wrapper:
Ok.

2023-08-28 10:03 UTC, popescu-v commented on README.md
> +[TO BE UPDATED]
Ok, but I think this information belongs to the general web site; otherwise, there will be an overlapping. IMHO, this documentation here in `khiops-python` should insist on the API, tutorials, etc - the pure Python code aspects.

2023-08-28 10:43 UTC, popescu-v commented on khiops/__init__.py
> +            if entry.is_file():
I would prefer to keep all this deprecation code in one single place. It would be easier to remove later on, IMHO. 

Moreover, putting the deprecation wrapper class in the `__init__.py` and importing it "later" in the modules that contain the deprecated code, entails circular import errors (because of the various `from ... import *` that are spread throughout the code base.

2023-08-28 10:54 UTC, popescu-v commented on khiops/core/internals/runner.py
> +        - Create a ``$TEMP/khiops_<HASH>`` and use it
Yes, ok.

2023-08-28 10:55 UTC, popescu-v commented on khiops/core/internals/runner.py
> +            self._root_temp_dir = tempfile.mkdtemp(prefix="khiops_")
Yes, we need to check the existence of and create if needed `os.path.dirname(self._root_temp_dir)` first.

2023-08-28 11:11 UTC, popescu-v commented on khiops/core/internals/runner.py
> +        The temporary scenarios/templates and dictionary files created by khiops are
Ok.

2023-08-28 11:14 UTC, popescu-v commented on khiops/core/internals/runner.py
> +                + 1
> Refactor to
> 
> ```python
> cpu_entries = [entry for entry in command_output.splitlines() if not entry.startswith("#")]
> return len(cpu_entries) + 1
> ```

Ok, though we need to have a set here as on certain Linux machines the entries are duplicated.

2023-08-28 11:18 UTC, popescu-v commented on khiops/core/internals/runner.py
> +                + 1
> Also this function should not have the `command_output` parameter. The execution of `_cpu_count_command` should be done inside.

It could, by I wanted to avoid writing the call `Popen` thrice in the cpu counting code.

2023-08-28 11:19 UTC, popescu-v commented on khiops/core/internals/runner.py
> +    def _cpu_count(self, command_output):
Ok.

2023-08-28 11:20 UTC, popescu-v commented on khiops/core/internals/runner.py
> +            n_cores = 1  # number of cores + 1
Yeah, ok.

2023-08-28 11:28 UTC, popescu-v commented on khiops/core/internals/runner.py
> +                    continue
IIRC, it was because on Windows the command did not output only integers. It outputted
```
NumberOfCores
------------------------
n
```
where n is the integer. But I was not sure whether:
- there was only integer (IIRC there could be several integers for multi-core CPUS)
- the non-integer output was constant so that a sufficient invariant can be enforced (as on Linux)

2023-08-28 11:29 UTC, popescu-v commented on khiops/core/internals/runner.py
> +                    return int(out.split(" ")[-1]) + 1
Ok.

2023-08-28 11:30 UTC, popescu-v commented on khiops/core/internals/runner.py
> +        # The conda environment mpiexec takes precedence over any other mpiexec install
Ok (`So the correct mpiexec is found`).

2023-08-28 11:32 UTC, popescu-v commented on khiops/core/internals/runner.py
> +        - Windows: ``C:\Users\username\khiops\samples``
Ok, good to know; I will make the change.

2023-08-28 11:35 UTC, popescu-v commented on khiops/core/internals/runner.py
> +
This initialization is not lazy, as it is done directly in `__init__` (so that it is not delayed until the `raw_run` is called). If this fails, then we warn the user and fall back to lazy (system-wide only) initialization. Indeed, vendored (Conda-based) initialization need not be lazy, as it cannot work in remoted, partially-initialized environments.

2023-08-28 11:51 UTC, popescu-v commented on khiops/core/internals/runner.py
> +    def _mpi_exec_command(self):
As it stands, no, because this string output serves two purposes (in the vendored case):
- to initialize the `mpi_command_args` attribute (here indeed a split into a list is done)
- to initialize the `KHIOPS_MPI_COMMAND` environment variable, where the string as such is needed; however, I am under the impression that this environment variable is *not needed* in the vendored context. In this case, I could indeed eliminate its assignment in the vendored context and thus return an array directly as you suggest.

2023-08-28 11:52 UTC, popescu-v commented on khiops/core/internals/runner.py
> +            # Linux and Mac OS
All this `if / else` would go away if the `_mpi_exec_command` method returned an array directly.

2023-08-28 11:53 UTC, popescu-v commented on khiops/core/internals/runner.py
> +            cpu_count_command_output, _ = cpu_informer.communicate()
Right, ok.

2023-08-28 12:25 UTC, popescu-v commented on khiops/core/internals/runner.py
> +            # inside Conda environment
Ok, I could encapsulate this in a method like `_check_inside_conda_environment`.

2023-08-28 12:26 UTC, popescu-v commented on khiops/core/internals/runner.py
> +                        # MODL* executable file found
Ok.

2023-08-28 12:26 UTC, popescu-v commented on khiops/core/internals/runner.py
> +            # "C:\Users\username\khiops\samples" on Windows
Ok.

2023-08-28 12:27 UTC, popescu-v commented on khiops/core/internals/runner.py
> +        # Determine which Khiops to run, according to whether one has a
Indeed, the part that starts with "`, according to`" is not relevant anymore; hence, I will remove it.

2023-08-28 12:33 UTC, popescu-v commented on packaging/conda/bld.bat
> +cmake --build --preset windows-msvc-release --parallel --target MODL --target MODL_Coclustering
Yes, ok.

2023-08-28 12:33 UTC, popescu-v commented on packaging/conda/build.sh
> +set -x
Right, ok.

2023-08-28 14:13 UTC, popescu-v commented on khiops/core/internals/runner.py
> +            # inside Conda environment
On second thought, given that this is only used in one place, I think a better comment would suffice.

2023-08-28 17:12 UTC, popescu-v commented on khiops/core/internals/runner.py
> +            - Linux: ``$TMP/khiops``
Ok.

2023-08-28 17:28 UTC, popescu-v commented on .github/workflows/build-conda-package.yml
> +      - name: Download artifacts
Done.

2023-08-28 17:29 UTC, popescu-v commented on .github/workflows/build-conda-package.yml
> +          path: artifacts
Done.

2023-08-28 17:29 UTC, popescu-v commented on .github/workflows/build-conda-package.yml
> +          C:\Miniconda3\envs\true\Scripts\kh-status.exe
Done; Conda environment renamed.

2023-08-28 17:29 UTC, popescu-v commented on .github/workflows/build-conda-package.yml
> +      - name: Download artifacts
Done.

2023-08-28 17:29 UTC, popescu-v commented on khiops/__init__.py
> +class _Wrapper:
Done.

2023-08-28 17:29 UTC, popescu-v commented on .github/workflows/build-pip-package.yml
> +          KHIOPS_LOCATION=$(pip show khiops | awk '/^Location:/ { print $2 }')
Done.

2023-08-28 17:30 UTC, popescu-v commented on khiops/core/internals/runner.py
> +            self._root_temp_dir = tempfile.mkdtemp(prefix="khiops_")
Done.

2023-08-28 17:30 UTC, popescu-v commented on khiops/core/internals/runner.py
> +        The temporary scenarios/templates and dictionary files created by khiops are
Done.

2023-08-28 17:30 UTC, popescu-v commented on khiops/core/internals/runner.py
> +            - Linux: ``$TMP/khiops``
Done.

2023-08-28 17:30 UTC, popescu-v commented on khiops/core/internals/runner.py
> +                + 1
> Refactor to
> 
> ```python
> cpu_entries = [entry for entry in command_output.splitlines() if not entry.startswith("#")]
> return len(cpu_entries) + 1
> ```

Done.

2023-08-28 17:31 UTC, popescu-v commented on khiops/core/internals/runner.py
> +    def _cpu_count(self, command_output):
Done for both requirements.

2023-08-28 17:31 UTC, popescu-v commented on khiops/core/internals/runner.py
> +            n_cores = 1  # number of cores + 1
Done.

2023-08-28 17:31 UTC, popescu-v commented on khiops/core/internals/runner.py
> +                    return int(out.split(" ")[-1]) + 1
Done in both places.

2023-08-28 17:31 UTC, popescu-v commented on khiops/core/internals/runner.py
> +        # The conda environment mpiexec takes precedence over any other mpiexec install
Done.

2023-08-28 17:31 UTC, popescu-v commented on khiops/core/internals/runner.py
> +        - Windows: ``C:\Users\username\khiops\samples``
Done.

2023-08-28 17:32 UTC, popescu-v commented on khiops/core/internals/runner.py
> +
Done: removed the `else` branch.

2023-08-28 17:32 UTC, popescu-v commented on khiops/core/internals/runner.py
> +            # Linux and Mac OS
Done.

2023-08-28 17:32 UTC, popescu-v commented on khiops/core/internals/runner.py
> +            cpu_count_command_output, _ = cpu_informer.communicate()
Done.

2023-08-28 17:33 UTC, popescu-v commented on khiops/core/internals/runner.py
> +            # inside Conda environment
Done: simplified the code and commented it more thoroughly.

2023-08-28 17:33 UTC, popescu-v commented on khiops/core/internals/runner.py
> +                        # MODL* executable file found
Done.

2023-08-28 17:33 UTC, popescu-v commented on khiops/core/internals/runner.py
> +            # "C:\Users\username\khiops\samples" on Windows
Done.

2023-08-28 17:33 UTC, popescu-v commented on khiops/core/internals/runner.py
> +        # Determine which Khiops to run, according to whether one has a
Done: removed the no-longer-relevant part of the comment.

2023-08-28 17:33 UTC, popescu-v commented on packaging/conda/bld.bat
> +cmake --build --preset windows-msvc-release --parallel --target MODL --target MODL_Coclustering
Done.

2023-08-28 17:33 UTC, popescu-v commented on packaging/conda/build.sh
> +set -x
Done.

2023-08-30 17:22 UTC, popescu-v commented on .github/workflows/build-conda-package.yml
> +          python $SAMPLES_SKLEARN -i khiops_coclustering -e
Done. The entry point is called `kh-samples` (to be coherent with the `kh-status` command, and with the `kh` namespace).

2023-08-31 09:07 UTC, felipe-olmos-orange commented on .github/workflows/build-conda-package.yml
> +          echo "SINGLE_VERSION=$SINGLE_VERSION" >> "$GITHUB_ENV"
Ok

2023-08-31 09:11 UTC, felipe-olmos-orange commented on .github/workflows/build-conda-package.yml
> +          # To be removed once GitHub supports Mac OS arm64
Ok

2023-08-31 09:11 UTC, felipe-olmos-orange commented on README.md
> +[TO BE UPDATED]
Ok, we'll see that later.

2023-08-31 09:13 UTC, felipe-olmos-orange commented on khiops/__init__.py
> +            if entry.is_file():
Ok.

2023-08-31 15:32 UTC, felipe-olmos-orange commented on khiops/core/internals/runner.py
> +        """Portably counts the number of cpu cores (no hyperthreading)"""
Here you execute `subprocess.POpen(self._cpu_count_command)` and you can eliminate the parameter. That way the count of cpu is encapsulated.

2023-08-31 15:38 UTC, felipe-olmos-orange commented on khiops/core/internals/version.py
> +import pkg_resources
This API is deprecated, why it is needed?

2023-08-31 15:40 UTC, felipe-olmos-orange commented on khiops/tools.py
> +    **Deprecated** will be removed in Khiops 11, use `kh_status_entry_point` instead.
Add space between title and the paragraph

2023-08-31 16:19 UTC, popescu-v commented on README.md
> +[TO BE UPDATED]
Ok, I will add the part that concerns Conda.

2023-08-31 16:20 UTC, popescu-v commented on khiops/core/internals/runner.py
> +                    continue
Ok, I will add a comment.

2023-08-31 16:20 UTC, popescu-v commented on khiops/core/internals/runner.py
> +    def _mpi_exec_command(self):
Yes, `" ".join(...)` will do I think.

2023-08-31 16:21 UTC, popescu-v commented on khiops/__init__.py
> +        if name.startswith(self.old_name_prefix):
Ok.

2023-08-31 16:22 UTC, popescu-v commented on khiops/__init__.py
> +            sys.modules[module_name] = _DeprecationWrapper(module)
Ok.

2023-08-31 16:26 UTC, popescu-v commented on .github/workflows/build-conda-package.yml
> +          - ubuntu-22.04
IMHO, we need to check a few things:
- that the GitHub actions that we use support this OS.
- that OS support for Miniconda is up-to-date.

2023-08-31 16:28 UTC, popescu-v commented on README.md
> +[TO BE COMPLETED]
Yes, ok.

2023-08-31 16:32 UTC, popescu-v commented on khiops/core/internals/runner.py
> +        - Create a ``$TEMP/khiops/python_<HASH>`` and use it
Right, if `$TEMP/khiops` exists, but is not directory, then there is a problem, which would indeed be solved if we had `$TEMP/khiops_<HASH>/python`.

2023-08-31 16:36 UTC, popescu-v commented on khiops/core/internals/runner.py
> +        """Portably counts the number of cpu cores (no hyperthreading)"""
Yes, right, we can encapsulate the `Popen`, ok.

2023-08-31 16:38 UTC, popescu-v commented on khiops/core/internals/version.py
> +import pkg_resources
It is needed so that we can reliably test the Python version constraint. Otherwise, we would need to (re)-implement ourselves the version comparison logic for the major part and for the minor part as well.

2023-08-31 16:38 UTC, popescu-v commented on khiops/tools.py
> +    """ "Entry point of the kh-samples command"""
Ok.

2023-08-31 16:43 UTC, popescu-v commented on khiops/tools.py
> +            sampler = "core"
I do not think so, because I had noted that you proposed that `kh-samples [other args]` is equivalent to `kh-samples core [other args]`, i.e. to `python samples.py [other args]`.

So, args[0] can be something like `-i` or `-e` etc.  See https://github.com/KhiopsML/khiops-python/pull/91#discussion_r1305386242.

2023-08-31 16:44 UTC, popescu-v commented on packaging/conda/meta.yaml
> +    - mpich <=3.3.2 # [arm64]
Yes, arm64 => Mac OS ARM64 (see https://docs.conda.io/projects/conda-build/en/stable/resources/define-metadata.html): "arm64 | True if the platform is macOS and the Python architecture is arm64." (dixit the web site).

2023-08-31 16:49 UTC, felipe-olmos-orange commented
> > Additionally we should make a converter script to migrate from `pykhiops` to `khiops-python`
> 
> We already provide a deprecation path: users are warned if they import pykhiops or use pk-status.
> 
> Having a converter script would IMHO incur the risk of operating with arbitrary choices, e.g. converting `import pykhiops.core as pk` into `import khiops.core as kh`, where `kh` is an arbitrary choice and, besides, users could have been using something else than `pk` and this would be hard to detect, thus making such a script rather brittle IMHO.
> 
> The deprecation path provides sufficient safeguards IMHO, while being robust enough.

It suffices to change the imports and the classes. The alias for the namespace we can keep it as `pk` in the script.

2023-08-31 16:50 UTC, felipe-olmos-orange commented on .github/workflows/build-conda-package.yml
> +          - ubuntu-22.04
Ok, maybe for another PR

2023-08-31 16:52 UTC, felipe-olmos-orange commented on .github/workflows/build-conda-package.yml
> +          - ubuntu-22.04
https://github.com/KhiopsML/khiops-python/issues/100

2023-08-31 16:54 UTC, felipe-olmos-orange commented on khiops/__init__.py
> +- sklearn: Scikit-Learn classes to execute Khiops
Ok

2023-08-31 16:56 UTC, felipe-olmos-orange commented on khiops/core/internals/version.py
> +import pkg_resources
Is there a non-deprecated API with the same functionality ?

2023-08-31 16:57 UTC, felipe-olmos-orange commented on khiops/tools.py
> +            sampler = "core"
Right. So the error handling is deferred to argparse. Ok

2023-08-31 16:57 UTC, felipe-olmos-orange commented on packaging/conda/meta.yaml
> +    - mpich <=3.3.2 # [arm64]
Ok

2023-08-31 17:00 UTC, felipe-olmos-orange commented on pykhiops/__init__.py
> +sys.modules[__name__] = __import__("khiops")
I mean the `__import__` statement.

2023-08-31 17:08 UTC, popescu-v commented on khiops/core/internals/runner.py
> +          - otherwise, ``%USERPROFILE%\khiops\samples``
So, we stop using %KHIOPS_HOME% (and %KhiopsHome%) as default path for the samples on Windows? We replace this with %PUBLIC%\khiops_data.

Moreover, does this also impact default path behaviour on other platforms (i.e. $HOME/khiops_data/samples instead of $HOME/khiops/samples)?

2023-08-31 17:25 UTC, popescu-v commented on khiops/core/internals/version.py
> +import pkg_resources
None that I am aware of, without relying on extra dependencies (e.g. `packaging` which is indicated by the setuptools documentation itself: https://setuptools.pypa.io/en/latest/pkg_resources.html).

2023-08-31 17:36 UTC, popescu-v commented
> > > Additionally we should make a converter script to migrate from `pykhiops` to `khiops-python`
> > 
> > 
> > We already provide a deprecation path: users are warned if they import pykhiops or use pk-status.
> > Having a converter script would IMHO incur the risk of operating with arbitrary choices, e.g. converting `import pykhiops.core as pk` into `import khiops.core as kh`, where `kh` is an arbitrary choice and, besides, users could have been using something else than `pk` and this would be hard to detect, thus making such a script rather brittle IMHO.
> > The deprecation path provides sufficient safeguards IMHO, while being robust enough.
> 
> It suffices to change the imports and the classes. The alias for the namespace we can keep it as `pk` in the script.

Well, I am still not convinced by the value this would bring with respect to the deprecation warnings that are already in place: the user sees each deprecation warning, then she or he can just change the lines of their scripts one by one to silence the deprecation warnings, right?

2023-08-31 18:02 UTC, popescu-v commented on khiops/tools.py
> +            sampler = "core"
Ok, hence this can be closed, right?

2023-08-31 18:02 UTC, popescu-v commented on khiops/tools.py
> +            sampler = args.pop(0)
Yeah, ok.

2023-09-01 08:51 UTC, felipe-olmos-orange commented on khiops/tools.py
> +            sampler = "core"
Yes

2023-09-01 09:49 UTC, felipe-olmos-orange commented on README.md
> +[TO BE UPDATED]
Done.

2023-09-13 11:43 UTC, felipe-olmos-orange commented on khiops/__init__.py
> +    return ret
Done

2023-09-13 11:46 UTC, felipe-olmos-orange commented on pykhiops/__init__.py
> +sys.modules[__name__] = __import__("khiops")
Done

2023-09-13 11:47 UTC, felipe-olmos-orange commented on khiops/tools.py
> +            sampler = args.pop(0)
Done

2023-09-13 11:47 UTC, felipe-olmos-orange commented on khiops/tools.py
> +    """ "Entry point of the kh-samples command"""
Done

2023-09-13 11:50 UTC, felipe-olmos-orange commented on khiops/tools.py
> +    **Deprecated** will be removed in Khiops 11, use `kh_status_entry_point` instead.
Done

2023-09-13 12:01 UTC, felipe-olmos-orange commented on khiops/core/internals/version.py
> +import pkg_resources
replaced all the code with a `re.sub("^v", "", self.version)` statement.
Done

2023-09-13 12:55 UTC, felipe-olmos-orange commented on khiops/core/internals/runner.py
> +          - otherwise, ``%USERPROFILE%\khiops\samples``
Done

2023-09-13 13:38 UTC, felipe-olmos-orange commented on khiops/core/internals/runner.py
> +        - Create a ``$TEMP/khiops/python_<HASH>`` and use it
Done

2023-09-13 13:40 UTC, felipe-olmos-orange commented on khiops/__init__.py
> +- sklearn: Scikit-Learn classes to execute Khiops
Done

2023-09-13 13:46 UTC, felipe-olmos-orange commented on khiops/__init__.py
> +            sys.modules[module_name] = _DeprecationWrapper(module)
Done (sparsely, we should better document this later)

2023-09-13 13:50 UTC, felipe-olmos-orange commented on khiops/__init__.py
> +    Inspired from https://stackoverflow.com/a/40546615
Not done. Created Issue #101

2023-09-13 13:58 UTC, felipe-olmos-orange commented on khiops/core/internals/runner.py
> +                + 1
Refactored to just one function.

2023-09-13 13:59 UTC, felipe-olmos-orange commented on khiops/core/internals/runner.py
> +    def _mpi_exec_command(self):
Done

2023-09-13 13:59 UTC, felipe-olmos-orange commented on README.md
> +[TO BE COMPLETED]
Done

2023-09-13 14:00 UTC, felipe-olmos-orange commented on khiops/core/internals/runner.py
> +        """Portably counts the number of cpu cores (no hyperthreading)"""
Done

2023-09-13 14:01 UTC, felipe-olmos-orange commented on khiops/core/internals/runner.py
> +                    continue
Refactored and done.

2023-09-22 13:08 UTC, felipe-olmos-orange commented
I removed the deprecation wrapper because of two reasons:
1) It broke the sphinx mechanism to link cross-references
2) It augmented the startup time enough to double the execution time in small datasets (eg. `Adult`).

2023-09-22 13:45 UTC, felipe-olmos-orange approved these changes

2023-09-22 13:45 UTC, merged