92 add workflows for automatic testing
KhiopsML/khiops-python pull request #93
Opened 2023-07-06 16:14 UTC by popescu-v

2023-07-10 13:36 UTC, felipe-olmos-orange requested changes

2023-07-10 13:36 UTC, felipe-olmos-orange commented on .github/workflows/build-ubuntu-khiops-container.yml
> +          ref: 92-add-workflows-for-automatic-testing
remove this

2023-07-10 13:36 UTC, felipe-olmos-orange commented on .github/workflows/build-ubuntu-khiops-container.yml
> +          ref: 39-add-learningtest-lite-to-the-repo # WIP; to remove after merge to dev
Can we remove it *before* the merge ?

2023-07-10 13:36 UTC, felipe-olmos-orange commented on .github/workflows/build-ubuntu-khiops-container.yml
> +        with:
This is the container to run the tests ? It should not contain the khiops-python sources

2023-07-10 13:36 UTC, felipe-olmos-orange commented on .github/workflows/run-unit-tests.yml
> +            fetch-depth: 0 # Get all tags
why you want all tags, shouldn't be only the latest version ?

2023-07-10 13:36 UTC, felipe-olmos-orange commented on .github/workflows/run-unit-tests.yml
> +          mkdir -p -m 777 ${{github.workspace}}/reports
Maybe use the more readable notation `user+rwx`

2023-07-10 13:36 UTC, felipe-olmos-orange commented on .github/workflows/run-unit-tests.yml
> +          coverage xml -o "reports/py-coverage.xml"
Use the mechanic of long tests as before. There should be the summary table in the logs

2023-07-10 13:36 UTC, felipe-olmos-orange commented on .github/workflows/run-unit-tests.yml
> +      - name: Display Unit Test Reports
Where I can see the reports ? I didn't find it in the workflow run page

2023-07-10 13:36 UTC, felipe-olmos-orange commented on .github/workflows/build-ubuntu-khiops-container.yml
> +        # push: ${{ github.ref == 'refs/heads/main' }}
Either uncomment or remove

2023-07-10 13:39 UTC, popescu-v commented on .github/workflows/build-ubuntu-khiops-container.yml
> +          ref: 92-add-workflows-for-automatic-testing
This is needed for the `packaging/linux/common/{khiops,khiops_coclustering,khiops-env}` which are not on `dev` (yet).

2023-07-10 13:45 UTC, popescu-v commented on .github/workflows/build-ubuntu-khiops-container.yml
> +        with:
I did this in order to be able to use the Dockerfile in the `docker/build-push-action@v2`. But it is deleted in the Dockerfile itself, so it is not in the resulting image.

2023-07-10 13:49 UTC, popescu-v commented on .github/workflows/run-unit-tests.yml
> +            fetch-depth: 0 # Get all tags
I wanted to make sure versioneer is able to properly compute the current version, for whichever version. Without this constraint, tags are not retrieved, hence the versioneer fails to compute a meaningful version.

2023-07-10 13:49 UTC, popescu-v commented on .github/workflows/run-unit-tests.yml
> +          mkdir -p -m 777 ${{github.workspace}}/reports
Ok for this :+1:

2023-07-10 13:51 UTC, popescu-v commented on .github/workflows/run-unit-tests.yml
> +      - name: Display Unit Test Reports
The URL is in the log: https://github.com/KhiopsML/khiops-python/runs/14911515934. This URL can be seen from the workflow log, e.g. https://github.com/KhiopsML/khiops-python/actions/runs/5508457314/jobs/10039763057

2023-07-10 13:54 UTC, popescu-v commented on .github/workflows/build-ubuntu-khiops-container.yml
> +        # push: ${{ github.ref == 'refs/heads/main' }}
Ok to remove. We can keep the workflow in manual launching mode.

2023-07-10 15:22 UTC, felipe-olmos-orange commented on .github/workflows/build-ubuntu-khiops-container.yml
> +          ref: 92-add-workflows-for-automatic-testing
But before merging we should eliminate (or put main if it is not the default). You can create the image now, and then recreate it from master.

2023-07-10 15:23 UTC, felipe-olmos-orange commented on .github/workflows/build-ubuntu-khiops-container.yml
> +          ref: 39-add-learningtest-lite-to-the-repo # WIP; to remove after merge to dev
Then we will merge once that branch will be merged (which is soon).

2023-07-10 15:24 UTC, felipe-olmos-orange commented on .github/workflows/run-unit-tests.yml
> +            fetch-depth: 0 # Get all tags
Ok, explain better the comment then.

2023-07-10 15:26 UTC, popescu-v commented on .github/workflows/build-ubuntu-khiops-container.yml
> +          ref: 92-add-workflows-for-automatic-testing
Yes, we can eliminate the `ref:` before merging, as this workflow isn't launched on each push / merge / pull_request event anyway.

2023-07-10 15:28 UTC, felipe-olmos-orange commented on .github/workflows/build-ubuntu-khiops-container.yml
> +          file: ./khiops-python/packaging/docker/Dockerfile.ubuntu22.04-khiops
`khiopspydev` ?

2023-07-10 15:43 UTC, popescu-v commented on .github/workflows/build-ubuntu-khiops-container.yml
> +          file: ./khiops-python/packaging/docker/Dockerfile.ubuntu22.04-khiops
Ok for `khiopspydev-ubuntu22.04`, then.

2023-07-10 17:44 UTC, popescu-v commented on .github/workflows/build-ubuntu-khiops-container.yml
> +          ref: 92-add-workflows-for-automatic-testing
Changed the comment accordingly.

2023-07-10 17:44 UTC, popescu-v commented on .github/workflows/build-ubuntu-khiops-container.yml
> +          ref: 39-add-learningtest-lite-to-the-repo # WIP; to remove after merge to dev
Changed the comment accordingly.

2023-07-10 17:46 UTC, popescu-v commented on .github/workflows/run-unit-tests.yml
> +          mkdir -p -m 777 ${{github.workspace}}/reports
Done.

2023-07-10 17:46 UTC, popescu-v commented on .github/workflows/run-unit-tests.yml
> +          coverage xml -o "reports/py-coverage.xml"
Done. To be fully tested on merge into `dev`.

2023-07-10 17:47 UTC, popescu-v commented on .github/workflows/build-ubuntu-khiops-container.yml
> +          file: ./khiops-python/packaging/docker/Dockerfile.ubuntu22.04-khiops
Done. Renamed.

2023-07-10 17:47 UTC, popescu-v commented on .github/workflows/build-ubuntu-khiops-container.yml
> +          tags: ghcr.io/khiopsml/khiops-python/ubuntu22.04-khiops-python:latest
Full path kept (see above).

2023-07-11 12:18 UTC, felipe-olmos-orange requested changes
There is still 2 small changes.

2023-07-11 12:18 UTC, felipe-olmos-orange commented on .github/workflows/run-unit-tests.yml
> +            fetch-depth: 0 # Get all tags
Ok

2023-07-11 12:18 UTC, felipe-olmos-orange commented on .github/workflows/run-unit-tests.yml
> +          coverage xml -o "reports/py-coverage.xml"
Ok

2023-07-11 12:18 UTC, felipe-olmos-orange commented on .github/workflows/build-ubuntu-khiops-container.yml
> +        # push: ${{ github.ref == 'refs/heads/main' }}
Ok

2023-07-11 12:18 UTC, felipe-olmos-orange commented on .github/workflows/build-ubuntu-khiops-container.yml
> +          tags: ghcr.io/khiopsml/khiops-python/ubuntu22.04-khiops-python:latest
Ok

2023-07-11 12:18 UTC, felipe-olmos-orange commented on .github/workflows/run-unit-tests.yml
> +          fi
This is ok! Could you add a `workflow_dispatch` input so when we run it manually we can choose to run long tests ?

2023-07-11 12:19 UTC, felipe-olmos-orange commented on .github/workflows/build-ubuntu-khiops-container.yml
> +          ref: 39-add-learningtest-lite-to-the-repo # WIP; to remove after merge to dev
This is ready to be merged. Maybe the version of khiops can be a `workflow_dispatch` parameter ?

2023-07-11 15:10 UTC, popescu-v commented on .github/workflows/build-ubuntu-khiops-container.yml
> +          ref: 39-add-learningtest-lite-to-the-repo # WIP; to remove after merge to dev
Perhaps (if needed): thread the version to the ref through the workflow_dispatch. For now, I have removed the ref altogether.

2023-07-11 15:12 UTC, popescu-v commented on .github/workflows/run-unit-tests.yml
> +          fi
Ok, I will see into it.

2023-07-11 15:13 UTC, popescu-v commented on .github/workflows/build-ubuntu-khiops-container.yml
> +name: Build Ubuntu Khiops container
Ok.

2023-07-11 15:31 UTC, popescu-v commented on .github/workflows/build-ubuntu-khiops-container.yml
> +name: Build Ubuntu Khiops container
Done. And fixed YAMLs.

2023-07-12 14:25 UTC, popescu-v commented on .github/workflows/build-ubuntu-khiops-container.yml
> +          ref: 39-add-learningtest-lite-to-the-repo # WIP; to remove after merge to dev
> The patch we were waiting is merged. But maybe the version of khiops can be a `workflow_dispatch` parameter ?

Can we use the Git tag of the khiops repo for this?

2023-07-12 15:27 UTC, popescu-v commented on .github/workflows/run-unit-tests.yml
> +          fi
So, the desired behavior is: if on `dev` or `main` branch, always run long tests. Otherwise (i.e. not not `dev`, neither on `main`), then: if the input to run the long tests is true, then run the long tests; otherwise, don't run the long tests.
Is this ok, @felipe-olmos-orange ?

2023-07-12 16:36 UTC, popescu-v commented on .github/workflows/run-unit-tests.yml
> +          fi
Done. Implemented thus: if not on 'main' or 'dev': if 'run-long-tests' is not true: set `UNITTEST_ONLY_SHORT_TESTS` to `true`.

2023-07-13 09:28 UTC, felipe-olmos-orange commented on .github/workflows/run-unit-tests.yml
> +          fi
> So, the desired behavior is: if on `dev` or `main` branch, always run long tests. Otherwise (i.e. not not `dev`, neither on `main`), then: if the input to run the long tests is true, then run the long tests; otherwise, don't run the long tests. Is this ok, @felipe-olmos-orange ?

Yes exactly.

2023-07-13 10:00 UTC, popescu-v commented on .github/workflows/run-unit-tests.yml
> +          fi
> Just one more thing, could you please upload as artifiacts the results for scenario tests and report and their references. This way we can quickly see what went wrong.

Ok.

2023-07-18 09:19 UTC, popescu-v commented
> There is still 2 small changes.

IMHO, the comment thread left open with the `ref:` to the Khiops branch can be closed now.

2023-07-18 09:26 UTC, popescu-v commented on .github/workflows/build-ubuntu-khiops-container.yml
> +          ref: 39-add-learningtest-lite-to-the-repo # WIP; to remove after merge to dev
This is doable: the Khiops tag can be put in the `ref:`, once the Khiops tags are pushed to the `khiops` repo. For now, the `dev` version of the `khiops` repo is pulled (as this is the default branch), which currently works but is not felicitous.

2023-07-20 18:03 UTC, felipe-olmos-orange commented on .github/workflows/run-unit-tests.yml
> +          fi
Yes but the generated scenario files aren't there :(

2023-07-20 18:05 UTC, felipe-olmos-orange approved these changes

2023-07-21 10:10 UTC, popescu-v commented on .github/workflows/run-unit-tests.yml
> +          fi
Done. Scenarios and references are there now.

2023-07-21 13:50 UTC, merged